//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;P" +
            "assword=uuiikkjj98$10")]
        public string AdminReportingVNSConnectionString37 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString37"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=54.245.226.146;Initial Catalog=AdminReportingLog;Persist Security Inf" +
            "o=True;User ID=linkit_user")]
        public string AdminReportingLogConnectionString {
            get {
                return ((string)(this["AdminReportingLogConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info" +
            "=True;User ID=linkit_user;Pooling=False")]
        public string AdminReportingVNSConnectionString21 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString21"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info" +
            "=True;User ID=linkit_user;Password=uuiikkjj98$10;Pooling=False")]
        public string AdminReportingVNSConnectionString3 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info" +
            "=True;User ID=linkit_user")]
        public string AdminReportingVNSConnectionString34 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString34"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;C" +
            "onnect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string AdminReportingVNSConnectionString {
            get {
                return ((string)(this["AdminReportingVNSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;P" +
            "assword=uuiikkjj98$10;Connect Timeout=30;Encrypt=False;TrustServerCertificate=Fa" +
            "lse")]
        public string AdminReportingVNSConnectionString1 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.252.56.238;Initial Catalog=AdminReportingTemp;Persist Security Inf" +
            "o=True;User ID=DevblockDev")]
        public string AdminReportingTempConnectionString11 {
            get {
                return ((string)(this["AdminReportingTempConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info" +
            "=True;User ID=linkit_user;Pooling=False")]
        public string AdminReportingVNSConnectionString2 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.252.36.127;Persist Security Info=True;User ID=DevblockDev")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.252.36.127;Initial Catalog=AdminReportingStage;Persist Security In" +
            "fo=True;User ID=DevblockDev")]
        public string AdminReportingStageConnectionString {
            get {
                return ((string)(this["AdminReportingStageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;C" +
            "onnect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string AdminReportingVNSConnectionString30 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString30"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;C" +
            "onnect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string AdminReportingVNSConnectionString32 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString32"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.252.36.127;Initial Catalog=AdminReportingStage;User ID=DevblockDev" +
            ";Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string AdminReportingStageConnectionString1 {
            get {
                return ((string)(this["AdminReportingStageConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;C" +
            "onnect Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string AdminReportingVNSConnectionString4 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info" +
            "=True;User ID=linkit_user")]
        public string AdminReportingVNSConnectionString5 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info" +
            "=True;User ID=linkit_user;MultipleActiveResultSets=True;Application Name=EntityF" +
            "ramework")]
        public string AdminReportingVNSConnectionString31 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString31"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;P" +
            "assword=V7npJYVx8xmKFZ9;Connect Timeout=30;Encrypt=True;TrustServerCertificate=T" +
            "rue")]
        public string AdminReportingVNSConnectionString6 {
            get {
                return ((string)(this["AdminReportingVNSConnectionString6"]));
            }
        }
    }
}
