<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="APILogContextDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.245.226.146;Initial Catalog=AdminReportingVNS;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString17" Provider="System.Data.SqlClient" />
  <Table Name="dbo.APILog" Member="APILogEntities" AccessModifier="Internal">
    <Type Name="APILogEntity" AccessModifier="Internal">
      <Column Name="APILogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ResponseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RequestURL" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="HTTPMethod" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Exception" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ResponseStatus" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="DataPosted" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="APIName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="ExceptionDetails" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResetPasswordLog" Member="ResetPasswordLogEntities" AccessModifier="Internal">
    <Type Name="ResetPasswordLogEntity" AccessModifier="Internal">
      <Column Name="ResetPasswordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DistrictCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="Char(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConfigurationPortalLog" Member="ConfigurationPortalLogEntities">
    <Type Name="ConfigurationPortalLogEntity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Controller" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IsLogInput" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsLogOutput" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LogKeys" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteAPILogByListIDs" Method="DeleteAPILogByListIDs">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteAPILogByFilter" Method="DeleteAPILogByFilter">
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="APIName" Parameter="aPIName" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="ResponseStatus" Parameter="responseStatus" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>