<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="DataLockerContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.TestResultScoreNote" Member="TestResultScoreNoteEntities" AccessModifier="Internal">
    <Type Name="TestResultScoreNoteEntity" AccessModifier="Internal">
      <Column Name="TestResultScoreNotesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NoteKey" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TestResultScoreDLEntity_TestResultScoreNoteEntity" Member="TestResultScoreDLEntity" ThisKey="TestResultScoreID" OtherKey="TestResultScoreID" Type="TestResultScoreDLEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultSubScoreNote" Member="TestResultSubScoreNoteEntities" AccessModifier="Internal">
    <Type Name="TestResultSubScoreNoteEntity" AccessModifier="Internal">
      <Column Name="TestResultSubScoreNotesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NoteKey" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TestResultSubScoreDLEntity_TestResultSubScoreNoteEntity" Member="TestResultSubScoreDLEntity" ThisKey="TestResultSubScoreID" OtherKey="TestResultSubScoreID" Type="TestResultSubScoreDLEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomScoreDistrictShare" Member="VirtualTestCustomScoreDistrictShareEntities" AccessModifier="Internal">
    <Type Name="VirtualTestCustomScoreDistrictShareEntity" AccessModifier="Internal">
      <Column Name="VirtualTestCustomScoreDistrictShareID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DTLDistrictEntity_VirtualTestCustomScoreDistrictShareEntity" Member="DTLDistrictEntity" Storage="_District" ThisKey="DistrictID" OtherKey="DistrictID" Type="DTLDistrictEntity" IsForeignKey="true" />
      <Association Name="UserDLEntity_VirtualTestCustomScoreDistrictShareEntity" Member="UserDLEntity" ThisKey="CreatedUserID" OtherKey="UserID" Type="UserDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.District" Member="DTLDistrictEntities" AccessModifier="Internal">
    <Type Name="DTLDistrictEntity" AccessModifier="Internal">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneOffsetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="DTLDistrictEntity_VirtualTestCustomScoreDistrictShareEntity" Member="VirtualTestCustomScoreDistrictShareEntities" Storage="_VirtualTestCustomScoreDistrictShares" ThisKey="DistrictID" OtherKey="DistrictID" Type="VirtualTestCustomScoreDistrictShareEntity" />
      <Association Name="DTLDistrictEntity_UserDLEntity" Member="UserDLEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="UserDLEntity" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultScoreUploadFile" Member="TestResultScoreUploadFileEntities">
    <Type Name="TestResultScoreUploadFileEntity">
      <Column Name="TestResultScoreUploadFileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsUrl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UploadedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DocumentGUID" Type="System.Guid" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DTLAutoSaveResultData" Member="DTLAutoSaveResultDataEntities">
    <Type Name="DTLAutoSaveResultDataEntity">
      <Column Name="DTLAutoSaveResultDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentTestResultScoresJson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentTestResultSubScoresJson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualTestResultScoresJson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomSubScore" Member="VirtualTestCustomSubScoreEntities" AccessModifier="Internal">
    <Type Name="VirtualTestCustomSubScoreEntity" AccessModifier="Internal">
      <Column Name="VirtualTestCustomSubScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsePercentile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseAchievementLevel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScaledScoreMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScaledScoreMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseCustomN_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomN_1_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_2_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_3_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_4_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_1_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_2_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_1_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomA_2_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UseCustomA_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomA_3_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_4_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_3_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomA_4_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_1_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_2_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_3_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_4_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_1_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_2_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_3_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_4_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemTagID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseArtifact" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseNote" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="VirtualTestCustomSubScoreEntity_VirtualTestCustomMetaDataEntity" Member="VirtualTestCustomMetaDataEntities" ThisKey="VirtualTestCustomSubScoreID" OtherKey="VirtualTestCustomSubScoreID" Type="VirtualTestCustomMetaDataEntity" />
      <Association Name="VirtualTestCustomSubScoreEntity_VirtualTestCustomMetaDataDLEntity" Member="VirtualTestCustomMetaDataDLEntities" ThisKey="VirtualTestCustomSubScoreID" OtherKey="VirtualTestCustomSubScoreID" Type="VirtualTestCustomMetaDataDLEntity" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomMetaData" Member="VirtualTestCustomMetaDataEntities" AccessModifier="Internal">
    <Type Name="VirtualTestCustomMetaDataEntity" AccessModifier="Internal">
      <Column Name="VirtualTestCustomMetaDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MetaData" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VirtualTestCustomSubScoreEntity_VirtualTestCustomMetaDataEntity" Member="VirtualTestCustomSubScoreEntity" ThisKey="VirtualTestCustomSubScoreID" OtherKey="VirtualTestCustomSubScoreID" Type="VirtualTestCustomSubScoreEntity" IsForeignKey="true" />
      <Association Name="VirtualTestCustomScoreDLEntity_VirtualTestCustomMetaDataEntity" Member="VirtualTestCustomScoreDLEntity" ThisKey="VirtualTestCustomScoreID" OtherKey="VirtualTestCustomScoreID" Type="VirtualTestCustomScoreDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomScoreView" Member="VirtualTestCustomScoreViews" AccessModifier="Internal">
    <Type Name="VirtualTestCustomScoreView" AccessModifier="Internal">
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuthorUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TotalVirtualTestAssociated" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsMultiDate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTest" Member="VirtualTestDLEntities" AccessModifier="Internal">
    <Type Name="VirtualTestDLEntity" AccessModifier="Internal">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AuthorUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EditedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Instruction" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PreQTIVirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreProdVTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestScoreMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestSubTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetOriginID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsTeacherLed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsePointsEarnedConversion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasUseRationale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsNumberQuestions" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMultipleTestResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NavigationMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginalTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VirtualTestDLEntity_TestResultDLEntity" Member="TestResultDLEntities" ThisKey="VirtualTestID" OtherKey="VirtualTestID" Type="TestResultDLEntity" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="UserDLEntities" AccessModifier="Internal">
    <Type Name="UserDLEntity" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hint" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Privileges]" Member="Privileges" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APIaccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GUIDcode" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SISID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HashedPassword" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HasTemporaryPassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PasswordLastSetDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateConfirmedActive" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MessageNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TermOfUseAccepted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(102) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="UserDLEntity_VirtualTestCustomScoreDistrictShareEntity" Member="VirtualTestCustomScoreDistrictShareEntities" ThisKey="UserID" OtherKey="CreatedUserID" Type="VirtualTestCustomScoreDistrictShareEntity" />
      <Association Name="UserDLEntity_PreferenceDLEntity" Member="PreferenceDLEntities" ThisKey="UserID" OtherKey="UpdatedBy" Type="PreferenceDLEntity" />
      <Association Name="UserDLEntity_StudentUserDLEntity" Member="StudentUserDLEntities" ThisKey="UserID" OtherKey="UserId" Type="StudentUserDLEntity" />
      <Association Name="DTLDistrictEntity_UserDLEntity" Member="DTLDistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DTLDistrictEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="ClassDLEntities" AccessModifier="Internal">
    <Type Name="ClassDLEntity" AccessModifier="Internal">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Period" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TrackAttendance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ClassDLEntity_TestResultDLEntity" Member="TestResultDLEntities" ThisKey="ClassID" OtherKey="ClassID" Type="TestResultDLEntity" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="StudentDLEntities" AccessModifier="Internal">
    <Type Name="StudentDLEntity" AccessModifier="Internal">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LoginCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dateofbirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrimaryLanguageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Note01" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CurrentGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(202) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RegistrationCodeEmailLastSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="StudentDLEntity_TestResultDLEntity" Member="TestResultDLEntities" ThisKey="StudentID" OtherKey="StudentID" Type="TestResultDLEntity" />
      <Association Name="StudentDLEntity_StudentUserDLEntity" Member="StudentUserDLEntities" ThisKey="StudentID" OtherKey="StudentId" Type="StudentUserDLEntity" />
    </Type>
  </Table>
  <Table Name="dbo.TestResult" Member="TestResultDLEntities" AccessModifier="Internal">
    <Type Name="TestResultDLEntity" AccessModifier="Internal">
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TRData" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="SubmitType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginalUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LegacyBatchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BubbleSheetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestResultDLEntity_TestResultScoreDLEntity" Member="TestResultScoreDLEntities" ThisKey="TestResultID" OtherKey="TestResultID" Type="TestResultScoreDLEntity" />
      <Association Name="ClassDLEntity_TestResultDLEntity" Member="ClassDLEntity" ThisKey="ClassID" OtherKey="ClassID" Type="ClassDLEntity" IsForeignKey="true" />
      <Association Name="StudentDLEntity_TestResultDLEntity" Member="StudentDLEntity" ThisKey="StudentID" OtherKey="StudentID" Type="StudentDLEntity" IsForeignKey="true" />
      <Association Name="VirtualTestDLEntity_TestResultDLEntity" Member="VirtualTestDLEntity" ThisKey="VirtualTestID" OtherKey="VirtualTestID" Type="VirtualTestDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultScore" Member="TestResultScoreDLEntities" AccessModifier="Internal">
    <Type Name="TestResultScoreDLEntity" AccessModifier="Internal">
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TookTest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreIndex" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsePercentage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseIndex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseGradeLevelEquiv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScoreGradeLevelEquiv" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MetStandard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AchieveLevelName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TestResultScoreDLEntity_TestResultScoreNoteEntity" Member="TestResultScoreNoteEntities" ThisKey="TestResultScoreID" OtherKey="TestResultScoreID" Type="TestResultScoreNoteEntity" />
      <Association Name="TestResultScoreDLEntity_TestResultSubScoreDLEntity" Member="TestResultSubScoreDLEntities" ThisKey="TestResultScoreID" OtherKey="TestResultScoreID" Type="TestResultSubScoreDLEntity" />
      <Association Name="TestResultDLEntity_TestResultScoreDLEntity" Member="TestResultDLEntity" ThisKey="TestResultID" OtherKey="TestResultID" Type="TestResultDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultSubScore" Member="TestResultSubScoreDLEntities" AccessModifier="Internal">
    <Type Name="TestResultSubScoreDLEntity" AccessModifier="Internal">
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsePercentage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseGradeLevelEquiv" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ScoreGradeLevelEquiv" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="MetStandard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreIndex" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Association Name="TestResultSubScoreDLEntity_TestResultSubScoreNoteEntity" Member="TestResultSubScoreNoteEntities" ThisKey="TestResultSubScoreID" OtherKey="TestResultSubScoreID" Type="TestResultSubScoreNoteEntity" />
      <Association Name="TestResultScoreDLEntity_TestResultSubScoreDLEntity" Member="TestResultScoreDLEntity" ThisKey="TestResultScoreID" OtherKey="TestResultScoreID" Type="TestResultScoreDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultScoreUploadFile" Member="TestResultScoreUploadFileDLEntities" AccessModifier="Internal">
    <Type Name="TestResultScoreUploadFileDLEntity" AccessModifier="Internal">
      <Column Name="TestResultScoreUploadFileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsUrl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UploadedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DocumentGUID" Type="System.Guid" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Preferences" Member="PreferenceDLEntities" AccessModifier="Internal">
    <Type Name="PreferenceDLEntity" AccessModifier="Internal">
      <Column Name="PreferenceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserDLEntity_PreferenceDLEntity" Member="UserDLEntity" ThisKey="UpdatedBy" OtherKey="UserID" Type="UserDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QTITestClassAssignment" Member="QTITestClassAssignmentDLEntities" AccessModifier="Internal">
    <Type Name="QTITestClassAssignmentDLEntity" AccessModifier="Internal">
      <Column Name="QTITestClassAssignmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignmentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CodeTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignmentGUID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TestSetting" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ComparisonPasscodeLength" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsHide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SurveyAssignmentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListOfDisplayQuestions" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="QTITestClassAssignmentDLEntity_QTITestStudentAssignmentDLEntity" Member="QTITestStudentAssignmentDLEntities" ThisKey="QTITestClassAssignmentID" OtherKey="QTITestClassAssignmentID" Type="QTITestStudentAssignmentDLEntity" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomMetaData" Member="VirtualTestCustomMetaDataDLEntities" AccessModifier="Internal">
    <Type Name="VirtualTestCustomMetaDataDLEntity" AccessModifier="Internal">
      <Column Name="VirtualTestCustomMetaDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MetaData" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VirtualTestCustomSubScoreEntity_VirtualTestCustomMetaDataDLEntity" Member="VirtualTestCustomSubScoreEntity" ThisKey="VirtualTestCustomSubScoreID" OtherKey="VirtualTestCustomSubScoreID" Type="VirtualTestCustomSubScoreEntity" IsForeignKey="true" />
      <Association Name="VirtualTestCustomScoreDLEntity_VirtualTestCustomMetaDataDLEntity" Member="VirtualTestCustomScoreDLEntity" ThisKey="VirtualTestCustomScoreID" OtherKey="VirtualTestCustomScoreID" Type="VirtualTestCustomScoreDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTest_VirtualTestCustomScore" Member="VirtualTest_VirtualTestCustomScoreDLEntities" AccessModifier="Internal">
    <Type Name="VirtualTest_VirtualTestCustomScoreDLEntity" AccessModifier="Internal">
      <Column Name="VirtualTest_VirtualTestCustomScore" Member="VirtualTest_VirtualTestCustomScore1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StudentUser" Member="StudentUserDLEntities" AccessModifier="Internal">
    <Type Name="StudentUserDLEntity" AccessModifier="Internal">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentDLEntity_StudentUserDLEntity" Member="StudentDLEntity" ThisKey="StudentId" OtherKey="StudentID" Type="StudentDLEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UserDLEntity_StudentUserDLEntity" Member="UserDLEntity" ThisKey="UserId" OtherKey="UserID" Type="UserDLEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QTITestStudentAssignment" Member="QTITestStudentAssignmentDLEntities" AccessModifier="Internal">
    <Type Name="QTITestStudentAssignmentDLEntity" AccessModifier="Internal">
      <Column Name="QTITestStudentAssignmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTITestClassAssignmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QTITestClassAssignmentDLEntity_QTITestStudentAssignmentDLEntity" Member="QTITestClassAssignmentDLEntity" ThisKey="QTITestClassAssignmentID" OtherKey="QTITestClassAssignmentID" Type="QTITestClassAssignmentDLEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomScore" Member="VirtualTestCustomScoreDLEntities" AccessModifier="Internal">
    <Type Name="VirtualTestCustomScoreDLEntity" AccessModifier="Internal">
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsePercentile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseAchievementLevel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScaledScoreMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScaledScoreMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseCustomN_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomN_1_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_2_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_3_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_4_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_1_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_2_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_1_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomA_2_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UseCustomA_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomA_3_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_4_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_3_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomA_4_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankLabel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestScoreMethodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSubTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomN_1_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_2_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_3_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_4_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_1_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_2_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_3_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_4_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthorUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UseArtifact" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseNote" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMultiDate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseIndex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseGradeLevelEquiv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DataSetOriginID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="VirtualTestCustomScoreDLEntity_VirtualTestCustomMetaDataEntity" Member="VirtualTestCustomMetaDataEntities" ThisKey="VirtualTestCustomScoreID" OtherKey="VirtualTestCustomScoreID" Type="VirtualTestCustomMetaDataEntity" />
      <Association Name="VirtualTestCustomScoreDLEntity_VirtualTestCustomMetaDataDLEntity" Member="VirtualTestCustomMetaDataDLEntities" ThisKey="VirtualTestCustomScoreID" OtherKey="VirtualTestCustomScoreID" Type="VirtualTestCustomMetaDataDLEntity" />
    </Type>
  </Table>
  <Function Name="dbo.DTLTemplateHasAssociatedTestResult" Method="DTLTemplateHasAssociatedTestResult">
    <Parameter Name="VirtualTestCustomScoreId" Parameter="virtualTestCustomScoreId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLDeleteSubscore" Method="DTLDeleteSubscore">
    <Parameter Name="VirtualTestCustomSubScoreId" Parameter="virtualTestCustomSubScoreId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLDeleteTemplate" Method="DTLDeleteTemplate">
    <Parameter Name="VirtualTestCustomScoreId" Parameter="virtualTestCustomScoreId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteVirtualTestLegacyByID" Method="DeleteVirtualTestLegacyByID">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Error" Parameter="error" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLCopyTemplateByID" Method="DTLCopyTemplateByID">
    <Parameter Name="TemplateID" Parameter="templateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TemplateNameNew" Parameter="templateNameNew" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="DTLCopyTemplateByIDResult">
      <Column Name="TemplateIDNew" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DTLDeleteAllAutoSaveData" Method="DTLDeleteAllAutoSaveData">
    <Parameter Name="VirtualTestId" Parameter="virtualTestId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLGetStudentAndTestResultSubScore" Method="DTLGetStudentAndTestResultSubScore">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentIDs" Parameter="studentIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="DTLGetStudentAndTestResultSubScoreResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DTLSaveEntryResults" Method="DTLSaveEntryResults">
    <Parameter Name="TestResultXML" Parameter="testResultXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultScoreXML" Parameter="testResultScoreXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultSubScoreXML" Parameter="testResultSubScoreXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultScoreNoteXML" Parameter="testResultScoreNoteXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultSubScoreNoteXML" Parameter="testResultSubScoreNoteXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultScoreUploadFileXML" Parameter="testResultScoreUploadFileXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultSubScoreUploadFileXML" Parameter="testResultSubScoreUploadFileXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="DeleteTestResultIdList" Parameter="deleteTestResultIdList" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLUpdateOrderForMetaData" Method="DTLUpdateOrderForMetaData">
    <Parameter Name="VirtualTestCustomScoreId" Parameter="virtualTestCustomScoreId" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestCustomSubScoreId" Parameter="virtualTestCustomSubScoreId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ScoreTypeOrder" Parameter="scoreTypeOrder" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetFormBanksByUserID" Method="GetFormBanksByUserID">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="userSchoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="userDistrictID" Type="System.Int32" DbType="Int" />
    <Parameter Name="showArchived" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="hideBankOnlyTest" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetFormBanksByUserIDResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GradeOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DTLDeleteAllAutoSaveDataBaseDate" Method="DTLDeleteAllAutoSaveDataBaseDate">
    <Parameter Name="VirtualTestId" Parameter="virtualTestId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLSaveEntryResultsMultiple" Method="DTLSaveEntryResultsMultiple">
    <Parameter Name="TestResultXML" Parameter="testResultXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultScoreXML" Parameter="testResultScoreXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultSubScoreXML" Parameter="testResultSubScoreXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultScoreNoteXML" Parameter="testResultScoreNoteXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultSubScoreNoteXML" Parameter="testResultSubScoreNoteXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultScoreUploadFileXML" Parameter="testResultScoreUploadFileXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="TestResultSubScoreUploadFileXML" Parameter="testResultSubScoreUploadFileXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="DeleteTestResultIdList" Parameter="deleteTestResultIdList" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ProcBankFormBank" Method="ProcBankFormBank">
    <Parameter Name="SubjectId" Parameter="subjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleId" Parameter="userRoleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsFromMultiDate" Parameter="isFromMultiDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsingMultiDate" Parameter="usingMultiDate" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="ProcBankFormBankResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankAccessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetFormDataLockerByBankID" Method="GetFormDataLockerByBankID">
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsFromMultiDate" Parameter="isFromMultiDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsingMultiDate" Parameter="usingMultiDate" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetFormDataLockerByBankIDResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="IsMultiDate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetFormBanksByMultipleSubjectIds" Method="GetFormBanksByMultipleSubjectIds">
    <Parameter Name="SubjectId" Parameter="subjectId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleId" Parameter="userRoleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsFromMultiDate" Parameter="isFromMultiDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UsingMultiDate" Parameter="usingMultiDate" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetFormBanksByMultipleSubjectIdsResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankAccessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DTLArchiveTemplate" Method="DTLArchiveTemplate">
    <Parameter Name="VirtualTestCustomScoreId" Parameter="virtualTestCustomScoreId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Archived" Parameter="archived" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DTLGetStudentAndTestResultScoreMultiple" Method="DTLGetStudentAndTestResultScoreMultiple">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentIDs" Parameter="studentIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="EntryDate" Parameter="entryDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="DTLGetStudentAndTestResultScoreMultipleResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DTLGetStudentAndTestResultSubScoreMultiple" Method="DTLGetStudentAndTestResultSubScoreMultiple">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentIDs" Parameter="studentIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="EntryDate" Parameter="entryDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="DTLGetStudentAndTestResultSubScoreMultipleResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DTLGetStudentAndTestResultScore" Method="DTLGetStudentAndTestResultScore">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentIDs" Parameter="studentIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="DTLGetStudentAndTestResultScoreResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>