<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingStage" Class="DbDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Request" Member="RequestEntities" AccessModifier="Internal">
    <Type Name="RequestEntity" AccessModifier="Internal">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataRequestTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportedFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ImportedStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ImportedEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ImportDuration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TemplateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserIDs" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DistrictIDs" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasBeenMoved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RequestEntity_RequestEmailNotificationEntity" Member="RequestEmailNotificationEntities" ThisKey="RequestID" OtherKey="RequestID" Type="RequestEmailNotificationEntity" />
      <Association Name="RequestEntity_RequestStudentResponse" Member="RequestStudentResponses" ThisKey="RequestID" OtherKey="RequestID" Type="RequestStudentResponse" />
      <Association Name="RequestEntity_RequestQuestion" Member="RequestQuestions" ThisKey="RequestID" OtherKey="RequestID" Type="RequestQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolManagementView" Member="SchoolManagementViews" AccessModifier="Internal">
    <Type Name="SchoolManagementView" AccessModifier="Internal">
      <Column Name="UserSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestParameter" Member="RequestParameterEntities" AccessModifier="Internal">
    <Type Name="RequestParameterEntity" AccessModifier="Internal">
      <Column Name="RequestParameterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClusterDistrict" Member="ClusterDistrictEntities" AccessModifier="Internal">
    <Type Name="ClusterDistrictEntity" AccessModifier="Internal">
      <Column Name="ListClusterName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ColumnLookupData" Member="ColumnLookupDataEntities" AccessModifier="Internal">
    <Type Name="ColumnLookupDataEntity" AccessModifier="Internal">
      <Column Name="LookupDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColumnID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="StandardColumnEntity_ColumnLookupDataEntity" Member="StandardColumnEntity" ThisKey="ColumnID" OtherKey="ColumnID" Type="StandardColumnEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DelegateTeacher" Member="DelegateTeacherEntities" AccessModifier="Internal">
    <Type Name="DelegateTeacherEntity" AccessModifier="Internal">
      <Column Name="DelegateTeacherID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OriginalTeacherID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewTeacherID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeEnd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MappingInformation" Member="MappingInformationEntities" AccessModifier="Internal">
    <Type Name="MappingInformationEntity" AccessModifier="Internal">
      <Column Name="MapID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LoaderType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgressStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceFileContent" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="XMLTransform" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastestModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PrintingGroup" Member="PrintingGroupEntities" AccessModifier="Internal">
    <Type Name="PrintingGroupEntity" AccessModifier="Internal">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PrintingGroupEntity_PrintingGroupJobEntity" Member="PrintingGroupJobEntities" ThisKey="GroupID" OtherKey="GroupID" Type="PrintingGroupJobEntity" />
      <Association Name="PrintingGroupEntity_ClassPrintingGroupEntity" Member="ClassPrintingGroupEntities" ThisKey="GroupID" OtherKey="GroupID" Type="ClassPrintingGroupEntity" />
    </Type>
  </Table>
  <Table Name="dbo.PrintingGroupJob" Member="PrintingGroupJobEntities" AccessModifier="Internal">
    <Type Name="PrintingGroupJobEntity" AccessModifier="Internal">
      <Column Name="PrintingGroupJobID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PrintingGroupEntity_PrintingGroupJobEntity" Member="PrintingGroupEntity" ThisKey="GroupID" OtherKey="GroupID" Type="PrintingGroupEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestParameterDistrict" Member="RequestParameterDistrictViews" AccessModifier="Internal">
    <Type Name="RequestParameterDistrictView" AccessModifier="Internal">
      <Column Name="RequestParameterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StandardColumn" Member="StandardColumnEntities" AccessModifier="Internal">
    <Type Name="StandardColumnEntity" AccessModifier="Internal">
      <Column Name="ColumnID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="LoaderType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ColumnType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDefaultForCommonPhase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDefaultForTestPhase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRequiredForCommonPhase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRequiredForTestPhase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="StandardColumnEntity_ColumnLookupDataEntity" Member="ColumnLookupDataEntities" ThisKey="ColumnID" OtherKey="ColumnID" Type="ColumnLookupDataEntity" />
    </Type>
  </Table>
  <Table Name="dbo.RequestEmailNotification" Member="RequestEmailNotificationEntities" AccessModifier="Internal">
    <Type Name="RequestEmailNotificationEntity" AccessModifier="Internal">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmailContent" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileAttachContent" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="RequestEntity_RequestEmailNotificationEntity" Member="RequestEntity" ThisKey="RequestID" OtherKey="RequestID" Type="RequestEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestStudentsWithRosterView" Member="TestStudentsWithRosterViews" AccessModifier="Internal">
    <Type Name="TestStudentsWithRosterView" AccessModifier="Internal">
      <Column Name="BubblesheetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ticket" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RosterPosition" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StudentGroup" Member="StudentGroupViews" AccessModifier="Internal">
    <Type Name="StudentGroupView" AccessModifier="Internal">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RequestNotificationEmailView" Member="RequestNotificationEmailViews" AccessModifier="Internal">
    <Type Name="RequestNotificationEmailView" AccessModifier="Internal">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataRequestTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportedFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasBeenMoved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasEmailContent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RosterType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report" Member="ReportEntities" AccessModifier="Internal">
    <Type Name="ReportEntity" AccessModifier="Internal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PrintingGroupData" Member="PrintingGroupDataViews" AccessModifier="Internal">
    <Type Name="PrintingGroupDataView" AccessModifier="Internal">
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClassPrintingGroup" Member="ClassPrintingGroupEntities" AccessModifier="Internal">
    <Type Name="ClassPrintingGroupEntity" AccessModifier="Internal">
      <Column Name="ClassGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PrintingGroupEntity_ClassPrintingGroupEntity" Member="PrintingGroupEntity" ThisKey="GroupID" OtherKey="GroupID" Type="PrintingGroupEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictRosterUpload" Member="DistrictRosterUploadViews" AccessModifier="Internal">
    <Type Name="DistrictRosterUploadView" AccessModifier="Internal">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastProcessed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ScheduledTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Run" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UploadTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestStudentResponse" Member="RequestStudentResponses" AccessModifier="Internal">
    <Type Name="RequestStudentResponse" AccessModifier="Internal">
      <Column Name="RequestStudentResponseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentLocalCode" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SessionData" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StudentResponseSummary" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StudentResponses" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentExist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RequestEntity_RequestStudentResponse" Member="RequestEntity" ThisKey="RequestID" OtherKey="RequestID" Type="RequestEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestQuestion" Member="RequestQuestions" AccessModifier="Internal">
    <Type Name="RequestQuestion" AccessModifier="Internal">
      <Column Name="RequestQuestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerOptions" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CorrectAnswer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RequestEntity_RequestQuestion" Member="RequestEntity" ThisKey="RequestID" OtherKey="RequestID" Type="RequestEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassSchoolTeacherStudentView" Member="ClassSchoolTeacherStudentViews">
    <Type Name="ClassSchoolTeacherStudentView">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeacherLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="RoleEntities" AccessModifier="Internal">
    <Type Name="RoleEntity" AccessModifier="Internal">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Display" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIIconAccessView" Member="XLIIconAccessViews" AccessModifier="Internal">
    <Type Name="XLIIconAccessView" AccessModifier="Internal">
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Restrict]" Member="Restrict" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllModules" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Expires" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XLIAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolDistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictSchoolRestrict" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaSchoolStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AreaSchoolEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AreaSchoolExpires" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllRoles" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIModuleAccessView" Member="XLIModuleAccessViews">
    <Type Name="XLIModuleAccessView">
      <Column Name="AreaCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModuleCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModuleAllRoles" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ModuleRestrict" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="XLIModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DMRoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMRoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DSMDistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DSMRestrict" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SMAllRoles" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SMEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SMExpires" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DMAllRole" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DMStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DMEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DMExprires" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DMDistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIModule" Member="XLIModuleEntities" AccessModifier="Internal">
    <Type Name="XLIModuleEntity" AccessModifier="Internal">
      <Column Name="XLIModuleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="XLIAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModuleOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="AllRoles" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="[Restrict]" Member="Restrict" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="DisplayTooltip" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="HelpText" Type="System.String" CanBeNull="false" />
      <Association Name="XLIAreaEntity_XLIModuleEntity" Member="XLIAreaEntity" ThisKey="XLIAreaID" OtherKey="XLIAreaID" Type="XLIAreaEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualQuestionSub" Member="VirtualQuestionSubEntities">
    <Type Name="VirtualQuestionSubEntity">
      <Column Name="VirtualQuestionSubID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTIItemSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualQuestionAnswerScore" Member="VirtualQuestionAnswerScoreEntities">
    <Type Name="VirtualQuestionAnswerScoreEntity">
      <Column Name="VirtualQuestionAnswerScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTIItemAnswerScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TestAssignment" Member="TestAssignmentEntities">
    <Type Name="TestAssignmentEntity">
      <Column Name="TestAssignmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ClosingDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TestTaken" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AssignedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassUserView" Member="ClassUserViews" AccessModifier="Internal">
    <Type Name="ClassUserView" AccessModifier="Internal">
      <Column Name="ClassUserLOEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserIDClassUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoggedOffUser" Member="LoggedOffUserEntities" AccessModifier="Internal">
    <Type Name="LoggedOffUserEntity" AccessModifier="Internal">
      <Column Name="LoggedOffUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RedirectURL" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserLogon" Member="UserLogonEntities" AccessModifier="Internal">
    <Type Name="UserLogonEntity" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GUIDSession" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RosterType" Member="RosterTypeEntities" AccessModifier="Internal">
    <Type Name="RosterTypeEntity" AccessModifier="Internal">
      <Column Name="RosterTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RosterTypeName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="RosterTypeEntity_DistrictRosterOptionEntity" Member="DistrictRosterOptionEntities" ThisKey="RosterTypeID" OtherKey="RosterTypeID" Type="DistrictRosterOptionEntity" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictRosterOption" Member="DistrictRosterOptionEntities" AccessModifier="Internal">
    <Type Name="DistrictRosterOptionEntity" AccessModifier="Internal">
      <Column Name="DistrictRosterOptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RosterTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="RosterTypeEntity_DistrictRosterOptionEntity" Member="RosterTypeEntity" ThisKey="RosterTypeID" OtherKey="RosterTypeID" Type="RosterTypeEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDistrictSectorView" Member="UserDistrictSectorViews">
    <Type Name="UserDistrictSectorView">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Sector" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TTLConfigs" Member="TTLConfigEntities" AccessModifier="Internal">
    <Type Name="TTLConfigEntity" AccessModifier="Internal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DynamoTableName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RetentionInDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AchievementLevelSetting" Member="AchievementLevelSettingEntities" AccessModifier="Internal">
    <Type Name="AchievementLevelSettingEntity" AccessModifier="Internal">
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ValueString" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="LabelString" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GradedValueString" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SubValueString" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SubLabelString" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SubGradedValueString" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="AchievementLevelSettingEntity_VirtualTestDBEntity" Member="VirtualTestDBEntities" Storage="_VirtualTests" ThisKey="AchievementLevelSettingID" OtherKey="AchievementLevelSettingID" Type="VirtualTestDBEntity" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTest" Member="VirtualTestDBEntities" AccessModifier="Internal">
    <Type Name="VirtualTestDBEntity" AccessModifier="Internal">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AuthorUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EditedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Instruction" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PreQTIVirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreProdVTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestScoreMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestSubTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsTeacherLed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsePointsEarnedConversion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasUseRationale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsNumberQuestions" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMultipleTestResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NavigationMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetOriginID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginalTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AchievementLevelSettingEntity_VirtualTestDBEntity" Member="AchievementLevelSettingEntity" ThisKey="AchievementLevelSettingID" OtherKey="AchievementLevelSettingID" Type="AchievementLevelSettingEntity" IsForeignKey="true" />
      <Association Name="DataSetCategoryEntity_VirtualTestDBEntity" Member="DataSetCategoryEntity" ThisKey="DataSetCategoryID" OtherKey="DataSetCategoryID" Type="DataSetCategoryEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LTIRequestHistory" Member="LTIRequestHistoryEntities">
    <Type Name="LTIRequestHistoryEntity">
      <Column Name="LTIRequestHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlatformID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DeploymentID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nonce" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LTIInformation" Member="LTIInformationEntities">
    <Type Name="LTIInformationEntity">
      <Column Name="LTIInformationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlatformID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DeploymentID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorizationServerID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AuthenticationRequestURL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AccessTokenURL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PublicKey" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictDataParm" Member="DistrictDataParmEntities" AccessModifier="Internal">
    <Type Name="DistrictDataParmEntity" AccessModifier="Internal">
      <Column Name="DistrictDataParmID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetOriginID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JSONDataConfig" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImportType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Interoperability" Member="Interoperabilities">
    <Type Name="Interoperability">
      <Column Name="InteroperabilityId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LinkitObjectTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThirdPartySourceTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceId" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="LinkitObjectType_Interoperability" Member="LinkitObjectType" ThisKey="LinkitObjectTypeId" OtherKey="LinkitObjectTypeId" Type="LinkitObjectType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LinkitObjectType" Member="LinkitObjectTypes">
    <Type Name="LinkitObjectType">
      <Column Name="LinkitObjectTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="LinkitObjectType_Interoperability" Member="Interoperabilities" ThisKey="LinkitObjectTypeId" OtherKey="LinkitObjectTypeId" Type="Interoperability" />
    </Type>
  </Table>
  <Table Name="dbo.SSORedirectUrl" Member="SSORedirectUrlEntities">
    <Type Name="SSORedirectUrlEntity">
      <Column Name="SSORedirectUrlId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SSOInformationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RedirectUrl" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="XLIModuleCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataSetCategoryDistrictDisplayName" Member="DataSetCategoryDistrictDisplayNames" AccessModifier="Internal">
    <Type Name="DataSetCategoryDistrictDisplayName" AccessModifier="Internal">
      <Column Name="DataSetCategoryId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DistrictId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryDisplayName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="DataSetCategoryEntity_DataSetCategoryDistrictDisplayName" Member="DataSetCategoryEntity" ThisKey="DataSetCategoryId" OtherKey="DataSetCategoryID" Type="DataSetCategoryEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataSetCategory" Member="DataSetCategoryEntities" AccessModifier="Internal">
    <Type Name="DataSetCategoryEntity" AccessModifier="Internal">
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataSetCategoryName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DataSetCategoryEntity_VirtualTestDBEntity" Member="VirtualTestDBEntities" ThisKey="DataSetCategoryID" OtherKey="DataSetCategoryID" Type="VirtualTestDBEntity" />
      <Association Name="DataSetCategoryEntity_DataSetCategoryDistrictDisplayName" Member="DataSetCategoryDistrictDisplayNames" ThisKey="DataSetCategoryID" OtherKey="DataSetCategoryId" Type="DataSetCategoryDistrictDisplayName" />
    </Type>
  </Table>
  <Table Name="dbo.ClassMeta" Member="ClassMetaEntities" AccessModifier="Internal">
    <Type Name="ClassMetaEntity" AccessModifier="Internal">
      <Column Name="ClassMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIArea" Member="XLIAreaEntities" AccessModifier="Internal">
    <Type Name="XLIAreaEntity" AccessModifier="Internal">
      <Column Name="XLIAreaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Restrict]" Member="Restrict" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayTooltip" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="AreaOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="XLIAreaEntity_XLIModuleEntity" Member="XLIModuleEntities" ThisKey="XLIAreaID" OtherKey="XLIAreaID" Type="XLIModuleEntity" />
    </Type>
  </Table>
  <Table Name="dbo.AggregateSubjectMapping" Member="AggregateSubjectMappingEntities" AccessModifier="Internal">
    <Type Name="AggregateSubjectMappingEntity" AccessModifier="Internal">
      <Column Name="AggregateSubjectMappingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AggregateSubjectName" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.xpsDistrictUpload" Member="xpsDistrictUploadEntities">
    <Type Name="xpsDistrictUploadEntity">
      <Column Name="xpsDistrictUploadID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastProcessed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DirectoryPath" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ScheduledTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Run" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UploadTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassNameType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GetExternalFiles" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExternalSourceInfo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.xpsQueue" Member="xpsQueueEntities">
    <Type Name="xpsQueueEntity">
      <Column Name="xpsQueueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="xpsDistrictUploadID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="xpsUpLoadTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xpsQueueStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xpsQueueResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchedStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsValidation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteClass" Method="DeleteClass" AccessModifier="Internal">
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RITCreateVirtualTestQuestion" Method="RITCreateVirtualTestQuestion">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ApproveStudentResponse" Parameter="approveStudentResponse" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="RITCreateVirtualTestQuestionResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RITCreateRequest" Method="RITCreateRequest">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ImportedFileName" Parameter="importedFileName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="RequestParameter" Parameter="requestParameter" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="RITCreateRequestResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RITCreateRequestTestResponse" Method="RITCreateRequestTestResponse">
    <Parameter Name="requestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="testData" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="RITCreateRequestTestResponseResult">
      <Column Name="RequestStudentResponseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentLocalCode" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="StudentExist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StudentResponses" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SessionData" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StudentResponseSummary" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RITGradeTestResponse" Method="RITGradeTestResponse">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ApproveStudentResponse" Parameter="approveStudentResponse" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="RITGradeTestResponseResult">
      <Column Name="StatisticID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DomainID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogData" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ParentStatisticID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DomainValue" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetListGroupIDsByUserId" Method="GetListGroupIDsByUserId">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetListGroupIDsByUserIdResult">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.XLIModuleAccessProc" Method="XLIModuleAccessProc">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListXliAreaID" Parameter="listXliAreaID" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="XLIModuleAccessProcResult">
      <Column Name="XLIModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XLIModuleName" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="XLIAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XLIAreaName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.XLIIconAccessProc" Method="XLIIconAccessProc">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="XLIIconAccessProcResult">
      <Column Name="XLIAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckUserCanAccessClassOrSchool" Method="CheckUserCanAccessClassOrSchool">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ItemID" Parameter="itemID" Type="System.Int32" DbType="Int" />
    <Parameter Name="itemType" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="CheckUserCanAccessClassOrSchoolResult">
      <Column Name="CanAccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckUserCanAccessStudent" Method="CheckUserCanAccessStudent">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentIDList" Parameter="studentIDList" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="CheckUserCanAccessStudentResult">
      <Column Name="CanAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckUserCanAccessTeacher" Method="CheckUserCanAccessTeacher">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherId" Parameter="teacherId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CheckUserCanAccessTeacherResult">
      <Column Name="CanAccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckUserCanAccessTestResult" Method="CheckUserCanAccessTestResult">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="testResultIdList" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="CheckUserCanAccessTestResultResult">
      <Column Name="CanAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckUserCanPurgeTest" Method="CheckUserCanPurgeTest">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <ElementType Name="CheckUserCanPurgeTestResult">
      <Column Name="CanPurge" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.XLICheckDistrictRoleAccessModule" Method="XLICheckDistrictRoleAccessModule">
    <Parameter Name="Moduleid" Parameter="moduleid" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetRequestsByUserID" Method="GetRequestsByUserID">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRequestsByUserIDResult">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataRequestTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportedFileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasBeenMoved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasEmailContent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RosterType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetClassBySchoolAndDistrictTerm" Method="GetClassBySchoolAndDistrictTerm">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictTermID" Parameter="districtTermID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetClassBySchoolAndDistrictTermResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassNameCustom" Type="System.String" DbType="VarChar(303) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTimeZoneByStateWithSchoolID" Method="GetTimeZoneByStateWithSchoolID">
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTimeZoneByStateWithSchoolIDResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CountActiveStudentInGroup" Method="CountActiveStudentInGroup">
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CountActiveStudentInGroupResult">
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCategoryByUser" Method="GetCategoryByUser">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StateID" Parameter="stateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CategoryID" Parameter="categoryID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCategoryByUserResult">
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetCategoryName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNotificationByDistrictId" Method="GetNotificationByDistrictId">
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetNotificationByDistrictIdResult">
      <Column Name="NotificationMessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublishedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HtmlContent" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AccessedDistrict" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ReceivingUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotificationType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreateSurveySchoolClass" Method="CreateSurveySchoolClass">
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictTermId" Parameter="districtTermId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SurveyName" Parameter="surveyName" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="CreateSurveySchoolClassResult">
      <Column Name="SchoolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetClassBySchool" Method="GetClassBySchool">
    <Parameter Name="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetClassBySchoolResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSchoolAccessByModuleID" Method="GetSchoolAccessByModuleID">
    <Parameter Name="XLIModuleID" Parameter="xLIModuleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSchoolAccessByModuleIDResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RoleAccess" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetModuleAccessByGroupID" Method="GetModuleAccessByGroupID">
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="XLIModuleIDs" Parameter="xLIModuleIDs" Type="System.String" DbType="VarChar(2000)" />
    <ElementType Name="GetModuleAccessByGroupIDResult">
      <Column Name="RowNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetModuleAccessSumary" Method="GetModuleAccessSumary">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="XLIModuleIDs" Parameter="xLIModuleIDs" Type="System.String" DbType="VarChar(2000)" />
    <ElementType Name="GetModuleAccessSumaryResult">
      <Column Name="RowNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupWithAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupWithoutAccess" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetClassBySchoolAndDistrictTermV2" Method="GetClassBySchoolAndDistrictTermV2">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolIDList" Parameter="schoolIDList" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictTermID" Parameter="districtTermID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetClassBySchoolAndDistrictTermV2Result">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassNameCustom" Type="System.String" DbType="VarChar(303) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSchoolsByDistrictV2" Method="GetSchoolsByDistrictV2">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="TotalRecords" Parameter="totalRecords" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GetSchoolsByDistrictV2Result">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>