<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingStage" Class="ExtractTestDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.245.86.67;Initial Catalog=AdminReportingStage;Persist Security Info=True;User ID=Vina" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingStageConnectionString10" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ExtractTestResultsView" Member="ExtractTestResultsViews" AccessModifier="Internal">
    <Type Name="ExtractTestResultsView" AccessModifier="Internal">
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestNameCustom" Type="System.String" DbType="VarChar(259)" CanBeNull="true" />
      <Column Name="ClassNameCustom" Type="System.String" DbType="VarChar(303) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCustom" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherCustom" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="StudentDistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestTimingOptionView" Member="VirtualTestTimingOptionViews" AccessModifier="Internal">
    <Type Name="VirtualTestTimingOptionView" AccessModifier="Internal">
      <Column Name="TimingSettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimingSettingName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestTimingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.S3Permission" Member="S3PermissionEntities" AccessModifier="Internal">
    <Type Name="S3PermissionEntity" AccessModifier="Internal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="S3PortalLinkID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.S3PortalLink" Member="S3PortalLinkEntities" AccessModifier="Internal">
    <Type Name="S3PortalLinkEntity" AccessModifier="Internal">
      <Column Name="S3PortalLinkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BucketName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalKey" Type="System.String" DbType="VarChar(22)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestExtractTemplate" Member="TestExtractTemplateEntities" AccessModifier="Internal">
    <Type Name="TestExtractTemplateEntity" AccessModifier="Internal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ExtractTestResultParam" Member="ExtractTestResultParamEntities">
    <Type Name="ExtractTestResultParamEntity">
      <Column Name="ExtractTestResultParamID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListTestIDs" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ListIdsUncheck" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserRoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GeneralSearch" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExtractLocalTestResultsQueue" Member="ExtractLocalTestResultsQueueEntities">
    <Type Name="ExtractLocalTestResultsQueueEntity">
      <Column Name="ExtractLocalTestResultsQueueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserTimeZoneOffset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExportTemplates" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ListIDsInput" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ListSchoolIDs" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ListClassIDs" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ExtractType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProcessingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessingTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndProcessingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BaseHostURL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UrlDownload" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ExtractTestResultParamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ExportAssessmentItemResponse_New" Method="ExportAssessmentItemResponse_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportAssessmentItemResponse_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CorrectAnswer" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="QtiSchemaId" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ResponseLongType" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Export_ASMNT_ITEMR_ACADEMIC_STDS_New" Method="Export_ASMNT_ITEMR_ACADEMIC_STDS_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Export_ASMNT_ITEMR_ACADEMIC_STDS_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Document" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YearResultDate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Export_ASSESSMENT_RESPONSE_New" Method="Export_ASSESSMENT_RESPONSE_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Export_ASSESSMENT_RESPONSE_NewResult">
      <Column Name="Code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportAssessmentItem_New" Method="ExportAssessmentItem_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportAssessmentItem_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SubtestHighestGradeLevel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubtestLowestGradeLevel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportAssessmentAchievedDetail_New" Method="ExportAssessmentAchievedDetail_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportAssessmentAchievedDetail_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AchieveLevelName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportUserInformation" Method="ExportUserInformation">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportUserInformationResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportTest" Method="ExportTest">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportTestResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportQuestionTemplate" Method="ExportQuestionTemplate">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportQuestionTemplateResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Standard" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Skill" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Other" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportTestResultTemplate" Method="ExportTestResultTemplate">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportTestResultTemplateResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StatusName" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="TimeSettingValue" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportPointsEarned" Method="ExportPointsEarned">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportPointsEarnedResult">
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Term" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WasAnswered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportStudentResponse" Method="ExportStudentResponse">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Guid" Parameter="guid" Type="System.String" DbType="VarChar(36)" />
    <ElementType Name="ExportStudentResponseResult">
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Term" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="AnswerLetterString" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportClassTestAssignmentsTemplate" Method="ExportClassTestAssignmentsTemplate">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportClassTestAssignmentsTemplateResult">
      <Column Name="Assigned" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VirtualtestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Test" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Started" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Completed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WaitingForReview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotStarted" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportRosterTemplate" Method="ExportRosterTemplate">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ExportRosterTemplateResult">
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Term" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ClassCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StudentModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Race" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentEmail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ParentPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Program" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Export_ASMNT_SUBTEST_ACADEMIC_STDS_New" Method="Export_ASMNT_SUBTEST_ACADEMIC_STDS_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Export_ASMNT_SUBTEST_ACADEMIC_STDS_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Export_ASSESSMENT_ACC_MOD_FACT_New" Method="Export_ASSESSMENT_ACC_MOD_FACT_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Export_ASSESSMENT_ACC_MOD_FACT_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Export_ASSESSMENT_FACT_New" Method="Export_ASSESSMENT_FACT_New">
    <Parameter Name="ListTestResultIds" Parameter="listTestResultIds" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Export_ASSESSMENT_FACT_NewResult">
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPointsEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetGradeHaveTest" Method="extrGetGradeHaveTest">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetGradeHaveTestResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSubjectHaveTest" Method="extrGetSubjectHaveTest">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSubjectHaveTestResult">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetBankHaveTest" Method="extrGetBankHaveTest">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectId" Parameter="subjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="extrGetBankHaveTestResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetVirtualTest" Method="extrGetVirtualTest">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetVirtualTestResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSchoolsHaveTestResult" Method="extrGetSchoolsHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSchoolsHaveTestResultResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSchoolsHaveUser" Method="extrGetSchoolsHaveUser">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSchoolsHaveUserResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetTeachersHaveTestResult" Method="extrGetTeachersHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetTeachersHaveTestResultResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetClassesHaveTestResult" Method="extrGetClassesHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetClassesHaveTestResultResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetStudentsHaveTestResult" Method="extrGetStudentsHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetStudentsHaveTestResultResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetAllTestResultIdByFilter" Method="extrGetAllTestResultIdByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetAllTestResultIdByFilterResult">
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetVirtualTestByFilter" Method="extrGetVirtualTestByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="extrGetVirtualTestByFilterResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetGradeHaveTestResult" Method="extrGetGradeHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetGradeHaveTestResultResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetBankHaveTestAssignment" Method="extrGetBankHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectId" Parameter="subjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="extrGetBankHaveTestAssignmentResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetClassesHaveTestAssignment" Method="extrGetClassesHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetClassesHaveTestAssignmentResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetGradeHaveTestAssignment" Method="extrGetGradeHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetGradeHaveTestAssignmentResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSchoolsHaveTestAssignment" Method="extrGetSchoolsHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSchoolsHaveTestAssignmentResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSubjectHaveTestAssignment" Method="extrGetSubjectHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSubjectHaveTestAssignmentResult">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetTeachersHaveTestAssignment" Method="extrGetTeachersHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BankId" Parameter="bankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetTeachersHaveTestAssignmentResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSubjectHaveTestResult" Method="extrGetSubjectHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSubjectHaveTestResultResult">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetBankHaveTestResult" Method="extrGetBankHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetBankHaveTestResultResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetVirtualTestHaveTestAssignment" Method="extrGetVirtualTestHaveTestAssignment">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetVirtualTestHaveTestAssignmentResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetVirtualTestHaveTestResult" Method="extrGetVirtualTestHaveTestResult">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetVirtualTestHaveTestResultResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetTestAssignmentByFilter" Method="extrGetTestAssignmentByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetTestAssignmentByFilterResult">
      <Column Name="QTITestClassAssignmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignmentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherCustom" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="TestNameCustom" Type="System.String" DbType="VarChar(259)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetTermHaveStudent" Method="extrGetTermHaveStudent">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetTermHaveStudentResult">
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetUserByFilter" Method="extrGetUserByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ListSchoolIds" Parameter="listSchoolIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetUserByFilterResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetRosterByFilter" Method="extrGetRosterByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherId" Parameter="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListClassIds" Parameter="listClassIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetRosterByFilterResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCustom" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTerm" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
	  <Column Name="ClassStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetSchoolHaveStudent" Method="extrGetSchoolHaveStudent">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetSchoolHaveStudentResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetClassHaveStudent" Method="extrGetClassHaveStudent">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetClassHaveStudentResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetTeacherHaveStudent" Method="extrGetTeacherHaveStudent">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetTeacherHaveStudentResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrGetClassIDsByFilter" Method="extrGetClassIDsByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherId" Parameter="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListClassIds" Parameter="listClassIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="extrGetClassIDsByFilterResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.extrAddExtrTestResultToQueue" Method="extrAddExtrTestResultToQueue">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserTimeZoneOffset" Parameter="userTimeZoneOffset" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExtractType" Parameter="extractType" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedDate" Parameter="createdDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="BaseHostURL" Parameter="baseHostURL" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ExportTemplate" Parameter="exportTemplate" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ListTestResultIDUncheck" Parameter="listTestResultIDUncheck" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.extrGetTestResultByFilter" Method="extrGetTestResultByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BankID" Parameter="bankID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ListTestIds" Parameter="listTestIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="GradeId" Parameter="gradeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="IsHideStudentName" Parameter="isHideStudentName" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="extrGetTestResultByFilterResult">
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCustom" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ClassNameCustom" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherCustom" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TestNameCustom" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>
