#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Data.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IsolatingTestTaker")]
	internal partial class IsolatingTestTakerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion	
			
		public IsolatingTestTakerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IsolatingTestTakerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IsolatingTestTakerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IsolatingTestTakerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOnlineTestSessionStatusIsolating")]
		public ISingleResult<GetOnlineTestSessionStatusIsolatingResult> GetOnlineTestSessionStatusIsolating([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QTITestClassAssignmentIDs", DbType="NVarChar(MAX)")] string qTITestClassAssignmentIDs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qTITestClassAssignmentIDs);
			return ((ISingleResult<GetOnlineTestSessionStatusIsolatingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PausedOnlineTest")]
		public int PausedOnlineTest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnlineTestSessionIDs", DbType="NVarChar(MAX)")] string onlineTestSessionIDs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), onlineTestSessionIDs);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubmitOnlineTest")]
		public int SubmitOnlineTest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnlineTestSessionIDs", DbType="NVarChar(MAX)")] string onlineTestSessionIDs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), onlineTestSessionIDs);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTestSessionAnswers")]
		public ISingleResult<GetTestSessionAnswersResult> GetTestSessionAnswers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QTIOnlineTestSessionID", DbType="Int")] System.Nullable<int> qTIOnlineTestSessionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qTIOnlineTestSessionID);
			return ((ISingleResult<GetTestSessionAnswersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOnlineTestSessionAnswer")]
		public ISingleResult<GetOnlineTestSessionAnswerResult> GetOnlineTestSessionAnswer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QTIOnlineTestSessionIDs", DbType="NVarChar(MAX)")] string qTIOnlineTestSessionIDs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qTIOnlineTestSessionIDs);
			return ((ISingleResult<GetOnlineTestSessionAnswerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsolatingUpdateAnswerText")]
		public int IsolatingUpdateAnswerText([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnswerID", DbType="Int")] System.Nullable<int> answerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnswerSubID", DbType="Int")] System.Nullable<int> answerSubID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Saved", DbType="Bit")] System.Nullable<bool> saved)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), answerID, answerSubID, saved);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsolatingGetQTIOnlineTestSessionStatus")]
		public ISingleResult<IsolatingGetQTIOnlineTestSessionStatusResult> IsolatingGetQTIOnlineTestSessionStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QtiOnlineTestSessionID", DbType="Int")] System.Nullable<int> qtiOnlineTestSessionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qtiOnlineTestSessionID);
			return ((ISingleResult<IsolatingGetQTIOnlineTestSessionStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsolatingReopenFailedTestSession")]
		public int IsolatingReopenFailedTestSession([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QTIOnlineTestSessionID", DbType="Int")] System.Nullable<int> qTIOnlineTestSessionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), qTIOnlineTestSessionID);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetOnlineTestSessionStatusIsolatingResult
	{
		
		private int _QTITestClassAssignmentId;
		
		private int _QTIOnlineTestSessionId;
		
		private int _StatusId;
		
		private System.Nullable<System.DateTime> _LastLoginDate;
		
		private System.Nullable<System.DateTime> _Timestamp;
		
		public GetOnlineTestSessionStatusIsolatingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTITestClassAssignmentId", DbType="Int NOT NULL")]
		public int QTITestClassAssignmentId
		{
			get
			{
				return this._QTITestClassAssignmentId;
			}
			set
			{
				if ((this._QTITestClassAssignmentId != value))
				{
					this._QTITestClassAssignmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTIOnlineTestSessionId", DbType="Int NOT NULL")]
		public int QTIOnlineTestSessionId
		{
			get
			{
				return this._QTIOnlineTestSessionId;
			}
			set
			{
				if ((this._QTIOnlineTestSessionId != value))
				{
					this._QTIOnlineTestSessionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusId", DbType="Int NOT NULL")]
		public int StatusId
		{
			get
			{
				return this._StatusId;
			}
			set
			{
				if ((this._StatusId != value))
				{
					this._StatusId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this._LastLoginDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this._Timestamp = value;
				}
			}
		}
	}
	
	public partial class GetTestSessionAnswersResult
	{
		
		private int _QTIOnlineTestSessionAnswerID;
		
		private string _AnswerChoice;
		
		private bool _Answered;
		
		private string _AnswerText;
		
		private System.Nullable<int> _PointsEarned;
		
		private System.DateTime _Timestamp;
		
		private string _HighlightPassage;
		
		private string _HighlightQuestion;
		
		private string _AnswerTemp;
		
		private bool _Flag;
		
		private string _AnswerImage;
		
		private string _CrossedAnswer;
		
		private bool _Status;
		
		private System.Nullable<int> _AnswerOrder;
		
		private string _AnswerSubs;
		
		public GetTestSessionAnswersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTIOnlineTestSessionAnswerID", DbType="Int NOT NULL")]
		public int QTIOnlineTestSessionAnswerID
		{
			get
			{
				return this._QTIOnlineTestSessionAnswerID;
			}
			set
			{
				if ((this._QTIOnlineTestSessionAnswerID != value))
				{
					this._QTIOnlineTestSessionAnswerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerChoice", DbType="VarChar(200)")]
		public string AnswerChoice
		{
			get
			{
				return this._AnswerChoice;
			}
			set
			{
				if ((this._AnswerChoice != value))
				{
					this._AnswerChoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answered", DbType="Bit NOT NULL")]
		public bool Answered
		{
			get
			{
				return this._Answered;
			}
			set
			{
				if ((this._Answered != value))
				{
					this._Answered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerText", DbType="NVarChar(MAX)")]
		public string AnswerText
		{
			get
			{
				return this._AnswerText;
			}
			set
			{
				if ((this._AnswerText != value))
				{
					this._AnswerText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsEarned", DbType="Int")]
		public System.Nullable<int> PointsEarned
		{
			get
			{
				return this._PointsEarned;
			}
			set
			{
				if ((this._PointsEarned != value))
				{
					this._PointsEarned = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this._Timestamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighlightPassage", DbType="NVarChar(MAX)")]
		public string HighlightPassage
		{
			get
			{
				return this._HighlightPassage;
			}
			set
			{
				if ((this._HighlightPassage != value))
				{
					this._HighlightPassage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighlightQuestion", DbType="NVarChar(MAX)")]
		public string HighlightQuestion
		{
			get
			{
				return this._HighlightQuestion;
			}
			set
			{
				if ((this._HighlightQuestion != value))
				{
					this._HighlightQuestion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerTemp", DbType="NVarChar(MAX)")]
		public string AnswerTemp
		{
			get
			{
				return this._AnswerTemp;
			}
			set
			{
				if ((this._AnswerTemp != value))
				{
					this._AnswerTemp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Bit NOT NULL")]
		public bool Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this._Flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerImage", DbType="NVarChar(MAX)")]
		public string AnswerImage
		{
			get
			{
				return this._AnswerImage;
			}
			set
			{
				if ((this._AnswerImage != value))
				{
					this._AnswerImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrossedAnswer", DbType="VarChar(100)")]
		public string CrossedAnswer
		{
			get
			{
				return this._CrossedAnswer;
			}
			set
			{
				if ((this._CrossedAnswer != value))
				{
					this._CrossedAnswer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerOrder", DbType="Int")]
		public System.Nullable<int> AnswerOrder
		{
			get
			{
				return this._AnswerOrder;
			}
			set
			{
				if ((this._AnswerOrder != value))
				{
					this._AnswerOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerSubs", DbType="NVarChar(MAX)")]
		public string AnswerSubs
		{
			get
			{
				return this._AnswerSubs;
			}
			set
			{
				if ((this._AnswerSubs != value))
				{
					this._AnswerSubs = value;
				}
			}
		}
	}
	
	public partial class GetOnlineTestSessionAnswerResult
	{
		
		private System.Nullable<bool> _Answered;
		
		private System.Nullable<int> _QuestionOrder;
		
		private System.Nullable<int> _AnswerOrder;
		
		private int _VirtualQuestionID;
		
		private System.Nullable<bool> _ManualReview;
		
		private int _QTIOnlineTestSessionID;
		
		private System.DateTime _TimeStamp;
		
		private System.Nullable<System.DateTime> _LastLoginDate;
		
		public GetOnlineTestSessionAnswerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answered", DbType="Bit")]
		public System.Nullable<bool> Answered
		{
			get
			{
				return this._Answered;
			}
			set
			{
				if ((this._Answered != value))
				{
					this._Answered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionOrder", DbType="Int")]
		public System.Nullable<int> QuestionOrder
		{
			get
			{
				return this._QuestionOrder;
			}
			set
			{
				if ((this._QuestionOrder != value))
				{
					this._QuestionOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerOrder", DbType="Int")]
		public System.Nullable<int> AnswerOrder
		{
			get
			{
				return this._AnswerOrder;
			}
			set
			{
				if ((this._AnswerOrder != value))
				{
					this._AnswerOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualQuestionID", DbType="Int NOT NULL")]
		public int VirtualQuestionID
		{
			get
			{
				return this._VirtualQuestionID;
			}
			set
			{
				if ((this._VirtualQuestionID != value))
				{
					this._VirtualQuestionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManualReview", DbType="Bit")]
		public System.Nullable<bool> ManualReview
		{
			get
			{
				return this._ManualReview;
			}
			set
			{
				if ((this._ManualReview != value))
				{
					this._ManualReview = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTIOnlineTestSessionID", DbType="Int NOT NULL")]
		public int QTIOnlineTestSessionID
		{
			get
			{
				return this._QTIOnlineTestSessionID;
			}
			set
			{
				if ((this._QTIOnlineTestSessionID != value))
				{
					this._QTIOnlineTestSessionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this._TimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this._LastLoginDate = value;
				}
			}
		}
	}
	
	public partial class IsolatingGetQTIOnlineTestSessionStatusResult
	{
		
		private int _StatusID;
		
		public IsolatingGetQTIOnlineTestSessionStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int NOT NULL")]
		public int StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
