<?xml version="1.0" encoding="utf-8"?><Database Name="IsolatingTestTaker" Class="IsolatingTestTakerDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.189.210.104;Initial Catalog=IsolatingTestTaker;Persist Security Info=True;User ID=Vina" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="IsolatingTestTakerConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetOnlineTestSessionStatusIsolating" Method="GetOnlineTestSessionStatusIsolating">
    <Parameter Name="QTITestClassAssignmentIDs" Parameter="qTITestClassAssignmentIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="GetOnlineTestSessionStatusIsolatingResult">
      <Column Name="QTITestClassAssignmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PausedOnlineTest" Method="PausedOnlineTest">
    <Parameter Name="OnlineTestSessionIDs" Parameter="onlineTestSessionIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SubmitOnlineTest" Method="SubmitOnlineTest">
    <Parameter Name="OnlineTestSessionIDs" Parameter="onlineTestSessionIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTestSessionAnswers" Method="GetTestSessionAnswers">
    <Parameter Name="QTIOnlineTestSessionID" Parameter="qTIOnlineTestSessionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTestSessionAnswersResult">
      <Column Name="QTIOnlineTestSessionAnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerChoice" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Answered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HighlightPassage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HighlightQuestion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AnswerTemp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CrossedAnswer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerSubs" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetOnlineTestSessionAnswer" Method="GetOnlineTestSessionAnswer">
    <Parameter Name="QTIOnlineTestSessionIDs" Parameter="qTIOnlineTestSessionIDs" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="GetOnlineTestSessionAnswerResult">
      <Column Name="Answered" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManualReview" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.IsolatingUpdateAnswerText" Method="IsolatingUpdateAnswerText">
    <Parameter Name="AnswerID" Parameter="answerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AnswerSubID" Parameter="answerSubID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Saved" Parameter="saved" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IsolatingGetQTIOnlineTestSessionStatus" Method="IsolatingGetQTIOnlineTestSessionStatus">
    <Parameter Name="QtiOnlineTestSessionID" Parameter="qtiOnlineTestSessionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="IsolatingGetQTIOnlineTestSessionStatusResult">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.IsolatingReopenFailedTestSession" Method="IsolatingReopenFailedTestSession">
    <Parameter Name="QTIOnlineTestSessionID" Parameter="qTIOnlineTestSessionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>
