<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="ItemTagDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.245.226.146;Initial Catalog=AdminReportingVNS;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString13" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ItemTagCategory" Member="ItemTagCategoryEntities">
    <Type Name="ItemTagCategoryEntity">
      <Column Name="ItemTagCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="ItemTagCategoryEntity_ItemTagEntity" Member="ItemTagEntities" ThisKey="ItemTagCategoryID" OtherKey="ItemTagCategoryID" Type="ItemTagEntity" />
    </Type>
  </Table>
  <Table Name="dbo.QtiItemItemTag" Member="QtiItemItemTagEntities">
    <Type Name="QtiItemItemTagEntity">
      <Column Name="QtiItemItemTagID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QtiItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemTagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ItemTagEntity_QtiItemItemTagEntity" Member="ItemTagEntity" ThisKey="ItemTagID" OtherKey="ItemTagID" Type="ItemTagEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemTag" Member="ItemTagEntities">
    <Type Name="ItemTagEntity">
      <Column Name="ItemTagID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemTagCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="ItemTagEntity_QtiItemItemTagEntity" Member="QtiItemItemTagEntities" ThisKey="ItemTagID" OtherKey="ItemTagID" Type="QtiItemItemTagEntity" />
      <Association Name="ItemTagCategoryEntity_ItemTagEntity" Member="ItemTagCategoryEntity" ThisKey="ItemTagCategoryID" OtherKey="ItemTagCategoryID" Type="ItemTagCategoryEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QtiItemItemTagView" Member="QtiItemItemTagViews">
    <Type Name="QtiItemItemTagView">
      <Column Name="QtiItemItemTagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QtiItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemTagCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryDescription" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ItemTagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TagDescription" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemTagView" Member="ItemTagViews">
    <Type Name="ItemTagView">
      <Column Name="ItemTagCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryDescription" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ItemTagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TagDescription" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CountQtiItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemTagCategoryView" Member="ItemTagCategoryViews">
    <Type Name="ItemTagCategoryView">
      <Column Name="ItemTagCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountQtiItem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetSuggestTags" Method="GetSuggestTags">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchValue" Parameter="searchValue" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="GetSuggestTagsResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTopicBySearchText" Method="GetTopicBySearchText">
    <Parameter Name="SearchValue" Parameter="searchValue" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="InputIdString" Parameter="inputIdString" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GetTopicBySearchTextResult">
      <Column Name="GroupTag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLessonTwoBySearchText" Method="GetLessonTwoBySearchText">
    <Parameter Name="SearchValue" Parameter="searchValue" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="InputIdString" Parameter="inputIdString" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GetLessonTwoBySearchTextResult">
      <Column Name="GroupTag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLessonOneBySearchText" Method="GetLessonOneBySearchText">
    <Parameter Name="SearchValue" Parameter="searchValue" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="InputIdString" Parameter="inputIdString" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GetLessonOneBySearchTextResult">
      <Column Name="GroupTag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>