<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="LearningLibraryDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.245.226.146;Initial Catalog=AdminReportingVNS;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString15" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LessonContentType" Member="LessonContentTypeEntities">
    <Type Name="LessonContentTypeEntity">
      <Column Name="LessonContentTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DisplayText" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonContentTypeEntity_LessonEntity" Member="LessonEntities" ThisKey="LessonContentTypeID" OtherKey="LessonContentTypeID" Type="LessonEntity" />
    </Type>
  </Table>
  <Table Name="dbo.LessonSubject" Member="LessonSubjectEntities">
    <Type Name="LessonSubjectEntity">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonSubjectEntity_LessonEntity" Member="LessonEntities" ThisKey="SubjectID" OtherKey="SubjectID" Type="LessonEntity" />
    </Type>
  </Table>
  <Table Name="dbo.LessonProviderDistrictView" Member="LessonProviderDistrictViewEntities">
    <Type Name="LessonProviderDistrictViewEntity">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TimeZoneOffsetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllDistrict" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThumbnailPath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Webpage" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SharedFor" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonFileType" Member="LessonFileTypeEntities">
    <Type Name="LessonFileTypeEntity">
      <Column Name="LessonFileTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ThumbnailPath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="LessonFileTypeEntity_LessonEntity" Member="LessonEntities" ThisKey="LessonFileTypeID" OtherKey="LessonFileTypeID" Type="LessonEntity" />
    </Type>
  </Table>
  <Table Name="dbo.LessonGrade" Member="LessonGradeEntities">
    <Type Name="LessonGradeEntity">
      <Column Name="LessonGradeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LessonEntity_LessonGradeEntity" Member="LessonEntity" ThisKey="LessonID" OtherKey="LessonID" Type="LessonEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonStateStandard" Member="LessonStateStandardEntities">
    <Type Name="LessonStateStandardEntity">
      <Column Name="LessonStateStandard" Member="LessonStateStandard1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateStandardID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CorrelationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonEntity_LessonStateStandardEntity" Member="LessonEntity" ThisKey="LessonID" OtherKey="LessonID" Type="LessonEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MasterStandardView" Member="MasterStandardViews">
    <Type Name="MasterStandardView">
      <Column Name="MasterStandardID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="GUID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentGUID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoGrade" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HiGrade" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LowGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HighGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Children" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountChildren" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lesson" Member="LessonEntities" AccessModifier="Internal">
    <Type Name="LessonEntity">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LessonFileTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="LessonPath" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="GuidePath" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="ThumbnailPath" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="LessonContentTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="urlPath" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LessonGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Blocked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LessonProviderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradeString" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="StandardGUIDString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardDescriptionString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardSubjectString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardNumberString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GradeOrderString" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="LessonEntity_LessonGradeEntity" Member="LessonGradeEntities" ThisKey="LessonID" OtherKey="LessonID" Type="LessonGradeEntity" />
      <Association Name="LessonEntity_LessonStateStandardEntity" Member="LessonStateStandardEntities" ThisKey="LessonID" OtherKey="LessonID" Type="LessonStateStandardEntity" />
      <Association Name="LessonContentTypeEntity_LessonEntity" Member="LessonContentTypeEntity" ThisKey="LessonContentTypeID" OtherKey="LessonContentTypeID" Type="LessonContentTypeEntity" IsForeignKey="true" />
      <Association Name="LessonFileTypeEntity_LessonEntity" Member="LessonFileTypeEntity" ThisKey="LessonFileTypeID" OtherKey="LessonFileTypeID" Type="LessonFileTypeEntity" IsForeignKey="true" />
      <Association Name="LessonSubjectEntity_LessonEntity" Member="LessonSubjectEntity" ThisKey="SubjectID" OtherKey="SubjectID" Type="LessonSubjectEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonView" Member="LessonViewEntities" AccessModifier="Internal">
    <Type Name="LessonViewEntity" AccessModifier="Internal">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="LessonPath" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="GuidePath" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="LessonContentTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LessonType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LessonProviderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Provider" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderThumbnail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="StandardGUIDString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardDescriptionString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardSubjectString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LessonFileTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="StandardNumberString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GradeOrderString" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="tUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetSharedProviders" Method="GetSharedProviders">
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSharedProvidersResult">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteLessonGrade" Method="DeleteLessonGrade">
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeId" Parameter="gradeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteLessonStateStandard" Method="DeleteLessonStateStandard">
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MasterStandardId" Parameter="masterStandardId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateLesson" Method="UpdateLesson">
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LessonProviderId" Parameter="lessonProviderId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LessonContentTypeId" Parameter="lessonContentTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SubjectId" Parameter="subjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Keywords" Parameter="keywords" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateLessonPath" Method="UpdateLessonPath">
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LessonFileTypeID" Parameter="lessonFileTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LessonPath" Parameter="lessonPath" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateGuidePath" Method="UpdateGuidePath">
    <Parameter Name="LessonID" Parameter="lessonID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GuidePath" Parameter="guidePath" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>