#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Data.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdminReportingVNS")]
	internal partial class LearningLibraryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLessonContentTypeEntity(LessonContentTypeEntity instance);
    partial void UpdateLessonContentTypeEntity(LessonContentTypeEntity instance);
    partial void DeleteLessonContentTypeEntity(LessonContentTypeEntity instance);
    partial void InsertLessonSubjectEntity(LessonSubjectEntity instance);
    partial void UpdateLessonSubjectEntity(LessonSubjectEntity instance);
    partial void DeleteLessonSubjectEntity(LessonSubjectEntity instance);
    partial void InsertLessonFileTypeEntity(LessonFileTypeEntity instance);
    partial void UpdateLessonFileTypeEntity(LessonFileTypeEntity instance);
    partial void DeleteLessonFileTypeEntity(LessonFileTypeEntity instance);
    partial void InsertLessonGradeEntity(LessonGradeEntity instance);
    partial void UpdateLessonGradeEntity(LessonGradeEntity instance);
    partial void DeleteLessonGradeEntity(LessonGradeEntity instance);
    partial void InsertLessonStateStandardEntity(LessonStateStandardEntity instance);
    partial void UpdateLessonStateStandardEntity(LessonStateStandardEntity instance);
    partial void DeleteLessonStateStandardEntity(LessonStateStandardEntity instance);
    partial void InsertLessonEntity(LessonEntity instance);
    partial void UpdateLessonEntity(LessonEntity instance);
    partial void DeleteLessonEntity(LessonEntity instance);
    #endregion		
		
		
		public LearningLibraryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LearningLibraryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LearningLibraryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LearningLibraryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LessonContentTypeEntity> LessonContentTypeEntities
		{
			get
			{
				return this.GetTable<LessonContentTypeEntity>();
			}
		}
		
		public System.Data.Linq.Table<LessonSubjectEntity> LessonSubjectEntities
		{
			get
			{
				return this.GetTable<LessonSubjectEntity>();
			}
		}
		
		public System.Data.Linq.Table<LessonProviderDistrictViewEntity> LessonProviderDistrictViewEntities
		{
			get
			{
				return this.GetTable<LessonProviderDistrictViewEntity>();
			}
		}
		
		public System.Data.Linq.Table<LessonFileTypeEntity> LessonFileTypeEntities
		{
			get
			{
				return this.GetTable<LessonFileTypeEntity>();
			}
		}
		
		public System.Data.Linq.Table<LessonGradeEntity> LessonGradeEntities
		{
			get
			{
				return this.GetTable<LessonGradeEntity>();
			}
		}
		
		public System.Data.Linq.Table<LessonStateStandardEntity> LessonStateStandardEntities
		{
			get
			{
				return this.GetTable<LessonStateStandardEntity>();
			}
		}
		
		public System.Data.Linq.Table<MasterStandardView> MasterStandardViews
		{
			get
			{
				return this.GetTable<MasterStandardView>();
			}
		}
		
		internal System.Data.Linq.Table<LessonEntity> LessonEntities
		{
			get
			{
				return this.GetTable<LessonEntity>();
			}
		}
		
		internal System.Data.Linq.Table<LessonViewEntity> LessonViewEntities
		{
			get
			{
				return this.GetTable<LessonViewEntity>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSharedProviders")]
		public ISingleResult<GetSharedProvidersResult> GetSharedProviders([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DistrictId", DbType="Int")] System.Nullable<int> districtId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), districtId);
			return ((ISingleResult<GetSharedProvidersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteLessonGrade")]
		public int DeleteLessonGrade([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonID", DbType="Int")] System.Nullable<int> lessonID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GradeId", DbType="Int")] System.Nullable<int> gradeId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lessonID, gradeId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteLessonStateStandard")]
		public int DeleteLessonStateStandard([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonID", DbType="Int")] System.Nullable<int> lessonID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MasterStandardId", DbType="Int")] System.Nullable<int> masterStandardId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lessonID, masterStandardId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateLesson")]
		public int UpdateLesson([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonID", DbType="Int")] System.Nullable<int> lessonID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonProviderId", DbType="Int")] System.Nullable<int> lessonProviderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonContentTypeId", DbType="Int")] System.Nullable<int> lessonContentTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectId", DbType="Int")] System.Nullable<int> subjectId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keywords", DbType="NVarChar(MAX)")] string keywords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lessonID, lessonProviderId, lessonContentTypeId, name, description, subjectId, keywords);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateLessonPath")]
		public int UpdateLessonPath([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonID", DbType="Int")] System.Nullable<int> lessonID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonFileTypeID", DbType="Int")] System.Nullable<int> lessonFileTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonPath", DbType="NVarChar(MAX)")] string lessonPath)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lessonID, lessonFileTypeID, lessonPath);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateGuidePath")]
		public int UpdateGuidePath([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LessonID", DbType="Int")] System.Nullable<int> lessonID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GuidePath", DbType="NVarChar(MAX)")] string guidePath)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lessonID, guidePath);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonContentType")]
	public partial class LessonContentTypeEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LessonContentTypeID;
		
		private string _Code;
		
		private string _Description;
		
		private string _ImagePath;
		
		private string _DisplayText;
		
		private System.Nullable<int> _SortOrder;
		
		private EntitySet<LessonEntity> _LessonEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLessonContentTypeIDChanging(int value);
    partial void OnLessonContentTypeIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    partial void OnDisplayTextChanging(string value);
    partial void OnDisplayTextChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    #endregion
		
		public LessonContentTypeEntity()
		{
			this._LessonEntities = new EntitySet<LessonEntity>(new Action<LessonEntity>(this.attach_LessonEntities), new Action<LessonEntity>(this.detach_LessonEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonContentTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LessonContentTypeID
		{
			get
			{
				return this._LessonContentTypeID;
			}
			set
			{
				if ((this._LessonContentTypeID != value))
				{
					this.OnLessonContentTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LessonContentTypeID = value;
					this.SendPropertyChanged("LessonContentTypeID");
					this.OnLessonContentTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(100)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayText", DbType="VarChar(20)")]
		public string DisplayText
		{
			get
			{
				return this._DisplayText;
			}
			set
			{
				if ((this._DisplayText != value))
				{
					this.OnDisplayTextChanging(value);
					this.SendPropertyChanging();
					this._DisplayText = value;
					this.SendPropertyChanged("DisplayText");
					this.OnDisplayTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonContentTypeEntity_LessonEntity", Storage="_LessonEntities", ThisKey="LessonContentTypeID", OtherKey="LessonContentTypeID")]
		public EntitySet<LessonEntity> LessonEntities
		{
			get
			{
				return this._LessonEntities;
			}
			set
			{
				this._LessonEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LessonEntities(LessonEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonContentTypeEntity = this;
		}
		
		private void detach_LessonEntities(LessonEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonContentTypeEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonSubject")]
	public partial class LessonSubjectEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubjectID;
		
		private string _Name;
		
		private System.Nullable<int> _SortOrder;
		
		private EntitySet<LessonEntity> _LessonEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubjectIDChanging(int value);
    partial void OnSubjectIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    #endregion
		
		public LessonSubjectEntity()
		{
			this._LessonEntities = new EntitySet<LessonEntity>(new Action<LessonEntity>(this.attach_LessonEntities), new Action<LessonEntity>(this.detach_LessonEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this.OnSubjectIDChanging(value);
					this.SendPropertyChanging();
					this._SubjectID = value;
					this.SendPropertyChanged("SubjectID");
					this.OnSubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonSubjectEntity_LessonEntity", Storage="_LessonEntities", ThisKey="SubjectID", OtherKey="SubjectID")]
		public EntitySet<LessonEntity> LessonEntities
		{
			get
			{
				return this._LessonEntities;
			}
			set
			{
				this._LessonEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LessonEntities(LessonEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonSubjectEntity = this;
		}
		
		private void detach_LessonEntities(LessonEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonSubjectEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonProviderDistrictView")]
	public partial class LessonProviderDistrictViewEntity
	{
		
		private int _DistrictID;
		
		private string _Name;
		
		private string _StateName;
		
		private int _StateID;
		
		private string _Code;
		
		private System.Nullable<int> _DistrictGroupID;
		
		private string _LICode;
		
		private System.Nullable<int> _TimeZoneOffsetID;
		
		private int _AllDistrict;
		
		private string _Description;
		
		private System.Nullable<int> _ReferenceID;
		
		private string _ThumbnailPath;
		
		private string _Webpage;
		
		private string _SharedFor;
		
		public LessonProviderDistrictViewEntity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictID", DbType="Int NOT NULL")]
		public int DistrictID
		{
			get
			{
				return this._DistrictID;
			}
			set
			{
				if ((this._DistrictID != value))
				{
					this._DistrictID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StateName
		{
			get
			{
				return this._StateName;
			}
			set
			{
				if ((this._StateName != value))
				{
					this._StateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateID", DbType="Int NOT NULL")]
		public int StateID
		{
			get
			{
				return this._StateID;
			}
			set
			{
				if ((this._StateID != value))
				{
					this._StateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(20)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictGroupID", DbType="Int")]
		public System.Nullable<int> DistrictGroupID
		{
			get
			{
				return this._DistrictGroupID;
			}
			set
			{
				if ((this._DistrictGroupID != value))
				{
					this._DistrictGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LICode", DbType="VarChar(20)")]
		public string LICode
		{
			get
			{
				return this._LICode;
			}
			set
			{
				if ((this._LICode != value))
				{
					this._LICode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZoneOffsetID", DbType="Int")]
		public System.Nullable<int> TimeZoneOffsetID
		{
			get
			{
				return this._TimeZoneOffsetID;
			}
			set
			{
				if ((this._TimeZoneOffsetID != value))
				{
					this._TimeZoneOffsetID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllDistrict", DbType="Int NOT NULL")]
		public int AllDistrict
		{
			get
			{
				return this._AllDistrict;
			}
			set
			{
				if ((this._AllDistrict != value))
				{
					this._AllDistrict = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceID", DbType="Int")]
		public System.Nullable<int> ReferenceID
		{
			get
			{
				return this._ReferenceID;
			}
			set
			{
				if ((this._ReferenceID != value))
				{
					this._ReferenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbnailPath", DbType="VarChar(100)")]
		public string ThumbnailPath
		{
			get
			{
				return this._ThumbnailPath;
			}
			set
			{
				if ((this._ThumbnailPath != value))
				{
					this._ThumbnailPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Webpage", DbType="VarChar(100)")]
		public string Webpage
		{
			get
			{
				return this._Webpage;
			}
			set
			{
				if ((this._Webpage != value))
				{
					this._Webpage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharedFor", DbType="VarChar(4000)")]
		public string SharedFor
		{
			get
			{
				return this._SharedFor;
			}
			set
			{
				if ((this._SharedFor != value))
				{
					this._SharedFor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonFileType")]
	public partial class LessonFileTypeEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LessonFileTypeID;
		
		private string _Name;
		
		private string _Description;
		
		private string _ThumbnailPath;
		
		private EntitySet<LessonEntity> _LessonEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLessonFileTypeIDChanging(int value);
    partial void OnLessonFileTypeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnThumbnailPathChanging(string value);
    partial void OnThumbnailPathChanged();
    #endregion
		
		public LessonFileTypeEntity()
		{
			this._LessonEntities = new EntitySet<LessonEntity>(new Action<LessonEntity>(this.attach_LessonEntities), new Action<LessonEntity>(this.detach_LessonEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonFileTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LessonFileTypeID
		{
			get
			{
				return this._LessonFileTypeID;
			}
			set
			{
				if ((this._LessonFileTypeID != value))
				{
					this.OnLessonFileTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LessonFileTypeID = value;
					this.SendPropertyChanged("LessonFileTypeID");
					this.OnLessonFileTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbnailPath", DbType="VarChar(100)")]
		public string ThumbnailPath
		{
			get
			{
				return this._ThumbnailPath;
			}
			set
			{
				if ((this._ThumbnailPath != value))
				{
					this.OnThumbnailPathChanging(value);
					this.SendPropertyChanging();
					this._ThumbnailPath = value;
					this.SendPropertyChanged("ThumbnailPath");
					this.OnThumbnailPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonFileTypeEntity_LessonEntity", Storage="_LessonEntities", ThisKey="LessonFileTypeID", OtherKey="LessonFileTypeID")]
		public EntitySet<LessonEntity> LessonEntities
		{
			get
			{
				return this._LessonEntities;
			}
			set
			{
				this._LessonEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LessonEntities(LessonEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonFileTypeEntity = this;
		}
		
		private void detach_LessonEntities(LessonEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonFileTypeEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonGrade")]
	public partial class LessonGradeEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LessonGradeID;
		
		private int _LessonID;
		
		private int _GradeID;
		
		private EntityRef<LessonEntity> _LessonEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLessonGradeIDChanging(int value);
    partial void OnLessonGradeIDChanged();
    partial void OnLessonIDChanging(int value);
    partial void OnLessonIDChanged();
    partial void OnGradeIDChanging(int value);
    partial void OnGradeIDChanged();
    #endregion
		
		public LessonGradeEntity()
		{
			this._LessonEntity = default(EntityRef<LessonEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonGradeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LessonGradeID
		{
			get
			{
				return this._LessonGradeID;
			}
			set
			{
				if ((this._LessonGradeID != value))
				{
					this.OnLessonGradeIDChanging(value);
					this.SendPropertyChanging();
					this._LessonGradeID = value;
					this.SendPropertyChanged("LessonGradeID");
					this.OnLessonGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonID", DbType="Int NOT NULL")]
		public int LessonID
		{
			get
			{
				return this._LessonID;
			}
			set
			{
				if ((this._LessonID != value))
				{
					if (this._LessonEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLessonIDChanging(value);
					this.SendPropertyChanging();
					this._LessonID = value;
					this.SendPropertyChanged("LessonID");
					this.OnLessonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int NOT NULL")]
		public int GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonEntity_LessonGradeEntity", Storage="_LessonEntity", ThisKey="LessonID", OtherKey="LessonID", IsForeignKey=true)]
		public LessonEntity LessonEntity
		{
			get
			{
				return this._LessonEntity.Entity;
			}
			set
			{
				LessonEntity previousValue = this._LessonEntity.Entity;
				if (((previousValue != value) 
							|| (this._LessonEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LessonEntity.Entity = null;
						previousValue.LessonGradeEntities.Remove(this);
					}
					this._LessonEntity.Entity = value;
					if ((value != null))
					{
						value.LessonGradeEntities.Add(this);
						this._LessonID = value.LessonID;
					}
					else
					{
						this._LessonID = default(int);
					}
					this.SendPropertyChanged("LessonEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonStateStandard")]
	public partial class LessonStateStandardEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LessonStateStandard1;
		
		private int _StateStandardID;
		
		private int _LessonID;
		
		private System.Nullable<int> _CorrelationID;
		
		private EntityRef<LessonEntity> _LessonEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLessonStateStandard1Changing(int value);
    partial void OnLessonStateStandard1Changed();
    partial void OnStateStandardIDChanging(int value);
    partial void OnStateStandardIDChanged();
    partial void OnLessonIDChanging(int value);
    partial void OnLessonIDChanged();
    partial void OnCorrelationIDChanging(System.Nullable<int> value);
    partial void OnCorrelationIDChanged();
    #endregion
		
		public LessonStateStandardEntity()
		{
			this._LessonEntity = default(EntityRef<LessonEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LessonStateStandard", Storage="_LessonStateStandard1", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LessonStateStandard1
		{
			get
			{
				return this._LessonStateStandard1;
			}
			set
			{
				if ((this._LessonStateStandard1 != value))
				{
					this.OnLessonStateStandard1Changing(value);
					this.SendPropertyChanging();
					this._LessonStateStandard1 = value;
					this.SendPropertyChanged("LessonStateStandard1");
					this.OnLessonStateStandard1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateStandardID", DbType="Int NOT NULL")]
		public int StateStandardID
		{
			get
			{
				return this._StateStandardID;
			}
			set
			{
				if ((this._StateStandardID != value))
				{
					this.OnStateStandardIDChanging(value);
					this.SendPropertyChanging();
					this._StateStandardID = value;
					this.SendPropertyChanged("StateStandardID");
					this.OnStateStandardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonID", DbType="Int NOT NULL")]
		public int LessonID
		{
			get
			{
				return this._LessonID;
			}
			set
			{
				if ((this._LessonID != value))
				{
					if (this._LessonEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLessonIDChanging(value);
					this.SendPropertyChanging();
					this._LessonID = value;
					this.SendPropertyChanged("LessonID");
					this.OnLessonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrelationID", DbType="Int")]
		public System.Nullable<int> CorrelationID
		{
			get
			{
				return this._CorrelationID;
			}
			set
			{
				if ((this._CorrelationID != value))
				{
					this.OnCorrelationIDChanging(value);
					this.SendPropertyChanging();
					this._CorrelationID = value;
					this.SendPropertyChanged("CorrelationID");
					this.OnCorrelationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonEntity_LessonStateStandardEntity", Storage="_LessonEntity", ThisKey="LessonID", OtherKey="LessonID", IsForeignKey=true)]
		public LessonEntity LessonEntity
		{
			get
			{
				return this._LessonEntity.Entity;
			}
			set
			{
				LessonEntity previousValue = this._LessonEntity.Entity;
				if (((previousValue != value) 
							|| (this._LessonEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LessonEntity.Entity = null;
						previousValue.LessonStateStandardEntities.Remove(this);
					}
					this._LessonEntity.Entity = value;
					if ((value != null))
					{
						value.LessonStateStandardEntities.Add(this);
						this._LessonID = value.LessonID;
					}
					else
					{
						this._LessonID = default(int);
					}
					this.SendPropertyChanged("LessonEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MasterStandardView")]
	public partial class MasterStandardView
	{
		
		private int _MasterStandardID;
		
		private string _State;
		
		private string _Subject;
		
		private int _Year;
		
		private string _Grade;
		
		private int _Level;
		
		private string _Label;
		
		private string _Number;
		
		private string _Description;
		
		private string _GUID;
		
		private string _ParentGUID;
		
		private System.Nullable<int> _StateId;
		
		private string _LoGrade;
		
		private string _HiGrade;
		
		private System.Nullable<int> _LowGradeID;
		
		private System.Nullable<int> _HighGradeID;
		
		private bool _Archived;
		
		private int _Children;
		
		private System.Nullable<int> _CountChildren;
		
		public MasterStandardView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterStandardID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MasterStandardID
		{
			get
			{
				return this._MasterStandardID;
			}
			set
			{
				if ((this._MasterStandardID != value))
				{
					this._MasterStandardID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL")]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Label", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Label
		{
			get
			{
				return this._Label;
			}
			set
			{
				if ((this._Label != value))
				{
					this._Label = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this._GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentGUID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ParentGUID
		{
			get
			{
				return this._ParentGUID;
			}
			set
			{
				if ((this._ParentGUID != value))
				{
					this._ParentGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", DbType="Int")]
		public System.Nullable<int> StateId
		{
			get
			{
				return this._StateId;
			}
			set
			{
				if ((this._StateId != value))
				{
					this._StateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoGrade", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string LoGrade
		{
			get
			{
				return this._LoGrade;
			}
			set
			{
				if ((this._LoGrade != value))
				{
					this._LoGrade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HiGrade", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string HiGrade
		{
			get
			{
				return this._HiGrade;
			}
			set
			{
				if ((this._HiGrade != value))
				{
					this._HiGrade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowGradeID", DbType="Int")]
		public System.Nullable<int> LowGradeID
		{
			get
			{
				return this._LowGradeID;
			}
			set
			{
				if ((this._LowGradeID != value))
				{
					this._LowGradeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighGradeID", DbType="Int")]
		public System.Nullable<int> HighGradeID
		{
			get
			{
				return this._HighGradeID;
			}
			set
			{
				if ((this._HighGradeID != value))
				{
					this._HighGradeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archived", DbType="Bit NOT NULL")]
		public bool Archived
		{
			get
			{
				return this._Archived;
			}
			set
			{
				if ((this._Archived != value))
				{
					this._Archived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Children", DbType="Int NOT NULL")]
		public int Children
		{
			get
			{
				return this._Children;
			}
			set
			{
				if ((this._Children != value))
				{
					this._Children = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountChildren", DbType="Int")]
		public System.Nullable<int> CountChildren
		{
			get
			{
				return this._CountChildren;
			}
			set
			{
				if ((this._CountChildren != value))
				{
					this._CountChildren = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lesson")]
	public partial class LessonEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LessonID;
		
		private int _LessonFileTypeID;
		
		private int _SubjectID;
		
		private string _Name;
		
		private string _Description;
		
		private string _Keywords;
		
		private string _LessonPath;
		
		private string _GuidePath;
		
		private string _ThumbnailPath;
		
		private int _LessonContentTypeID;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		private System.Nullable<int> _UserID;
		
		private string _Source;
		
		private string _FileName;
		
		private string _urlPath;
		
		private System.Nullable<System.Guid> _LessonGuid;
		
		private System.Nullable<int> _SourceID;
		
		private System.Nullable<int> _tUserID;
		
		private System.Nullable<bool> _Blocked;
		
		private System.Nullable<int> _LessonProviderID;
		
		private string _GradeString;
		
		private string _StandardGUIDString;
		
		private string _StandardDescriptionString;
		
		private string _StandardSubjectString;
		
		private string _StandardNumberString;
		
		private string _GradeOrderString;
		
		private EntitySet<LessonGradeEntity> _LessonGradeEntities;
		
		private EntitySet<LessonStateStandardEntity> _LessonStateStandardEntities;
		
		private EntityRef<LessonContentTypeEntity> _LessonContentTypeEntity;
		
		private EntityRef<LessonFileTypeEntity> _LessonFileTypeEntity;
		
		private EntityRef<LessonSubjectEntity> _LessonSubjectEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLessonIDChanging(int value);
    partial void OnLessonIDChanged();
    partial void OnLessonFileTypeIDChanging(int value);
    partial void OnLessonFileTypeIDChanged();
    partial void OnSubjectIDChanging(int value);
    partial void OnSubjectIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    partial void OnLessonPathChanging(string value);
    partial void OnLessonPathChanged();
    partial void OnGuidePathChanging(string value);
    partial void OnGuidePathChanged();
    partial void OnThumbnailPathChanging(string value);
    partial void OnThumbnailPathChanged();
    partial void OnLessonContentTypeIDChanging(int value);
    partial void OnLessonContentTypeIDChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateUpdatedChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnurlPathChanging(string value);
    partial void OnurlPathChanged();
    partial void OnLessonGuidChanging(System.Nullable<System.Guid> value);
    partial void OnLessonGuidChanged();
    partial void OnSourceIDChanging(System.Nullable<int> value);
    partial void OnSourceIDChanged();
    partial void OntUserIDChanging(System.Nullable<int> value);
    partial void OntUserIDChanged();
    partial void OnBlockedChanging(System.Nullable<bool> value);
    partial void OnBlockedChanged();
    partial void OnLessonProviderIDChanging(System.Nullable<int> value);
    partial void OnLessonProviderIDChanged();
    partial void OnGradeStringChanging(string value);
    partial void OnGradeStringChanged();
    partial void OnStandardGUIDStringChanging(string value);
    partial void OnStandardGUIDStringChanged();
    partial void OnStandardDescriptionStringChanging(string value);
    partial void OnStandardDescriptionStringChanged();
    partial void OnStandardSubjectStringChanging(string value);
    partial void OnStandardSubjectStringChanged();
    partial void OnStandardNumberStringChanging(string value);
    partial void OnStandardNumberStringChanged();
    partial void OnGradeOrderStringChanging(string value);
    partial void OnGradeOrderStringChanged();
    #endregion
		
		public LessonEntity()
		{
			this._LessonGradeEntities = new EntitySet<LessonGradeEntity>(new Action<LessonGradeEntity>(this.attach_LessonGradeEntities), new Action<LessonGradeEntity>(this.detach_LessonGradeEntities));
			this._LessonStateStandardEntities = new EntitySet<LessonStateStandardEntity>(new Action<LessonStateStandardEntity>(this.attach_LessonStateStandardEntities), new Action<LessonStateStandardEntity>(this.detach_LessonStateStandardEntities));
			this._LessonContentTypeEntity = default(EntityRef<LessonContentTypeEntity>);
			this._LessonFileTypeEntity = default(EntityRef<LessonFileTypeEntity>);
			this._LessonSubjectEntity = default(EntityRef<LessonSubjectEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LessonID
		{
			get
			{
				return this._LessonID;
			}
			set
			{
				if ((this._LessonID != value))
				{
					this.OnLessonIDChanging(value);
					this.SendPropertyChanging();
					this._LessonID = value;
					this.SendPropertyChanged("LessonID");
					this.OnLessonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonFileTypeID", DbType="Int NOT NULL")]
		public int LessonFileTypeID
		{
			get
			{
				return this._LessonFileTypeID;
			}
			set
			{
				if ((this._LessonFileTypeID != value))
				{
					if (this._LessonFileTypeEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLessonFileTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LessonFileTypeID = value;
					this.SendPropertyChanged("LessonFileTypeID");
					this.OnLessonFileTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					if (this._LessonSubjectEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubjectIDChanging(value);
					this.SendPropertyChanging();
					this._SubjectID = value;
					this.SendPropertyChanged("SubjectID");
					this.OnSubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this.OnKeywordsChanging(value);
					this.SendPropertyChanging();
					this._Keywords = value;
					this.SendPropertyChanged("Keywords");
					this.OnKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonPath", DbType="NVarChar(450)")]
		public string LessonPath
		{
			get
			{
				return this._LessonPath;
			}
			set
			{
				if ((this._LessonPath != value))
				{
					this.OnLessonPathChanging(value);
					this.SendPropertyChanging();
					this._LessonPath = value;
					this.SendPropertyChanged("LessonPath");
					this.OnLessonPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuidePath", DbType="NVarChar(450)")]
		public string GuidePath
		{
			get
			{
				return this._GuidePath;
			}
			set
			{
				if ((this._GuidePath != value))
				{
					this.OnGuidePathChanging(value);
					this.SendPropertyChanging();
					this._GuidePath = value;
					this.SendPropertyChanged("GuidePath");
					this.OnGuidePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbnailPath", DbType="NVarChar(450)")]
		public string ThumbnailPath
		{
			get
			{
				return this._ThumbnailPath;
			}
			set
			{
				if ((this._ThumbnailPath != value))
				{
					this.OnThumbnailPathChanging(value);
					this.SendPropertyChanging();
					this._ThumbnailPath = value;
					this.SendPropertyChanged("ThumbnailPath");
					this.OnThumbnailPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonContentTypeID", DbType="Int NOT NULL")]
		public int LessonContentTypeID
		{
			get
			{
				return this._LessonContentTypeID;
			}
			set
			{
				if ((this._LessonContentTypeID != value))
				{
					if (this._LessonContentTypeEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLessonContentTypeIDChanging(value);
					this.SendPropertyChanging();
					this._LessonContentTypeID = value;
					this.SendPropertyChanged("LessonContentTypeID");
					this.OnLessonContentTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this.OnDateUpdatedChanging(value);
					this.SendPropertyChanging();
					this._DateUpdated = value;
					this.SendPropertyChanged("DateUpdated");
					this.OnDateUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NChar(10)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(200)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlPath", DbType="NVarChar(200)")]
		public string urlPath
		{
			get
			{
				return this._urlPath;
			}
			set
			{
				if ((this._urlPath != value))
				{
					this.OnurlPathChanging(value);
					this.SendPropertyChanging();
					this._urlPath = value;
					this.SendPropertyChanged("urlPath");
					this.OnurlPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> LessonGuid
		{
			get
			{
				return this._LessonGuid;
			}
			set
			{
				if ((this._LessonGuid != value))
				{
					this.OnLessonGuidChanging(value);
					this.SendPropertyChanging();
					this._LessonGuid = value;
					this.SendPropertyChanged("LessonGuid");
					this.OnLessonGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceID", DbType="Int")]
		public System.Nullable<int> SourceID
		{
			get
			{
				return this._SourceID;
			}
			set
			{
				if ((this._SourceID != value))
				{
					this.OnSourceIDChanging(value);
					this.SendPropertyChanging();
					this._SourceID = value;
					this.SendPropertyChanged("SourceID");
					this.OnSourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tUserID", DbType="Int")]
		public System.Nullable<int> tUserID
		{
			get
			{
				return this._tUserID;
			}
			set
			{
				if ((this._tUserID != value))
				{
					this.OntUserIDChanging(value);
					this.SendPropertyChanging();
					this._tUserID = value;
					this.SendPropertyChanged("tUserID");
					this.OntUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blocked", DbType="Bit")]
		public System.Nullable<bool> Blocked
		{
			get
			{
				return this._Blocked;
			}
			set
			{
				if ((this._Blocked != value))
				{
					this.OnBlockedChanging(value);
					this.SendPropertyChanging();
					this._Blocked = value;
					this.SendPropertyChanged("Blocked");
					this.OnBlockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonProviderID", DbType="Int")]
		public System.Nullable<int> LessonProviderID
		{
			get
			{
				return this._LessonProviderID;
			}
			set
			{
				if ((this._LessonProviderID != value))
				{
					this.OnLessonProviderIDChanging(value);
					this.SendPropertyChanging();
					this._LessonProviderID = value;
					this.SendPropertyChanged("LessonProviderID");
					this.OnLessonProviderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeString", DbType="VarChar(500)")]
		public string GradeString
		{
			get
			{
				return this._GradeString;
			}
			set
			{
				if ((this._GradeString != value))
				{
					this.OnGradeStringChanging(value);
					this.SendPropertyChanging();
					this._GradeString = value;
					this.SendPropertyChanged("GradeString");
					this.OnGradeStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardGUIDString", DbType="NVarChar(MAX)")]
		public string StandardGUIDString
		{
			get
			{
				return this._StandardGUIDString;
			}
			set
			{
				if ((this._StandardGUIDString != value))
				{
					this.OnStandardGUIDStringChanging(value);
					this.SendPropertyChanging();
					this._StandardGUIDString = value;
					this.SendPropertyChanged("StandardGUIDString");
					this.OnStandardGUIDStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardDescriptionString", DbType="NVarChar(MAX)")]
		public string StandardDescriptionString
		{
			get
			{
				return this._StandardDescriptionString;
			}
			set
			{
				if ((this._StandardDescriptionString != value))
				{
					this.OnStandardDescriptionStringChanging(value);
					this.SendPropertyChanging();
					this._StandardDescriptionString = value;
					this.SendPropertyChanged("StandardDescriptionString");
					this.OnStandardDescriptionStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardSubjectString", DbType="NVarChar(MAX)")]
		public string StandardSubjectString
		{
			get
			{
				return this._StandardSubjectString;
			}
			set
			{
				if ((this._StandardSubjectString != value))
				{
					this.OnStandardSubjectStringChanging(value);
					this.SendPropertyChanging();
					this._StandardSubjectString = value;
					this.SendPropertyChanged("StandardSubjectString");
					this.OnStandardSubjectStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardNumberString", DbType="NVarChar(MAX)")]
		public string StandardNumberString
		{
			get
			{
				return this._StandardNumberString;
			}
			set
			{
				if ((this._StandardNumberString != value))
				{
					this.OnStandardNumberStringChanging(value);
					this.SendPropertyChanging();
					this._StandardNumberString = value;
					this.SendPropertyChanged("StandardNumberString");
					this.OnStandardNumberStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeOrderString", DbType="VarChar(500)")]
		public string GradeOrderString
		{
			get
			{
				return this._GradeOrderString;
			}
			set
			{
				if ((this._GradeOrderString != value))
				{
					this.OnGradeOrderStringChanging(value);
					this.SendPropertyChanging();
					this._GradeOrderString = value;
					this.SendPropertyChanged("GradeOrderString");
					this.OnGradeOrderStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonEntity_LessonGradeEntity", Storage="_LessonGradeEntities", ThisKey="LessonID", OtherKey="LessonID")]
		public EntitySet<LessonGradeEntity> LessonGradeEntities
		{
			get
			{
				return this._LessonGradeEntities;
			}
			set
			{
				this._LessonGradeEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonEntity_LessonStateStandardEntity", Storage="_LessonStateStandardEntities", ThisKey="LessonID", OtherKey="LessonID")]
		public EntitySet<LessonStateStandardEntity> LessonStateStandardEntities
		{
			get
			{
				return this._LessonStateStandardEntities;
			}
			set
			{
				this._LessonStateStandardEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonContentTypeEntity_LessonEntity", Storage="_LessonContentTypeEntity", ThisKey="LessonContentTypeID", OtherKey="LessonContentTypeID", IsForeignKey=true)]
		public LessonContentTypeEntity LessonContentTypeEntity
		{
			get
			{
				return this._LessonContentTypeEntity.Entity;
			}
			set
			{
				LessonContentTypeEntity previousValue = this._LessonContentTypeEntity.Entity;
				if (((previousValue != value) 
							|| (this._LessonContentTypeEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LessonContentTypeEntity.Entity = null;
						previousValue.LessonEntities.Remove(this);
					}
					this._LessonContentTypeEntity.Entity = value;
					if ((value != null))
					{
						value.LessonEntities.Add(this);
						this._LessonContentTypeID = value.LessonContentTypeID;
					}
					else
					{
						this._LessonContentTypeID = default(int);
					}
					this.SendPropertyChanged("LessonContentTypeEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonFileTypeEntity_LessonEntity", Storage="_LessonFileTypeEntity", ThisKey="LessonFileTypeID", OtherKey="LessonFileTypeID", IsForeignKey=true)]
		public LessonFileTypeEntity LessonFileTypeEntity
		{
			get
			{
				return this._LessonFileTypeEntity.Entity;
			}
			set
			{
				LessonFileTypeEntity previousValue = this._LessonFileTypeEntity.Entity;
				if (((previousValue != value) 
							|| (this._LessonFileTypeEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LessonFileTypeEntity.Entity = null;
						previousValue.LessonEntities.Remove(this);
					}
					this._LessonFileTypeEntity.Entity = value;
					if ((value != null))
					{
						value.LessonEntities.Add(this);
						this._LessonFileTypeID = value.LessonFileTypeID;
					}
					else
					{
						this._LessonFileTypeID = default(int);
					}
					this.SendPropertyChanged("LessonFileTypeEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LessonSubjectEntity_LessonEntity", Storage="_LessonSubjectEntity", ThisKey="SubjectID", OtherKey="SubjectID", IsForeignKey=true)]
		public LessonSubjectEntity LessonSubjectEntity
		{
			get
			{
				return this._LessonSubjectEntity.Entity;
			}
			set
			{
				LessonSubjectEntity previousValue = this._LessonSubjectEntity.Entity;
				if (((previousValue != value) 
							|| (this._LessonSubjectEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LessonSubjectEntity.Entity = null;
						previousValue.LessonEntities.Remove(this);
					}
					this._LessonSubjectEntity.Entity = value;
					if ((value != null))
					{
						value.LessonEntities.Add(this);
						this._SubjectID = value.SubjectID;
					}
					else
					{
						this._SubjectID = default(int);
					}
					this.SendPropertyChanged("LessonSubjectEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LessonGradeEntities(LessonGradeEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonEntity = this;
		}
		
		private void detach_LessonGradeEntities(LessonGradeEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonEntity = null;
		}
		
		private void attach_LessonStateStandardEntities(LessonStateStandardEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonEntity = this;
		}
		
		private void detach_LessonStateStandardEntities(LessonStateStandardEntity entity)
		{
			this.SendPropertyChanging();
			entity.LessonEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LessonView")]
	internal partial class LessonViewEntity
	{
		
		private int _LessonID;
		
		private string _LessonName;
		
		private string _Grade;
		
		private string _LessonPath;
		
		private string _GuidePath;
		
		private int _LessonContentTypeID;
		
		private string _LessonType;
		
		private string _SubjectName;
		
		private System.Nullable<int> _LessonProviderID;
		
		private string _Provider;
		
		private string _ProviderThumbnail;
		
		private int _SubjectID;
		
		private string _Keywords;
		
		private string _StandardGUIDString;
		
		private string _StandardDescriptionString;
		
		private string _StandardSubjectString;
		
		private int _LessonFileTypeID;
		
		private string _Description;
		
		private string _StandardNumberString;
		
		private string _GradeOrderString;
		
		private System.Nullable<int> _tUserID;
		
		public LessonViewEntity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonID", DbType="Int NOT NULL")]
		public int LessonID
		{
			get
			{
				return this._LessonID;
			}
			set
			{
				if ((this._LessonID != value))
				{
					this._LessonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string LessonName
		{
			get
			{
				return this._LessonName;
			}
			set
			{
				if ((this._LessonName != value))
				{
					this._LessonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(500)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonPath", DbType="NVarChar(450)")]
		public string LessonPath
		{
			get
			{
				return this._LessonPath;
			}
			set
			{
				if ((this._LessonPath != value))
				{
					this._LessonPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuidePath", DbType="NVarChar(450)")]
		public string GuidePath
		{
			get
			{
				return this._GuidePath;
			}
			set
			{
				if ((this._GuidePath != value))
				{
					this._GuidePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonContentTypeID", DbType="Int NOT NULL")]
		public int LessonContentTypeID
		{
			get
			{
				return this._LessonContentTypeID;
			}
			set
			{
				if ((this._LessonContentTypeID != value))
				{
					this._LessonContentTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonType", DbType="VarChar(20)")]
		public string LessonType
		{
			get
			{
				return this._LessonType;
			}
			set
			{
				if ((this._LessonType != value))
				{
					this._LessonType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonProviderID", DbType="Int")]
		public System.Nullable<int> LessonProviderID
		{
			get
			{
				return this._LessonProviderID;
			}
			set
			{
				if ((this._LessonProviderID != value))
				{
					this._LessonProviderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Provider
		{
			get
			{
				return this._Provider;
			}
			set
			{
				if ((this._Provider != value))
				{
					this._Provider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderThumbnail", DbType="VarChar(100)")]
		public string ProviderThumbnail
		{
			get
			{
				return this._ProviderThumbnail;
			}
			set
			{
				if ((this._ProviderThumbnail != value))
				{
					this._ProviderThumbnail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this._Keywords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardGUIDString", DbType="NVarChar(MAX)")]
		public string StandardGUIDString
		{
			get
			{
				return this._StandardGUIDString;
			}
			set
			{
				if ((this._StandardGUIDString != value))
				{
					this._StandardGUIDString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardDescriptionString", DbType="NVarChar(MAX)")]
		public string StandardDescriptionString
		{
			get
			{
				return this._StandardDescriptionString;
			}
			set
			{
				if ((this._StandardDescriptionString != value))
				{
					this._StandardDescriptionString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardSubjectString", DbType="NVarChar(MAX)")]
		public string StandardSubjectString
		{
			get
			{
				return this._StandardSubjectString;
			}
			set
			{
				if ((this._StandardSubjectString != value))
				{
					this._StandardSubjectString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonFileTypeID", DbType="Int NOT NULL")]
		public int LessonFileTypeID
		{
			get
			{
				return this._LessonFileTypeID;
			}
			set
			{
				if ((this._LessonFileTypeID != value))
				{
					this._LessonFileTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardNumberString", DbType="NVarChar(MAX)")]
		public string StandardNumberString
		{
			get
			{
				return this._StandardNumberString;
			}
			set
			{
				if ((this._StandardNumberString != value))
				{
					this._StandardNumberString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeOrderString", DbType="VarChar(500)")]
		public string GradeOrderString
		{
			get
			{
				return this._GradeOrderString;
			}
			set
			{
				if ((this._GradeOrderString != value))
				{
					this._GradeOrderString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tUserID", DbType="Int")]
		public System.Nullable<int> tUserID
		{
			get
			{
				return this._tUserID;
			}
			set
			{
				if ((this._tUserID != value))
				{
					this._tUserID = value;
				}
			}
		}
	}
	
	public partial class GetSharedProvidersResult
	{
		
		private int _DistrictID;
		
		private string _Name;
		
		public GetSharedProvidersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictID", DbType="Int NOT NULL")]
		public int DistrictID
		{
			get
			{
				return this._DistrictID;
			}
			set
			{
				if ((this._DistrictID != value))
				{
					this._DistrictID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
