<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="MultiPartQuestionContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString30" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MultiPartQTIItemExpression" Member="MultiPartQTIItemExpressionEntities" AccessModifier="Internal">
    <Type Name="MultiPartQTIItemExpressionEntity" AccessModifier="Internal">
      <Column Name="MultiPartQTIItemExpressionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QTIItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expression" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EnableElements" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rules" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MultiPartVirtualQuestionExpression" Member="MultiPartVirtualQuestionExpressionEntities" AccessModifier="Internal">
    <Type Name="MultiPartVirtualQuestionExpressionEntity" AccessModifier="Internal">
      <Column Name="MultiPartVirtualQuestionExpressionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expression" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EnableElements" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rules" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.MultiPartSaveExpression" Method="MultiPartSaveExpression">
    <Parameter Name="QTIItemID" Parameter="qTIItemID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualQuestionID" Parameter="virtualQuestionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExpressionXML" Parameter="expressionXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="MultiPartSaveExpressionResult">
      <Column Name="MultiPartQTIItemExpressionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MultiPartVirtualQuestionExpressionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Expression" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rules" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DuplicateMultiPartQTIItemExpression" Method="DuplicateMultiPartQTIItemExpression">
    <Parameter Name="oldQtiItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="newQtiItemId" Type="System.Int32" DbType="Int" />
    <Parameter Name="currentUserId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>