<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="NavigatorReportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString34" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NavigatorReportPublish" Member="NavigatorReportPublishEntities">
    <Type Name="NavigatorReportPublishEntity">
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsPublished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PublishFirstTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublishTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublisherId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NavigatorReportEntity_NavigatorReportPublishEntity" Member="NavigatorReportEntity" ThisKey="NavigatorReportID" OtherKey="NavigatorReportID" Type="NavigatorReportEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NavigatorReportDetail" Member="NavigatorReportDetailEntities">
    <Type Name="NavigatorReportDetailEntity">
      <Column Name="NavigatorReportDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NavigatorReportEntity_NavigatorReportDetailEntity" Member="NavigatorReportEntity" ThisKey="NavigatorReportID" OtherKey="NavigatorReportID" Type="NavigatorReportEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NavigatorAttribute" Member="NavigatorAttributeEntities">
    <Type Name="NavigatorAttributeEntity">
      <Column Name="NavigatorAttributeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AttributeType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ListOrder" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Association Name="NavigatorAttributeEntity_NavigatorConfigurationEntity" Member="NavigatorConfigurationEntities" ThisKey="NavigatorAttributeID" OtherKey="NavigatorCategoryID" Type="NavigatorConfigurationEntity" />
    </Type>
  </Table>
  <Table Name="dbo.NavigatorReportLog" Member="NavigatorReportLogEntities">
    <Type Name="NavigatorReportLogEntity">
      <Column Name="NavigatorReportLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NavigatorReportDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="CallStack" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NavigatorConfiguration" Member="NavigatorConfigurationEntities">
    <Type Name="NavigatorConfigurationEntity">
      <Column Name="NavigatorConfigurationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NavigatorCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UseSchool" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseClass" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseStudent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanPublishSchoolAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanPublishTeacher" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanPublishStudent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanPublishDistrictAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KeywordMandatory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PeriodMandatory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReportTypePattern" Type="System.String" DbType="Varchar(1000) NULL" CanBeNull="false" />
      <Column Name="SchoolPattern" Type="System.String" DbType="Varchar(1000) NULL" CanBeNull="false" />
      <Column Name="SuffixPattern" Type="System.String" DbType="Varchar(1000) NULL" CanBeNull="false" />
      <Association Name="NavigatorConfigurationEntity_NavigatorFolderPathway" Member="NavigatorFolderPathwayEntities" ThisKey="NavigatorConfigurationID" OtherKey="NavigatorConfigurationID" Type="NavigatorFolderPathwayEntity" />
      <Association Name="NavigatorAttributeEntity_NavigatorConfigurationEntity" Member="NavigatorAttributeEntity" ThisKey="NavigatorCategoryID" OtherKey="NavigatorAttributeID" Type="NavigatorAttributeEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NavigatorReport" Member="NavigatorReportEntities">
    <Type Name="NavigatorReportEntity">
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="S3FileFullName" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NavigatorConfigurationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportingPeriodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeywordIDs" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReportSuffix" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CreatedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublishedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NavigatorReportEntity_NavigatorReportPublishEntity" Member="NavigatorReportPublishEntities" ThisKey="NavigatorReportID" OtherKey="NavigatorReportID" Type="NavigatorReportPublishEntity" />
      <Association Name="NavigatorReportEntity_NavigatorReportDetailEntity" Member="NavigatorReportDetailEntities" ThisKey="NavigatorReportID" OtherKey="NavigatorReportID" Type="NavigatorReportDetailEntity" />
    </Type>
  </Table>
  <Table Name="dbo.NavigatorFolderPathway" Member="NavigatorFolderPathwayEntities">
    <Type Name="NavigatorFolderPathwayEntity">
      <Column Name="NavigatorFolderPathwayID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NavigatorConfigurationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolderPathway" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="NavigatorConfigurationEntity_NavigatorFolderPathway" Member="NavigatorConfigurationEntity" ThisKey="NavigatorConfigurationID" OtherKey="NavigatorConfigurationID" Type="NavigatorConfigurationEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.NavigatorReportGetUploadedReportsInfo" Method="NavigatorReportGetUploadedReportsInfo">
    <Parameter Name="userid" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdList" Parameter="idList" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="NavigatorReportGetUploadedReportsInfoResult">
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NavigatorCategory" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetViewableNavigatorReportAttributes" Method="GetViewableNavigatorReportAttributes">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StateId" Parameter="stateId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Years" Parameter="years" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="GetViewableNavigatorReportAttributesResult">
      <Column Name="Type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ord" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetReportIdsInAScope" Method="NavigatorGetReportIdsInAScope">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AcceptedYears" Parameter="acceptedYears" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Year" Parameter="year" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="NavigatorReportCategoryId" Parameter="navigatorReportCategoryId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrimaryKeywordId" Parameter="primaryKeywordId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReportingPeriodId" Parameter="reportingPeriodId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorGetReportIdsInAScopeResult">
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportPublishByRole" Method="NavigatorReportPublishByRole">
    <Parameter Name="NavigatorReportIds" Parameter="navigatorReportIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="RolesTobePublised" Parameter="rolesTobePublised" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorReportPublishByRoleResult">
      <Column Name="Result" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetReportFiles" Method="NavigatorReportGetReportFiles">
    <Parameter Name="userid" Type="System.Int32" DbType="Int" />
    <Parameter Name="navigatorReportIds" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorReportGetReportFilesResult">
      <Column Name="S3FileFullName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MasterFileName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetReportFilesByClassId" Method="NavigatorReportGetReportFilesByClassId">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorReportGetReportFilesByClassIdResult">
      <Column Name="S3FileFullName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NavigatorReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MasterFileName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetFilterDownload" Method="NavigatorReportGetFilterDownload">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ResultToTempTable" Parameter="resultToTempTable" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorReportGetFilterDownloadResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DistrictTermName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetReportFolderDetail" Method="NavigatorGetReportFolderDetail">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="RolesTobePublised" Parameter="rolesTobePublised" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorGetReportFolderDetailResult">
      <Column Name="ReportCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublishedReportCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CanPublishSchoolAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishTeacher" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishStudent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetSchoolFolderDetail" Method="NavigatorGetSchoolFolderDetail">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorGetSchoolFolderDetailResult">
      <Column Name="ReportName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RoleShortName" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ORD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleTooltip" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PublishStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetRolesToPublishByIdentifiers" Method="NavigatorGetRolesToPublishByIdentifiers">
    <Parameter Name="Identifiers" Parameter="identifiers" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AcceptedYears" Parameter="acceptedYears" Type="System.String" DbType="VarChar(500)" />
    <ElementType Name="NavigatorGetRolesToPublishByIdentifiersResult">
      <Column Name="CanPublishDistrictAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishSchoolAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishStudent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishTeacher" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictAdminReportNames" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="SchoolAdminReportNames" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="StudentReportNames" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="TeacherReportNames" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetMaxConfiguration" Method="NavigatorReportGetMaxConfiguration">
    <Parameter Name="NavigatorReportIds" Parameter="navigatorReportIds" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorReportGetMaxConfigurationResult">
      <Column Name="CanPublishDistrictAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishSchoolAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishStudent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishTeacher" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportUnPublishByUserId" Method="NavigatorReportUnPublishByUserId">
    <Parameter Name="UserIds" Parameter="userIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="NavigatorReportIds" Parameter="navigatorReportIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="PublishDistrictAdmin" Parameter="publishDistrictAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishSchoolAdmin" Parameter="publishSchoolAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishTeacher" Parameter="publishTeacher" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishStudent" Parameter="publishStudent" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishTime" Parameter="publishTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PublisherId" Parameter="publisherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorReportUnPublishByUserIdResult">
      <Column Name="" Member="Column1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetAssociateUserByReportIds" Method="NavigatorReportGetAssociateUserByReportIds">
    <Parameter Name="NavigatorReportIds" Parameter="navigatorReportIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="IsPublished" Parameter="isPublished" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShowDistrictAdmin" Parameter="showDistrictAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShowSchoolAdmin" Parameter="showSchoolAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShowTeacher" Parameter="showTeacher" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShowStudent" Parameter="showStudent" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ProgramIds" Parameter="programIds" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="GradeIds" Parameter="gradeIds" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="selectUserIdOnly" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserTemptableName" Parameter="userTemptableName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorReportGetAssociateUserByReportIdsResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublishStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublishTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserFullName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetStudentGrade" Method="NavigatorReportGetStudentGrade">
    <Parameter Name="UserIds" Parameter="userIds" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorReportGetStudentGradeResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportGetStudentPrograms" Method="NavigatorReportGetStudentPrograms">
    <Parameter Name="UserIds" Parameter="userIds" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorReportGetStudentProgramsResult">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetAssociateEmailsWhichNotPublished" Method="NavigatorGetAssociateEmailsWhichNotPublished">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="showDistrictAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="showSchoolAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="showTeacher" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="showStudent" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="NavigatorGetAssociateEmailsWhichNotPublishedResult">
      <Column Name="Email" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportPublishByRoleAndIdentifiers" Method="NavigatorReportPublishByRoleAndIdentifiers">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="RolesTobePublised" Parameter="rolesTobePublised" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExcludeUserIds" Parameter="excludeUserIds" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorReportPublishByRoleAndIdentifiersResult">
      <Column Name="ReportCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserFullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserRoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NavigatorReportId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ReportType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Initiator" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="BreadCrumb" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetFileDetail" Method="NavigatorGetFileDetail">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorGetFileDetailResult">
      <Column Name="TotalDistrictAdmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDistrictAdminPublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalSchoolAdmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalSchoolAdminPublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTeacher" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTeacherPublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalStudent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalStudentPublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrimaryKeyword" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OtherKeywords" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CanPublishDistrictAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishSchoolAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishTeacher" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanPublishStudent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KeywordMandatory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetManageAccessPopupDetail" Method="NavigatorGetManageAccessPopupDetail">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserIdsToBePublished" Parameter="userIdsToBePublished" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="NavigatorGetManageAccessPopupDetailResult">
      <Column Name="mask" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorReportPublishByUserId" Method="NavigatorReportPublishByUserId">
    <Parameter Name="UserIds" Parameter="userIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="NavigatorReportIds" Parameter="navigatorReportIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="PublishDistrictAdmin" Parameter="publishDistrictAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishSchoolAdmin" Parameter="publishSchoolAdmin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishTeacher" Parameter="publishTeacher" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishStudent" Parameter="publishStudent" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PublishTime" Parameter="publishTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PublisherId" Parameter="publisherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NavigatorReportPublishByUserIdResult">
      <Column Name="mask" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NavigatorGetDirectoryList" Method="NavigatorGetDirectoryList">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AcceptedYears" Parameter="acceptedYears" Type="System.String" DbType="VarChar(500)" />
    <ElementType Name="NavigatorGetDirectoryListResult">
      <Column Name="Year" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NavigatorCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NavigatorCategory" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PrimaryKeywordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrimaryKeyword" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ReportingPeriodId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportingPeriod" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ReportingType" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ReportSuffix" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="S3FileFullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NavigatorReportId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NavigatorConfigurationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>
