<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="ParentDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString30" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MessageReceiver" Member="MessageReceiverEntities">
    <Type Name="MessageReceiverEntity">
      <Column Name="MessageReceiverID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRead" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MessageEntity_MessageReceiverEntity" Member="MessageEntity" ThisKey="MessageID" OtherKey="MessageID" Type="MessageEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportGroup" Member="ReportGroupEntities">
    <Type Name="ReportGroupEntity">
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GroupType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ReportGroupEntity_ReportGroupStudentEntity" Member="ReportGroupStudentEntities" ThisKey="ReportGroupID" OtherKey="ReportGroupID" Type="ReportGroupStudentEntity" />
    </Type>
  </Table>
  <Table Name="dbo.ReportGroupStudent" Member="ReportGroupStudentEntities">
    <Type Name="ReportGroupStudentEntity">
      <Column Name="ReportGroupStudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ReportGroupEntity_ReportGroupStudentEntity" Member="ReportGroupEntity" ThisKey="ReportGroupID" OtherKey="ReportGroupID" Type="ReportGroupEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportGroupStudentView" Member="ReportGroupStudentViews">
    <Type Name="ReportGroupStudentView">
      <Column Name="ReportGroupStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StudentInClassWithParentsView" Member="StudentInClassWithParentsViews">
    <Type Name="StudentInClassWithParentsView">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Race" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Parents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentInStudentGroupWithParentsView" Member="StudentInStudentGroupWithParentsViews">
    <Type Name="StudentInStudentGroupWithParentsView">
      <Column Name="ReportGroupStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Parents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="MessageEntities">
    <Type Name="MessageEntity">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAcknowlegdeRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReplyEnabled" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MessageEntity_MessageReceiverEntity" Member="MessageReceiverEntities" ThisKey="MessageID" OtherKey="MessageID" Type="MessageReceiverEntity" />
    </Type>
  </Table>
  <Table Name="dbo.UserRegistrationCode" Member="UserRegistrationCodeEntities">
    <Type Name="UserRegistrationCodeEntity">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GeneratorUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenerateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailLastSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parent" Member="ParentEntities">
    <Type Name="ParentEntity">
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ParentEntity_ParentMetaEntity" Member="ParentMetaEntities" ThisKey="ParentID" OtherKey="ParentID" Type="ParentMetaEntity" />
      <Association Name="ParentEntity_StudentParentEntity" Member="StudentParentEntities" ThisKey="ParentID" OtherKey="ParentID" Type="StudentParentEntity" />
    </Type>
  </Table>
  <Table Name="dbo.ParentMeta" Member="ParentMetaEntities">
    <Type Name="ParentMetaEntity">
      <Column Name="ParentMetaID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="ParentEntity_ParentMetaEntity" Member="ParentEntity" ThisKey="ParentID" OtherKey="ParentID" Type="ParentEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentParent" Member="StudentParentEntities">
    <Type Name="StudentParentEntity">
      <Column Name="StudentParentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Relationship" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="StudentDataAccess" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ParentEntity_StudentParentEntity" Member="ParentEntity" ThisKey="ParentID" OtherKey="ParentID" Type="ParentEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetClassesWithDetailByStudentID" Method="GetClassesWithDetailByStudentID">
    <Parameter Name="studentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetClassesWithDetailByStudentIDResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Course" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeacherFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeacherLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParentsByStudentID" Method="GetParentsByStudentID">
    <Parameter Name="studentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParentsByStudentIDResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MessageNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentParentListByDistrictID" Method="GetStudentParentListByDistrictID">
    <Parameter Name="districtID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentParentListByDistrictIDResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GradeOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ClassCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstClassName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstParentName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="School" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNotAssignParentsOfStudent" Method="GetNotAssignParentsOfStudent">
    <Parameter Name="studentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetNotAssignParentsOfStudentResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MessageNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInboxMessageForParent" Method="GetInboxMessageForParent">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchValue" Parameter="searchValue" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="GetInboxMessageForParentResult">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageNoUnread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Acknow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Replies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageNoInThread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInboxMessageOfMainMessage" Method="GetInboxMessageOfMainMessage">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MessageID" Parameter="messageID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetInboxMessageOfMainMessageResult">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Recipients" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageNoUnread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Acknow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Replies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageNoInThread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInboxMessageForStaff" Method="GetInboxMessageForStaff">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchValue" Parameter="searchValue" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="GetInboxMessageForStaffResult">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Recipients" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageNoUnread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Acknow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Replies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageNoInThread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetMainMessageDetail" Method="GetMainMessageDetail">
    <Parameter Name="MessageRef" Parameter="messageRef" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetMainMessageDetailResult">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessateType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRead" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAcknowlegdeRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Recipients" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteSubThreadMessage" Method="DeleteSubThreadMessage">
    <Parameter Name="MessageRef" Parameter="messageRef" Type="System.Int32" DbType="Int" />
    <Parameter Name="SenderID" Parameter="senderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceiverID" Parameter="receiverID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteMainMessage" Method="DeleteMainMessage">
    <Parameter Name="MessageID" Parameter="messageID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateMessageThreadAsRead" Method="UpdateMessageThreadAsRead">
    <Parameter Name="MessageRef" Parameter="messageRef" Type="System.Int32" DbType="Int" />
    <Parameter Name="SenderID" Parameter="senderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceiverID" Parameter="receiverID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStudentInStudentGroupWithParentForDistrictPublisher" Method="GetStudentInStudentGroupWithParentForDistrictPublisher">
    <Parameter Name="GroupID" Parameter="groupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentInStudentGroupWithParentForDistrictPublisherResult">
      <Column Name="ReportGroupStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Parents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentInStudentGroupWithParentForTeacher" Method="GetStudentInStudentGroupWithParentForTeacher">
    <Parameter Name="GroupID" Parameter="groupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentInStudentGroupWithParentForTeacherResult">
      <Column Name="ReportGroupStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Parents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentInStudentGroupWithParentForSchoolAdmin" Method="GetStudentInStudentGroupWithParentForSchoolAdmin">
    <Parameter Name="GroupID" Parameter="groupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolAdminId" Parameter="schoolAdminId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentInStudentGroupWithParentForSchoolAdminResult">
      <Column Name="ReportGroupStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Parents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSubThreadMessageDetail" Method="GetSubThreadMessageDetail">
    <Parameter Name="MessageRef" Parameter="messageRef" Type="System.Int32" DbType="Int" />
    <Parameter Name="SenderID" Parameter="senderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReceiverID" Parameter="receiverID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSubThreadMessageDetailResult">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRead" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAcknowlegdeRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReplyEnabled" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParentByRegistrationCode" Method="GetParentByRegistrationCode">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParentByRegistrationCodeResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentsByParentID" Method="GetStudentsByParentID">
    <Parameter Name="parentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsByParentIDResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StudentParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentByNavigatorReportAndParent" Method="GetStudentByNavigatorReportAndParent">
    <Parameter Name="NavigatorReportId" Parameter="navigatorReportId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentId" Parameter="parentId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentByNavigatorReportAndParentResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentFirtNameByParentID" Method="GetStudentFirtNameByParentID">
    <Parameter Name="ParentUserId" Parameter="parentUserId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentFirtNameByParentIDResult">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParentsInformationForDistributeRegistrationCode" Method="GetParentsInformationForDistributeRegistrationCode">
    <Parameter Name="ParentUserId" Parameter="parentUserId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParentsInformationForDistributeRegistrationCodeResult">
      <Column Name="StudentFirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StudentLastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StudentFullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StudentCurrentSchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserFirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAccessibleParentUserIds" Method="GetAccessibleParentUserIds">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAccessibleParentUserIdsResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ManageParentGetChildrenList" Method="ManageParentGetChildrenList">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentUserId" Parameter="parentUserId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SSearch" Parameter="sSearch" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="ForcedStudentIds" Parameter="forcedStudentIds" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Skip" Parameter="skip" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="ManageParentGetChildrenListResult">
      <Column Name="TotalRecord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentFullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Relationship" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StudentDataAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParentList" Method="GetParentList">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentName" Parameter="parentName" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="StudentName" Parameter="studentName" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ShowInactiveParent" Parameter="showInactiveParent" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SSearch" Parameter="sSearch" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="Skip" Parameter="skip" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="LoginTimeFrame" Parameter="loginTimeFrame" Type="System.Int32" DbType="Int" />
    <Parameter Name="HasRegistrationCode" Parameter="hasRegistrationCode" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DateTimeUTC" Parameter="dateTimeUTC" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetParentListResult">
      <Column Name="TotalRecord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentFullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolNames" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TheUserLogedIn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailLastSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>