<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="RestrictionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Display" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Role_XLITestRestrictionModuleRole" Member="XLITestRestrictionModuleRoles" ThisKey="RoleID" OtherKey="RoleID" Type="XLITestRestrictionModuleRole" />
    </Type>
  </Table>
  <Table Name="dbo.XLITestRestrictionModule" Member="XLITestRestrictionModules">
    <Type Name="XLITestRestrictionModule">
      <Column Name="XLITestRestrictionModuleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="XLITestRestrictionModule_XLITestRestrictionModuleRole" Member="XLITestRestrictionModuleRoles" ThisKey="XLITestRestrictionModuleID" OtherKey="XLITestRestrictionModuleID" Type="XLITestRestrictionModuleRole" />
    </Type>
  </Table>
  <Table Name="dbo.XLITestRestrictionModuleRole" Member="XLITestRestrictionModuleRoles">
    <Type Name="XLITestRestrictionModuleRole">
      <Column Name="XLITestRestrictionModuleRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PublishedLevelName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublishedLevelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XLITestRestrictionModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RestrictedObjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RestrictedObjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_XLITestRestrictionModuleRole" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
      <Association Name="XLITestRestrictionModule_XLITestRestrictionModuleRole" Member="XLITestRestrictionModule" ThisKey="XLITestRestrictionModuleID" OtherKey="XLITestRestrictionModuleID" Type="XLITestRestrictionModule" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetTestRestriction" Method="GetTestRestriction">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CategoryIds" Parameter="categoryIds" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="GradeIDs" Parameter="gradeIDs" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="SubjectIDs" Parameter="subjectIDs" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="StartRow" Parameter="startRow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SortColumn" Parameter="sortColumn" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GetTestRestrictionResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherRestriction" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolAdminRestriction" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolAdminRestrictionContent" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherRestrictionContent" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherRestrictionDisplay" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolAdminRestrictionDisplay" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCateSubjectGradeByDistrict" Method="GetCateSubjectGradeByDistrict">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCateSubjectGradeByDistrictResult">
      <Column Name="Kind" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>
