<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="SectionBranchingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString29" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VirtualSectionBranching" Member="VirtualSectionBranchingEntities">
    <Type Name="VirtualSectionBranchingEntity">
      <Column Name="VirtualSectionBranchingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestletPath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LowScore" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="HighScore" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TargetVirtualSectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsBranchBySectionScore" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>