#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Data.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdminReportingVNS")]
	public partial class SectionBranchingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVirtualSectionBranchingEntity(VirtualSectionBranchingEntity instance);
    partial void UpdateVirtualSectionBranchingEntity(VirtualSectionBranchingEntity instance);
    partial void DeleteVirtualSectionBranchingEntity(VirtualSectionBranchingEntity instance);
    #endregion		
		
		
		public SectionBranchingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SectionBranchingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SectionBranchingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SectionBranchingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VirtualSectionBranchingEntity> VirtualSectionBranchingEntities
		{
			get
			{
				return this.GetTable<VirtualSectionBranchingEntity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VirtualSectionBranching")]
	public partial class VirtualSectionBranchingEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VirtualSectionBranchingID;
		
		private System.Nullable<int> _VirtualTestID;
		
		private string _TestletPath;
		
		private System.Nullable<decimal> _LowScore;
		
		private System.Nullable<decimal> _HighScore;
		
		private System.Nullable<int> _TargetVirtualSectionID;
		
		private System.Nullable<int> _CreatedUserID;
		
		private System.Nullable<System.DateTime> _CreatedDateTime;
		
		private System.Nullable<bool> _IsBranchBySectionScore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVirtualSectionBranchingIDChanging(int value);
    partial void OnVirtualSectionBranchingIDChanged();
    partial void OnVirtualTestIDChanging(System.Nullable<int> value);
    partial void OnVirtualTestIDChanged();
    partial void OnTestletPathChanging(string value);
    partial void OnTestletPathChanged();
    partial void OnLowScoreChanging(System.Nullable<decimal> value);
    partial void OnLowScoreChanged();
    partial void OnHighScoreChanging(System.Nullable<decimal> value);
    partial void OnHighScoreChanged();
    partial void OnTargetVirtualSectionIDChanging(System.Nullable<int> value);
    partial void OnTargetVirtualSectionIDChanged();
    partial void OnCreatedUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedUserIDChanged();
    partial void OnCreatedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateTimeChanged();
    partial void OnIsBranchBySectionScoreChanging(System.Nullable<bool> value);
    partial void OnIsBranchBySectionScoreChanged();
    #endregion
		
		public VirtualSectionBranchingEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualSectionBranchingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VirtualSectionBranchingID
		{
			get
			{
				return this._VirtualSectionBranchingID;
			}
			set
			{
				if ((this._VirtualSectionBranchingID != value))
				{
					this.OnVirtualSectionBranchingIDChanging(value);
					this.SendPropertyChanging();
					this._VirtualSectionBranchingID = value;
					this.SendPropertyChanged("VirtualSectionBranchingID");
					this.OnVirtualSectionBranchingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualTestID", DbType="Int")]
		public System.Nullable<int> VirtualTestID
		{
			get
			{
				return this._VirtualTestID;
			}
			set
			{
				if ((this._VirtualTestID != value))
				{
					this.OnVirtualTestIDChanging(value);
					this.SendPropertyChanging();
					this._VirtualTestID = value;
					this.SendPropertyChanged("VirtualTestID");
					this.OnVirtualTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestletPath", DbType="VarChar(MAX)")]
		public string TestletPath
		{
			get
			{
				return this._TestletPath;
			}
			set
			{
				if ((this._TestletPath != value))
				{
					this.OnTestletPathChanging(value);
					this.SendPropertyChanging();
					this._TestletPath = value;
					this.SendPropertyChanged("TestletPath");
					this.OnTestletPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowScore", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> LowScore
		{
			get
			{
				return this._LowScore;
			}
			set
			{
				if ((this._LowScore != value))
				{
					this.OnLowScoreChanging(value);
					this.SendPropertyChanging();
					this._LowScore = value;
					this.SendPropertyChanged("LowScore");
					this.OnLowScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighScore", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> HighScore
		{
			get
			{
				return this._HighScore;
			}
			set
			{
				if ((this._HighScore != value))
				{
					this.OnHighScoreChanging(value);
					this.SendPropertyChanging();
					this._HighScore = value;
					this.SendPropertyChanged("HighScore");
					this.OnHighScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetVirtualSectionID", DbType="Int")]
		public System.Nullable<int> TargetVirtualSectionID
		{
			get
			{
				return this._TargetVirtualSectionID;
			}
			set
			{
				if ((this._TargetVirtualSectionID != value))
				{
					this.OnTargetVirtualSectionIDChanging(value);
					this.SendPropertyChanging();
					this._TargetVirtualSectionID = value;
					this.SendPropertyChanged("TargetVirtualSectionID");
					this.OnTargetVirtualSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUserID", DbType="Int")]
		public System.Nullable<int> CreatedUserID
		{
			get
			{
				return this._CreatedUserID;
			}
			set
			{
				if ((this._CreatedUserID != value))
				{
					this.OnCreatedUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedUserID = value;
					this.SendPropertyChanged("CreatedUserID");
					this.OnCreatedUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDateTime
		{
			get
			{
				return this._CreatedDateTime;
			}
			set
			{
				if ((this._CreatedDateTime != value))
				{
					this.OnCreatedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreatedDateTime = value;
					this.SendPropertyChanged("CreatedDateTime");
					this.OnCreatedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBranchBySectionScore", DbType="Bit")]
		public System.Nullable<bool> IsBranchBySectionScore
		{
			get
			{
				return this._IsBranchBySectionScore;
			}
			set
			{
				if ((this._IsBranchBySectionScore != value))
				{
					this.OnIsBranchBySectionScoreChanging(value);
					this.SendPropertyChanging();
					this._IsBranchBySectionScore = value;
					this.SendPropertyChanged("IsBranchBySectionScore");
					this.OnIsBranchBySectionScoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
