<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="SGODataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.252.36.127;Persist Security Info=True;User ID=DevblockDev" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SGOStudentFilter" Member="SGOStudentFilterEntities" AccessModifier="Internal">
    <Type Name="SGOStudentFilterEntity" AccessModifier="Internal">
      <Column Name="SGOStudentFilterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SGOEntity_SGOStudentFilterEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGODataPointFilter" Member="SGODataPointFilterEntities" AccessModifier="Internal">
    <Type Name="SGODataPointFilterEntity" AccessModifier="Internal">
      <Column Name="SGODataPointFilterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SGODataPointEntity_SGODataPointFilterEntity" Member="SGODataPointEntity" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOMilestone" Member="SGOMilestoneEntities" AccessModifier="Internal">
    <Type Name="SGOMilestoneEntity" AccessModifier="Internal">
      <Column Name="SGOMilestoneID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MilestoneDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SGOEntity_SGOMilestoneEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOStudentDataPoint" Member="SGOStudentDataPointEntities" AccessModifier="Internal">
    <Type Name="SGOStudentDataPointEntity" AccessModifier="Internal">
      <Column Name="SGOStudentDataPointID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SGOStudentDataPointEntity_SGOStudentDataPointBandEntity" Member="SGOStudentDataPointBandEntities" ThisKey="SGOStudentDataPointID" OtherKey="SGOStudentDataPointID" Type="SGOStudentDataPointBandEntity" />
      <Association Name="SGODataPointEntity_SGOStudentDataPointEntity" Member="SGODataPointEntity" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointEntity" IsForeignKey="true" />
      <Association Name="SGOStudentEntity_SGOStudentDataPointEntity" Member="SGOStudentEntity" ThisKey="SGOStudentID" OtherKey="SGOStudentID" Type="SGOStudentEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGODataPointBand" Member="SGODataPointBandEntities" AccessModifier="Internal">
    <Type Name="SGODataPointBandEntity" AccessModifier="Internal">
      <Column Name="SGODataPointBandID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LowValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="HighValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="SGODataPointBandEntity_SGOStudentDataPointBandEntity" Member="SGOStudentDataPointBandEntities" ThisKey="SGODataPointBandID" OtherKey="SGODataPointBandID" Type="SGOStudentDataPointBandEntity" />
      <Association Name="SGODataPointEntity_SGODataPointBandEntity" Member="SGODataPointEntity" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOStudentDataPointBand" Member="SGOStudentDataPointBandEntities" AccessModifier="Internal">
    <Type Name="SGOStudentDataPointBandEntity" AccessModifier="Internal">
      <Column Name="SGOStudentDataPointBandID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGOStudentDataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGODataPointBandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SGODataPointBandEntity_SGOStudentDataPointBandEntity" Member="SGODataPointBandEntity" ThisKey="SGODataPointBandID" OtherKey="SGODataPointBandID" Type="SGODataPointBandEntity" IsForeignKey="true" />
      <Association Name="SGOStudentDataPointEntity_SGOStudentDataPointBandEntity" Member="SGOStudentDataPointEntity" ThisKey="SGOStudentDataPointID" OtherKey="SGOStudentDataPointID" Type="SGOStudentDataPointEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOStudentTestDataView" Member="SGOStudentTestDataViews" AccessModifier="Internal">
    <Type Name="SGOStudentTestDataView" AccessModifier="Internal">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GradeOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AchievementLevelSettingName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VirtualTestSourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SGOActionType" Member="SGOActionTypeEntities" AccessModifier="Internal">
    <Type Name="SGOActionTypeEntity" AccessModifier="Internal">
      <Column Name="SGOActionTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SGOAuditTrail" Member="SGOAuditTrailEntities" AccessModifier="Internal">
    <Type Name="SGOAuditTrailEntity" AccessModifier="Internal">
      <Column Name="SGOAuditTrailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChagedByUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOActionTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActionDetail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="SGOEntity_SGOAuditTrailEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOAttainmentGoal" Member="SGOAttainmentGoalEntities" AccessModifier="Internal">
    <Type Name="SGOAttainmentGoalEntity" AccessModifier="Internal">
      <Column Name="SGOAttainmentGoalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ComparisonType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultGoal" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="SGOAttainmentGoalEntity_SGOAttainmentGroupEntity" Member="SGOAttainmentGroupEntities" ThisKey="SGOAttainmentGoalID" OtherKey="SGOAttainmentGoalID" Type="SGOAttainmentGroupEntity" />
      <Association Name="SGOEntity_SGOAttainmentGoalEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGODataPoint" Member="SGODataPointEntities" AccessModifier="Internal">
    <Type Name="SGODataPointEntity" AccessModifier="Internal">
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachScoreUrl" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalPoints" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RationaleGuidance" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ScoreType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImprovementBasedDataPoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SGODataPointEntity_SGODataPointFilterEntity" Member="SGODataPointFilterEntities" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointFilterEntity" />
      <Association Name="SGODataPointEntity_SGOStudentDataPointEntity" Member="SGOStudentDataPointEntities" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGOStudentDataPointEntity" />
      <Association Name="SGODataPointEntity_SGODataPointBandEntity" Member="SGODataPointBandEntities" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointBandEntity" />
      <Association Name="SGODataPointEntity_SGODataPointClusterScoreEntity" Member="SGODataPointClusterScoreEntities" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointClusterScoreEntity" />
      <Association Name="SGOEntity_SGODataPointEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTest_VirtualTestCustomScore" Member="VirtualTest_VirtualTestCustomScoreEntities" AccessModifier="Internal">
    <Type Name="VirtualTest_VirtualTestCustomScoreEntity" AccessModifier="Internal">
      <Column Name="VirtualTest_VirtualTestCustomScore" Member="VirtualTest_VirtualTestCustomScore1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SGOStudent" Member="SGOStudentEntities" AccessModifier="Internal">
    <Type Name="SGOStudentEntity" AccessModifier="Internal">
      <Column Name="SGOStudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AchievedTarget" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SGOStudentEntity_SGOStudentDataPointEntity" Member="SGOStudentDataPointEntities" ThisKey="SGOStudentID" OtherKey="SGOStudentID" Type="SGOStudentDataPointEntity" />
      <Association Name="SGOGroupEntity_SGOStudentEntity" Member="SGOGroupEntity" ThisKey="SGOGroupID" OtherKey="SGOGroupID" Type="SGOGroupEntity" IsForeignKey="true" />
      <Association Name="SGOEntity_SGOStudentEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOGroup" Member="SGOGroupEntities" AccessModifier="Internal">
    <Type Name="SGOGroupEntity" AccessModifier="Internal">
      <Column Name="SGOGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TargetScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PercentStudentAtTargetScore" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="TeacherSGOScore" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="TargetScoreCustom" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TeacherSGOScoreCustom" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="SGOGroupEntity_SGOStudentEntity" Member="SGOStudentEntities" ThisKey="SGOGroupID" OtherKey="SGOGroupID" Type="SGOStudentEntity" />
      <Association Name="SGOGroupEntity_SGOAttainmentGroupEntity" Member="SGOAttainmentGroupEntities" ThisKey="SGOGroupID" OtherKey="SGOGroupID" Type="SGOAttainmentGroupEntity" />
      <Association Name="SGOEntity_SGOGroupEntity" Member="SGOEntity" ThisKey="SGOID" OtherKey="SGOID" Type="SGOEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGOAttainmentGroup" Member="SGOAttainmentGroupEntities" AccessModifier="Internal">
    <Type Name="SGOAttainmentGroupEntity" AccessModifier="Internal">
      <Column Name="SGOAttainmentGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GoalValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SGOGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOAttainmentGoalID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoalValueCustom" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="SGOAttainmentGoalEntity_SGOAttainmentGroupEntity" Member="SGOAttainmentGoalEntity" ThisKey="SGOAttainmentGoalID" OtherKey="SGOAttainmentGoalID" Type="SGOAttainmentGoalEntity" IsForeignKey="true" />
      <Association Name="SGOGroupEntity_SGOAttainmentGroupEntity" Member="SGOGroupEntity" ThisKey="SGOGroupID" OtherKey="SGOGroupID" Type="SGOGroupEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SGO" Member="SGOEntities" AccessModifier="Internal">
    <Type Name="SGOEntity" AccessModifier="Internal">
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TargetScoreType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApproverUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SGOStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SchoolIDs" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GradeIDs" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ClassIDs" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreviousVersionSGOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsArchive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Feedback" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AdminComment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TeacherComment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EducatorComment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GenerateResultsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttachUnstructuredScoringUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RationaleUnstructuredScoring" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AttachUnstructuredProgressUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TotalTeacherSGOScoreCustom" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PreparationApprovedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SGONote" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="SGOEntity_SGOStudentFilterEntity" Member="SGOStudentFilterEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGOStudentFilterEntity" />
      <Association Name="SGOEntity_SGOMilestoneEntity" Member="SGOMilestoneEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGOMilestoneEntity" />
      <Association Name="SGOEntity_SGOAuditTrailEntity" Member="SGOAuditTrailEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGOAuditTrailEntity" />
      <Association Name="SGOEntity_SGOAttainmentGoalEntity" Member="SGOAttainmentGoalEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGOAttainmentGoalEntity" />
      <Association Name="SGOEntity_SGODataPointEntity" Member="SGODataPointEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGODataPointEntity" />
      <Association Name="SGOEntity_SGOStudentEntity" Member="SGOStudentEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGOStudentEntity" />
      <Association Name="SGOEntity_SGOGroupEntity" Member="SGOGroupEntities" ThisKey="SGOID" OtherKey="SGOID" Type="SGOGroupEntity" />
    </Type>
  </Table>
  <Table Name="dbo.SGODataPointClusterScore" Member="SGODataPointClusterScoreEntities" AccessModifier="Internal">
    <Type Name="SGODataPointClusterScoreEntity" AccessModifier="Internal">
      <Column Name="SGODataPointClusterScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestResultSubScoreName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomSubScoreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SGODataPointEntity_SGODataPointClusterScoreEntity" Member="SGODataPointEntity" ThisKey="SGODataPointID" OtherKey="SGODataPointID" Type="SGODataPointEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestCustomScore" Member="VirtualTestCustomScoreEntities">
    <Type Name="VirtualTestCustomScoreEntity">
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsePercentile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseAchievementLevel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScaledScoreMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScaledScoreMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseCustomN_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomN_1_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_2_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_3_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomN_4_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_1_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_2_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_1_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomA_2_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UseCustomA_3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA_4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomA_3_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_4_Label" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CustomA_3_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomA_4_ValueList" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankLabel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestScoreMethodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSubTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomN_1_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_2_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_3_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomN_4_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_1_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_2_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_3_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomA_4_ConversionSetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthorUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UseArtifact" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseNote" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMultiDate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseIndex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseGradeLevelEquiv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DataSetOriginID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.GetStateStandardsForSGO" Method="GetStateStandardsForSGO">
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Subject" Parameter="subject" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Grade" Parameter="grade" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestId" Parameter="virtualTestId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStateStandardsForSGOResult">
      <Column Name="MasterStandardID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LowGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HighGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Children" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="GUID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentGUID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetAccessVirtualTests" Method="SGOGetAccessVirtualTests">
    <Parameter Name="SubjectId" Parameter="subjectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeId" Parameter="gradeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleId" Parameter="userRoleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetAccessVirtualTestsResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetTestResultSubScoreNameOfVirtualTest" Method="SGOGetTestResultSubScoreNameOfVirtualTest">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetTestResultSubScoreNameOfVirtualTestResult">
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGODeleteSGOGroupBySGOIDWithOut9899" Method="SGODeleteSGOGroupBySGOIDWithOut9899">
    <Parameter Name="SGOId" Parameter="sGOId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGORemoveDataPointRelevantData" Method="SGORemoveDataPointRelevantData">
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOSaveStudentDataPointFromVirtualTest" Method="SGOSaveStudentDataPointFromVirtualTest">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOGetStudentSelectedBySGOID" Method="SGOGetStudentSelectedBySGOID">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentSelectedBySGOIDResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetStudentScorePreAssessmentExternal" Method="SGOGetStudentScorePreAssessmentExternal">
    <Parameter Name="dataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentScorePreAssessmentExternalResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOSaveStudent" Method="SGOSaveStudent">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentDataPointXML" Parameter="studentDataPointXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOMoveStudentHasNoGroupToDefaultGroup" Method="SGOMoveStudentHasNoGroupToDefaultGroup">
    <Parameter Name="sgoID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOUpdateStudentDataPointRoster" Method="SGOUpdateStudentDataPointRoster">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ResultDate" Parameter="resultDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PointsPossible" Parameter="pointsPossible" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.Int32" DbType="Int" />
    <Parameter Name="ModifiedBy" Parameter="modifiedBy" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentDataPointXML" Parameter="studentDataPointXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOAssignStudentToGroup" Method="SGOAssignStudentToGroup">
    <Parameter Name="sgoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sgoGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="studentIDs" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOAssignStudentToDataPointBand" Method="SGOAssignStudentToDataPointBand">
    <Parameter Name="sgoDataPointBandID" Type="System.Int32" DbType="Int" />
    <Parameter Name="studentIDs" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOSaveStudentPopulate1" Method="SGOSaveStudentPopulate1">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GenderIds" Parameter="genderIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="RaceIds" Parameter="raceIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="ProgramIds" Parameter="programIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="TermsIds" Parameter="termsIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="ClassIds" Parameter="classIds" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOUpdateGroup" Method="SGOUpdateGroup">
    <Parameter Name="sgoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="groupNames" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGODeleteDataPointBand" Method="SGODeleteDataPointBand">
    <Parameter Name="dataPointIDs" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOGetGender" Method="SGOGetGender">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetGenderResult">
      <Column Name="GenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetRace" Method="SGOGetRace">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetRaceResult">
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetProgram" Method="SGOGetProgram">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetProgramResult">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetStudents" Method="SGOGetStudents">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassIds" Parameter="classIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="GenderIds" Parameter="genderIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="RaceIds" Parameter="raceIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="ProgramIds" Parameter="programIds" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="SGOGetStudentsResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOPopulateColumnSchoolIDsAndClassIDsBySGOId" Method="SGOPopulateColumnSchoolIDsAndClassIDsBySGOId">
    <Parameter Name="SgoId" Parameter="sgoId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOGetClasses" Method="SGOGetClasses">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistricttermIds" Parameter="districttermIds" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="SGOGetClassesResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetDistrctTerm" Method="SGOGetDistrctTerm">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetDistrctTermResult">
      <Column Name="DistricttermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetCompletedList" Method="SGOGetCompletedList">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetCompletedListResult">
      <Column Name="StepId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetAuditTrailBySGOID" Method="SGOGetAuditTrailBySGOID">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetAuditTrailBySGOIDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceOfData" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOAutoAssignStudentToGroup" Method="SGOAutoAssignStudentToGroup">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IncludeUpdate" Parameter="includeUpdate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ScoreType" Parameter="scoreType" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOAutoAssignStudentToGroupResult">
      <Column Name="SGOStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AveragePercentScore" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MinPercentage" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MaxPercentage" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SGOGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCloneRelatedDataPoint" Method="SGOCloneRelatedDataPoint">
    <Parameter Name="OldDataPointID" Parameter="oldDataPointID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewSGOID" Parameter="newSGOID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOAuthorizeRevision" Method="SGOAuthorizeRevision">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StatusID" Parameter="statusID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOAuthorizeRevisionResult">
      <Column Name="NewSGOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetAdminsOfUser" Method="SGOGetAdminsOfUser">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetAdminsOfUserResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCalculateScoreResult" Method="SGOCalculateScoreResult">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOCalculateScoreResultResult">
      <Column Name="SGOGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PercentStudentAtTargetScore" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="TeacherScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="WeightedScore" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCheckExistTestResultByDataPoint" Method="SGOCheckExistTestResultByDataPoint">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DataPointID" Parameter="dataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOCheckExistTestResultByDataPointResult">
      <Column Name="TotalTestResults" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOPopulateDefaultAttainmentGroup" Method="SGOPopulateDefaultAttainmentGroup">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOGetAllStudentBySGOID" Method="SGOGetAllStudentBySGOID">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetAllStudentBySGOIDResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetDataPointHasNoBand" Method="SGOGetDataPointHasNoBand">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetDataPointHasNoBandResult">
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachScoreUrl" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalPoints" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RationaleGuidance" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ScoreType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImprovementBasedDataPoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOReportGetDataPointFilter" Method="SGOReportGetDataPointFilter">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOReportGetDataPointFilterResult">
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilterName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetVirtualTestCustomScore" Method="SGOGetVirtualTestCustomScore">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestCustomScoreID" Parameter="virtualTestCustomScoreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsTestTaken" Parameter="isTestTaken" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetVirtualTestCustomScoreResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GradeOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOStudentLookup" Method="SGOStudentLookup">
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StateCode" Parameter="stateCode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RaceName" Parameter="raceName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="GenderID" Parameter="genderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="SSearch" Parameter="sSearch" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecords" Parameter="totalRecords" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="SGOStudentLookupResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GradeName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RaceName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GenderCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetExternalVirtualTest" Method="SGOGetExternalVirtualTest">
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="GradeId" Parameter="gradeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetExternalVirtualTestResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGORemoveTemporaryExternalTest" Method="SGORemoveTemporaryExternalTest">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOGetAccessPermission" Method="SGOGetAccessPermission">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetAccessPermissionResult">
      <Column Name="HasAccess" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetListSGO" Method="SGOGetListSGO">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecords" Parameter="totalRecords" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SearchInBox" Parameter="searchInBox" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="IsArchive" Parameter="isArchive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserRoleId" Parameter="userRoleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherID" Parameter="teacherID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReviewerID" Parameter="reviewerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictTermID" Parameter="districtTermID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGOStatusIDs" Parameter="sGOStatusIDs" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="InstructionPeriodFrom" Parameter="instructionPeriodFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="InstructionPeriodTo" Parameter="instructionPeriodTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="SGOGetListSGOResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Teacher" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="GradeIDs" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TotalStudent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EffectiveStatus" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EffectiveStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsArchived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApproverUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApproverName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetFullDataForLogging" Method="SGOGetFullDataForLogging">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetFullDataForLoggingResult">
      <Column Name="TableName" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="XMLContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetStudentDataPoint" Method="SGOGetStudentDataPoint">
    <Parameter Name="SgoID" Parameter="sgoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentDataPointResult">
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SGOStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SGOStudentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOScoringDetail" Method="SGOScoringDetail">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOScoringDetailResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SGOStudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PostScore" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BasedScore" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AchievedScore" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AchievedTarget" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetFinalAdministrativeSignoffSGO" Method="SGOGetFinalAdministrativeSignoffSGO">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstructionPeriodFrom" Parameter="instructionPeriodFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="InstructionPeriodTo" Parameter="instructionPeriodTo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IsArchive" Parameter="isArchive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SGOStatusIDs" Parameter="sGOStatusIDs" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="SGOGetFinalAdministrativeSignoffSGOResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SGOScore" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="FinalSignoffDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SISID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StateID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalTeacherSGOScoreCustom" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TargetScoreType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCheckExistTestResultByDataPointAndVirtualTest" Method="SGOCheckExistTestResultByDataPointAndVirtualTest">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DataPointID" Parameter="dataPointID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTest" Parameter="virtualTest" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOCheckExistTestResultByDataPointAndVirtualTestResult">
      <Column Name="TotalTestResults" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCheckExistTestResultByVirtualTest" Method="SGOCheckExistTestResultByVirtualTest">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTest" Parameter="virtualTest" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOCheckExistTestResultByVirtualTestResult">
      <Column Name="IsPostAssessmentHasResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCheckScoreTestResult" Method="SGOCheckScoreTestResult">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DataPointID" Parameter="dataPointID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTest" Parameter="virtualTest" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOCheckScoreTestResultResult">
      <Column Name="IsPostOrPreAssessmentHaveResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetSGOCustomByID" Method="SGOGetSGOCustomByID">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetSGOCustomByIDResult">
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Teacher" Type="System.String" DbType="VarChar(102)" CanBeNull="true" />
      <Column Name="School" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GradeIDs" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalStudent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EffectiveStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EffectiveStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsArchive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApproverUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApproverName" Type="System.String" DbType="VarChar(102)" CanBeNull="true" />
      <Column Name="Feedback" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EducatorComment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AdminComment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TeacherComment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DistrictTerms" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOSaveStudentPopulate" Method="SGOSaveStudentPopulate">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GenderIds" Parameter="genderIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="RaceIds" Parameter="raceIds" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="ProgramIds" Parameter="programIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="TermsIds" Parameter="termsIds" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="ClassIds" Parameter="classIds" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SGOGetStudentScoreCustomScoreAssessmentLinkIt" Method="SGOGetStudentScoreCustomScoreAssessmentLinkIt">
    <Parameter Name="dataPointID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestCustomSubScoreID" Parameter="virtualTestCustomSubScoreID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentScoreCustomScoreAssessmentLinkItResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreText" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOCheckExistStudentNoScore" Method="SGOCheckExistStudentNoScore">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOCheckExistStudentNoScoreResult">
      <Column Name="IsExistStudentNoScore" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSubjectAndGradeByVirtualTestId" Method="GetSubjectAndGradeByVirtualTestId">
    <Parameter Name="VirtualTestId" Parameter="virtualTestId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSubjectAndGradeByVirtualTestIdResult">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOReportGetSGODataPoint" Method="SGOReportGetSGODataPoint">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOReportGetSGODataPointResult">
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(116)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RationaleGuidance" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImprovementBasedDataPoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VirtualTestId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetStudentTestData" Method="SGOGetStudentTestData">
    <Parameter Name="SGOID" Parameter="sGOID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentTestDataResult">
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="GradeOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="BankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="BankAuthorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataSetCategoryName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="VirtualTestType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestSourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataSetOriginID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetSGODataPointByID" Method="SGOGetSGODataPointByID">
    <Parameter Name="SGODataPointID" Parameter="sGODataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetSGODataPointByIDResult">
      <Column Name="SGODataPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachScoreUrl" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="AttachScoreDownload" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SGOID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalPoints" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevelSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RationaleGuidance" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ScoreType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImprovementBasedDataPoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataSetCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCustomCutScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestCustomScoreId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetStudentScorePreAssessmentLegacy" Method="SGOGetStudentScorePreAssessmentLegacy">
    <Parameter Name="dataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentScorePreAssessmentLegacyResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreIndex" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreText" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetStudentScorePreAssessmentLinkIt" Method="SGOGetStudentScorePreAssessmentLinkIt">
    <Parameter Name="dataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetStudentScorePreAssessmentLinkItResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreIndex" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuestionCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(33,14)" CanBeNull="true" />
      <Column Name="ScoreText" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetScoreToCreateDefaultBandForHistoricalTest" Method="SGOGetScoreToCreateDefaultBandForHistoricalTest">
    <Parameter Name="dataPointID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetScoreToCreateDefaultBandForHistoricalTestResult">
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreIndex" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="valueString" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LabelString" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SGOGetAssessmentScoreType" Method="SGOGetAssessmentScoreType">
    <Parameter Name="VirtualTestID" Parameter="virtualTestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestCustomScoreId" Parameter="virtualTestCustomScoreId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SGOId" Parameter="sGOId" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsPostAssignment" Parameter="isPostAssignment" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ScoreType" Parameter="scoreType" Type="System.Int32" DbType="Int" />
    <ElementType Name="SGOGetAssessmentScoreTypeResult">
      <Column Name="VirtualTestCustomScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsePercentile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseIndex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomN4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseCustomA4" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomN1Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomN2Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomN3Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomN4Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomA1Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomA2Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomA3Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CustomA4Label" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>
