<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="StudentDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Gender" Member="GenderEntities" AccessModifier="Internal">
    <Type Name="GenderEntity" AccessModifier="Internal">
      <Column Name="GenderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Race" Member="RaceEntities" AccessModifier="Internal">
    <Type Name="RaceEntity" AccessModifier="Internal">
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Program" Member="ProgramEntities" AccessModifier="Internal">
    <Type Name="ProgramEntity" AccessModifier="Internal">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ProgramEntity_StudentProgramEntity" Member="StudentProgramEntities" ThisKey="ProgramID" OtherKey="ProgramID" Type="StudentProgramEntity" />
    </Type>
  </Table>
  <Table Name="dbo.StudentProgram" Member="StudentProgramEntities" AccessModifier="Internal">
    <Type Name="StudentProgramEntity" AccessModifier="Internal">
      <Column Name="StudentProgramID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProgramEntity_StudentProgramEntity" Member="ProgramEntity" ThisKey="ProgramID" OtherKey="ProgramID" Type="ProgramEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="StudentEntity_StudentProgramEntity" Member="StudentEntity" ThisKey="StudentID" OtherKey="StudentID" Type="StudentEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentChangedLog" Member="StudentChangedLogEntities" AccessModifier="Internal">
    <Type Name="StudentChangedLogEntity" AccessModifier="Internal">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StudentIDChanged" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentChangedLogEntity_StudentChangedLogValueEntity" Member="StudentChangedLogValueEntities" ThisKey="LogID" OtherKey="LogID" Type="StudentChangedLogValueEntity" />
      <Association Name="StudentEntity_StudentChangedLogEntity" Member="StudentEntity" ThisKey="StudentIDChanged" OtherKey="StudentID" Type="StudentEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentChangedLogValue" Member="StudentChangedLogValueEntities" AccessModifier="Internal">
    <Type Name="StudentChangedLogValueEntity" AccessModifier="Internal">
      <Column Name="LogValueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ValueChanged" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OldValue" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NewValue" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="StudentChangedLogEntity_StudentChangedLogValueEntity" Member="StudentChangedLogEntity" ThisKey="LogID" OtherKey="LogID" Type="StudentChangedLogEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GenderStudent" Member="GenderStudentViews" AccessModifier="Internal">
    <Type Name="GenderStudentView" AccessModifier="Internal">
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClassTestResultList" Member="ClassTestResultListViews" AccessModifier="Internal">
    <Type Name="ClassTestResultListView" AccessModifier="Internal">
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TestCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassDistrictTermView" Member="ClassDistrictTermViews" AccessModifier="Internal">
    <Type Name="ClassDistrictTermView" AccessModifier="Internal">
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictTermId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeacherLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeacherUserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TempSchoolTeacherListView" Member="TempSchoolTeacherListViews" AccessModifier="Internal">
    <Type Name="TempSchoolTeacherListView" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClassSchoolStudentView" Member="ClassSchoolStudentViews" AccessModifier="Internal">
    <Type Name="ClassSchoolStudentView" AccessModifier="Internal">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictTerm" Member="DistrictTermEntities" AccessModifier="Internal">
    <Type Name="DistrictTermEntity" AccessModifier="Internal">
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DistrictTermEntity_ClassEntity" Member="ClassEntities" ThisKey="DistrictTermID" OtherKey="DistrictTermID" Type="ClassEntity" />
    </Type>
  </Table>
  <Table Name="dbo.ClassType" Member="ClassTypeEntities" AccessModifier="Internal">
    <Type Name="ClassTypeEntity" AccessModifier="Internal">
      <Column Name="ClassTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="ClassTypeEntity_ClassEntity" Member="ClassEntities" ThisKey="ClassTypeID" OtherKey="ClassTypeID" Type="ClassEntity" />
    </Type>
  </Table>
  <Table Name="dbo.ClassStudentView" Member="ClassStudentViews" AccessModifier="Internal">
    <Type Name="ClassStudentView" AccessModifier="Internal">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClassUser" Member="ClassUserEntities" AccessModifier="Internal">
    <Type Name="ClassUserEntity" AccessModifier="Internal">
      <Column Name="ClassUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassUserLOEID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ClassUserLOEEntity_ClassUserEntity" Member="ClassUserLOEEntity" ThisKey="ClassUserLOEID" OtherKey="ClassUserLOEID" Type="ClassUserLOEEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassUserLOE" Member="ClassUserLOEEntities" AccessModifier="Internal">
    <Type Name="ClassUserLOEEntity" AccessModifier="Internal">
      <Column Name="ClassUserLOEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="ClassUserLOEEntity_ClassUserEntity" Member="ClassUserEntities" ThisKey="ClassUserLOEID" OtherKey="ClassUserLOEID" Type="ClassUserEntity" />
    </Type>
  </Table>
  <Table Name="dbo.StudentInClassView" Member="StudentInClassViews" AccessModifier="Internal">
    <Type Name="StudentInClassView" AccessModifier="Internal">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Race" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolStudentView" Member="SchoolStudentViews">
    <Type Name="SchoolStudentView">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentGenderGradeView" Member="StudentGenderGradeViews" AccessModifier="Internal">
    <Type Name="StudentGenderGradeView" AccessModifier="Internal">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GenderName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentTeacherView" Member="StudentTeacherViews">
    <Type Name="StudentTeacherView">
      <Column Name="GenderName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolStudentRegistration" Member="SchoolStudentRegistrationEntities">
    <Type Name="SchoolStudentRegistrationEntity">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TempName" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentMeta" Member="StudentMetaEntities">
    <Type Name="StudentMetaEntity">
      <Column Name="StudentMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimingOption" Member="TimingOptionEntities">
    <Type Name="TimingOptionEntity">
      <Column Name="TimingSettingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VirtualTestTiming" Member="VirtualTestTimingEntities">
    <Type Name="VirtualTestTimingEntity">
      <Column Name="VirtualTestTimingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimingOptionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QTIOnlineTestSession" Member="QTIOnlineTestSessionEntities">
    <Type Name="QTIOnlineTestSessionEntity">
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignmentGUID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SessionQuestionOrder" Type="System.String" DbType="VarChar(1500)" CanBeNull="true" />
      <Column Name="TimeOver" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="ClassEntities" AccessModifier="Internal">
    <Type Name="ClassEntity" AccessModifier="Internal">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Period" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ClassEntity_ClassStudentEntity" Member="ClassStudentEntities" ThisKey="ClassID" OtherKey="ClassID" Type="ClassStudentEntity" />
      <Association Name="ClassTypeEntity_ClassEntity" Member="ClassTypeEntity" ThisKey="ClassTypeID" OtherKey="ClassTypeID" Type="ClassTypeEntity" IsForeignKey="true" />
      <Association Name="DistrictTermEntity_ClassEntity" Member="DistrictTermEntity" ThisKey="DistrictTermID" OtherKey="DistrictTermID" Type="DistrictTermEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherSchoolClassView" Member="TeacherSchoolClassViews" AccessModifier="Internal">
    <Type Name="TeacherSchoolClassView" AccessModifier="Internal">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentProgramManageView" Member="StudentProgramManageViews" AccessModifier="Internal">
    <Type Name="StudentProgramManageView" AccessModifier="Internal">
      <Column Name="StudentProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LoginCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dateofbirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrimaryLanguageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Note01" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CurrentGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentProgramView" Member="StudentProgramViews" AccessModifier="Internal">
    <Type Name="StudentProgramView" AccessModifier="Internal">
      <Column Name="StudentProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassStudentCustomView" Member="ClassStudentCustomViews">
    <Type Name="ClassStudentCustomView">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassStudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentFullName" Type="System.String" DbType="VarChar(202) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QTIOnlineTestSessionAnswer" Member="QTIOnlineTestSessionAnswerEntities" AccessModifier="Internal">
    <Type Name="QTIOnlineTestSessionAnswerEntity" AccessModifier="Internal">
      <Column Name="QTIOnlineTestSessionAnswerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerChoice" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Answered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResponseIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AnswerImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HighlightQuestion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HighlightPassage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CrossedAnswer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerTemp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QuestionOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Overridden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="StudentEntities" AccessModifier="Internal">
    <Type Name="StudentEntity" AccessModifier="Internal">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LoginCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dateofbirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrimaryLanguageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Note01" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CurrentGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegistrationCodeEmailLastSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SharedSecret" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="StudentEntity_StudentProgramEntity" Member="StudentProgramEntities" ThisKey="StudentID" OtherKey="StudentID" Type="StudentProgramEntity" />
      <Association Name="StudentEntity_StudentChangedLogEntity" Member="StudentChangedLogEntities" ThisKey="StudentID" OtherKey="StudentIDChanged" Type="StudentChangedLogEntity" />
      <Association Name="StudentEntity_ClassStudentEntity" Member="ClassStudentEntities" ThisKey="StudentID" OtherKey="StudentID" Type="ClassStudentEntity" />
    </Type>
  </Table>
  <Table Name="dbo.ProgramInStudentProgramView" Member="ProgramInStudentProgramViews" AccessModifier="Internal">
    <Type Name="ProgramInStudentProgramView" AccessModifier="Internal">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QTIOnlineTestSessionAnswerSub" Member="QTIOnlineTestSessionAnswerSubEntities" AccessModifier="Internal">
    <Type Name="QTIOnlineTestSessionAnswerSubEntity" AccessModifier="Internal">
      <Column Name="QTIOnlineTestSessionAnswerSubID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionAnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualQuestionSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerChoice" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Answered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResponseIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CrossedAnswer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AnswerTemp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Overridden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassStudent" Member="ClassStudentEntities" AccessModifier="Internal">
    <Type Name="ClassStudentEntity" AccessModifier="Internal">
      <Column Name="ClassStudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Started" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="ClassEntity_ClassStudentEntity" Member="ClassEntity" ThisKey="ClassID" OtherKey="ClassID" Type="ClassEntity" IsForeignKey="true" />
      <Association Name="StudentEntity_ClassStudentEntity" Member="StudentEntity" ThisKey="StudentID" OtherKey="StudentID" Type="StudentEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentGradeHistory" Member="StudentGradeHistoryEntities">
    <Type Name="StudentGradeHistoryEntity">
      <Column Name="StudentGradeHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentUser" Member="StudentUserEntities" AccessModifier="Internal">
    <Type Name="StudentUserEntity" AccessModifier="Internal">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerAttachment" Member="AnswerAttachments">
    <Type Name="AnswerAttachment">
      <Column Name="AnswerAttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FileType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachmentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QTIOnlineTestSessionAnswerAttachment" Member="QTIOnlineTestSessionAnswerAttachments">
    <Type Name="QTIOnlineTestSessionAnswerAttachment">
      <Column Name="QTIOnlineTestSessionAnswerAttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionAnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FileType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachmentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolMeta" Member="SchoolMetaEntities">
    <Type Name="SchoolMetaEntity">
      <Column Name="SchoolMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassListView" Member="ClassListViews">
    <Type Name="ClassListView">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TermStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TermEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrimaryTeacher" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Students" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Teachers" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassType" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.StudentLookupGetAdminSchool" Method="StudentLookupGetAdminSchool">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="StudentLookupGetAdminSchoolResult">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.StudentLookupGetRace" Method="StudentLookupGetRace">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="StudentLookupGetRaceResult">
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetProgramsByDistrictIDToView" Method="GetProgramsByDistrictIDToView">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentDate" Parameter="currentDate" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetProgramsByDistrictIDToViewResult">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteProgramAndAssociationItems" Method="DeleteProgramAndAssociationItems">
    <Parameter Name="ProgramId" Parameter="programId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetActiveStudentsOfProgram" Method="GetActiveStudentsOfProgram">
    <Parameter Name="ProgramId" Parameter="programId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentDate" Parameter="currentDate" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetActiveStudentsOfProgramResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CanReopenCompletedOnlineTestSession" Method="CanReopenCompletedOnlineTestSession">
    <Parameter Name="QTIOnlineTestSessionID" Parameter="qTIOnlineTestSessionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="CanReopenCompletedOnlineTestSessionResult">
      <Column Name="Result" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddManyStudentsToClass" Method="AddManyStudentsToClass">
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentIDList" Parameter="studentIDList" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStudentsAvailableByFilter" Method="GetStudentsAvailableByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProgramIdList" Parameter="programIdList" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="GradeIdList" Parameter="gradeIdList" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ShowInactive" Parameter="showInactive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsAvailableByFilterResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ManageClassGetGradesStudent" Method="ManageClassGetGradesStudent">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="ManageClassGetGradesStudentResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ManageClassGetProgramStudent" Method="ManageClassGetProgramStudent">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="ManageClassGetProgramStudentResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllStudentStartWithCodeByDistrictID" Method="GetAllStudentStartWithCodeByDistrictID">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalCode" Parameter="localCode" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetAllStudentStartWithCodeByDistrictIDResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LoginCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dateofbirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrimaryLanguageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Note01" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CurrentGradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUnassignedStudents" Method="GetUnassignedStudents">
    <Parameter Name="ProgramID" Parameter="programID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentCode" Parameter="studentCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetUnassignedStudentsResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.StudentLookupGetGradesFilter" Method="StudentLookupGetGradesFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="StudentLookupGetGradesFilterResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.StudentLookup" Method="StudentLookup">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StateCode" Parameter="stateCode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RaceName" Parameter="raceName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="GenderID" Parameter="genderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="SSearch" Parameter="sSearch" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="Skip" Parameter="skip" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="FilteredStudentId" Parameter="filteredStudentId" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <ElementType Name="StudentLookupResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GradeName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RaceName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GenderCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationCodeEmailLastSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalRecords" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TheUserLogedIn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SharedSecret" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Classes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HasPassword" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ManageParentGetStudentsAvailableByFilter" Method="ManageParentGetStudentsAvailableByFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProgramIdList" Parameter="programIdList" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="GradeIdList" Parameter="gradeIdList" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ShowInactive" Parameter="showInactive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="ManageParentGetStudentsAvailableByFilterResult">
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSurveyProgramByRole" Method="GetSurveyProgramByRole">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSurveyProgramByRoleResult">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SurveyGetGridPopulationUser" Method="SurveyGetGridPopulationUser">
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleId" Parameter="userRoleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherId" Parameter="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TermId" Parameter="termId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeIds" Parameter="gradeIds" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="ProgramIds" Parameter="programIds" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Roles" Parameter="roles" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SortBy" Parameter="sortBy" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SearchText" Parameter="searchText" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Skip" Parameter="skip" Type="System.Int32" DbType="Int" />
    <Parameter Name="Take" Parameter="take" Type="System.Int32" DbType="Int" />
    <ElementType Name="SurveyGetGridPopulationUserResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRecords" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentUserForStudentLogon" Method="GetStudentUserForStudentLogon">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentUserForStudentLogonResult">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ReopenCompletedOnlineTestSession" Method="ReopenCompletedOnlineTestSession">
    <Parameter Name="QTIOnlineTestSessionID" Parameter="qTIOnlineTestSessionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ImageIndexInComplexXML" Parameter="imageIndexInComplexXML" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <ElementType Name="ReopenCompletedOnlineTestSessionResult">
      <Column Name="VirtualQuestionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResponseIdentifier" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ImageIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_TestResultMeta_GetStudentSession" Method="SP_TestResultMeta_GetStudentSession">
    <Parameter Name="StudentID" Parameter="studentID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_TestResultMeta_GetStudentSessionResult">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Student_GetStudentLoginSlip" Method="SP_Student_GetStudentLoginSlip">
    <Parameter Name="StudentIds" Parameter="studentIds" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="SP_Student_GetStudentLoginSlipResult">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LocalCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="YearLevel" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PassCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Classes" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>