<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="SurveyContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString30" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetSurveyBanksByUserId" Method="GetSurveyBanksByUserId">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="userDistrictID" Type="System.Int32" DbType="Int" />
    <Parameter Name="showArchived" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetSurveyBanksByUserIdResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GradeOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAuthorizedSurveyBanksByUserId" Method="GetAuthorizedSurveyBanksByUserId">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAuthorizedSurveyBanksByUserIdResult">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetReviewSurveys" Method="GetReviewSurveys">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TermId" Parameter="termId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SurveyAssignmentType" Parameter="surveyAssignmentType" Type="System.Int32" DbType="Int" />
    <Parameter Name="SurveyBankId" Parameter="surveyBankId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SurveyId" Parameter="surveyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ShowActiveAssignment" Parameter="showActiveAssignment" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SortBy" Parameter="sortBy" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SearchText" Parameter="searchText" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Skip" Parameter="skip" Type="System.Int32" DbType="Int" />
    <Parameter Name="Take" Parameter="take" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetReviewSurveysResult">
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SurveyAssignmentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberAssignment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MostRecentResponsed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BankId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalRecords" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>