#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Data.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdminReportingVNS")]
	public partial class SurveyContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion		
		
		
		public SurveyContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SurveyContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSurveyBanksByUserId")]
		public ISingleResult<GetSurveyBanksByUserIdResult> GetSurveyBanksByUserId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userRoleID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userDistrictID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> showArchived)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, userRoleID, userDistrictID, showArchived);
			return ((ISingleResult<GetSurveyBanksByUserIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAuthorizedSurveyBanksByUserId")]
		public ISingleResult<GetAuthorizedSurveyBanksByUserIdResult> GetAuthorizedSurveyBanksByUserId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DistrictID", DbType="Int")] System.Nullable<int> districtID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, roleID, districtID);
			return ((ISingleResult<GetAuthorizedSurveyBanksByUserIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetReviewSurveys")]
		public ISingleResult<GetReviewSurveysResult> GetReviewSurveys([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserRoleID", DbType="Int")] System.Nullable<int> userRoleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DistrictId", DbType="Int")] System.Nullable<int> districtId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TermId", DbType="Int")] System.Nullable<int> termId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyAssignmentType", DbType="Int")] System.Nullable<int> surveyAssignmentType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyBankId", DbType="Int")] System.Nullable<int> surveyBankId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SurveyId", DbType="Int")] System.Nullable<int> surveyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowActiveAssignment", DbType="Bit")] System.Nullable<bool> showActiveAssignment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortBy", DbType="NVarChar(100)")] string sortBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchText", DbType="NVarChar(1000)")] string searchText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Skip", DbType="Int")] System.Nullable<int> skip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Take", DbType="Int")] System.Nullable<int> take)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, userRoleID, districtId, termId, surveyAssignmentType, surveyBankId, surveyId, showActiveAssignment, sortBy, searchText, skip, take);
			return ((ISingleResult<GetReviewSurveysResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetSurveyBanksByUserIdResult
	{
		
		private System.Nullable<int> _BankID;
		
		private string _BankName;
		
		private string _Subject;
		
		private string _Grade;
		
		private System.Nullable<int> _GradeOrder;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<bool> _Archived;
		
		public GetSurveyBanksByUserIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankID", DbType="Int")]
		public System.Nullable<int> BankID
		{
			get
			{
				return this._BankID;
			}
			set
			{
				if ((this._BankID != value))
				{
					this._BankID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(150)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="VarChar(100)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(100)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeOrder", DbType="Int")]
		public System.Nullable<int> GradeOrder
		{
			get
			{
				return this._GradeOrder;
			}
			set
			{
				if ((this._GradeOrder != value))
				{
					this._GradeOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this._CreatedByUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archived", DbType="Bit")]
		public System.Nullable<bool> Archived
		{
			get
			{
				return this._Archived;
			}
			set
			{
				if ((this._Archived != value))
				{
					this._Archived = value;
				}
			}
		}
	}
	
	public partial class GetAuthorizedSurveyBanksByUserIdResult
	{
		
		private int _BankID;
		
		private string _BankName;
		
		public GetAuthorizedSurveyBanksByUserIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankID", DbType="Int NOT NULL")]
		public int BankID
		{
			get
			{
				return this._BankID;
			}
			set
			{
				if ((this._BankID != value))
				{
					this._BankID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
	}
	
	public partial class GetReviewSurveysResult
	{
		
		private int _VirtualTestID;
		
		private string _Name;
		
		private string _TermName;
		
		private System.Nullable<int> _SurveyAssignmentType;
		
		private System.Nullable<int> _NumberAssignment;
		
		private System.Nullable<System.DateTime> _MostRecentResponsed;
		
		private int _BankId;
		
		private System.Nullable<int> _DistrictTermID;
		
		private System.Nullable<int> _TotalRecords;
		
		private string _SchoolName;
		
		public GetReviewSurveysResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualTestID", DbType="Int NOT NULL")]
		public int VirtualTestID
		{
			get
			{
				return this._VirtualTestID;
			}
			set
			{
				if ((this._VirtualTestID != value))
				{
					this._VirtualTestID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TermName
		{
			get
			{
				return this._TermName;
			}
			set
			{
				if ((this._TermName != value))
				{
					this._TermName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyAssignmentType", DbType="Int")]
		public System.Nullable<int> SurveyAssignmentType
		{
			get
			{
				return this._SurveyAssignmentType;
			}
			set
			{
				if ((this._SurveyAssignmentType != value))
				{
					this._SurveyAssignmentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberAssignment", DbType="Int")]
		public System.Nullable<int> NumberAssignment
		{
			get
			{
				return this._NumberAssignment;
			}
			set
			{
				if ((this._NumberAssignment != value))
				{
					this._NumberAssignment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MostRecentResponsed", DbType="DateTime")]
		public System.Nullable<System.DateTime> MostRecentResponsed
		{
			get
			{
				return this._MostRecentResponsed;
			}
			set
			{
				if ((this._MostRecentResponsed != value))
				{
					this._MostRecentResponsed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankId", DbType="Int NOT NULL")]
		public int BankId
		{
			get
			{
				return this._BankId;
			}
			set
			{
				if ((this._BankId != value))
				{
					this._BankId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictTermID", DbType="Int")]
		public System.Nullable<int> DistrictTermID
		{
			get
			{
				return this._DistrictTermID;
			}
			set
			{
				if ((this._DistrictTermID != value))
				{
					this._DistrictTermID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalRecords", DbType="Int")]
		public System.Nullable<int> TotalRecords
		{
			get
			{
				return this._TotalRecords;
			}
			set
			{
				if ((this._TotalRecords != value))
				{
					this._TotalRecords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolName", DbType="VarChar(100)")]
		public string SchoolName
		{
			get
			{
				return this._SchoolName;
			}
			set
			{
				if ((this._SchoolName != value))
				{
					this._SchoolName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
