#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Data.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdminReportingLog")]
	public partial class TestResultLogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTestResultSubScoreLogEntity(TestResultSubScoreLogEntity instance);
    partial void UpdateTestResultSubScoreLogEntity(TestResultSubScoreLogEntity instance);
    partial void DeleteTestResultSubScoreLogEntity(TestResultSubScoreLogEntity instance);
    partial void InsertTestResultScoreLogEntity(TestResultScoreLogEntity instance);
    partial void UpdateTestResultScoreLogEntity(TestResultScoreLogEntity instance);
    partial void DeleteTestResultScoreLogEntity(TestResultScoreLogEntity instance);
    partial void InsertTestResultProgramLogEntity(TestResultProgramLogEntity instance);
    partial void UpdateTestResultProgramLogEntity(TestResultProgramLogEntity instance);
    partial void DeleteTestResultProgramLogEntity(TestResultProgramLogEntity instance);
    partial void InsertTestResultLogEntity(TestResultLogEntity instance);
    partial void UpdateTestResultLogEntity(TestResultLogEntity instance);
    partial void DeleteTestResultLogEntity(TestResultLogEntity instance);
    partial void InsertAnswerSubLogEntity(AnswerSubLogEntity instance);
    partial void UpdateAnswerSubLogEntity(AnswerSubLogEntity instance);
    partial void DeleteAnswerSubLogEntity(AnswerSubLogEntity instance);
    partial void InsertAnswerLogEntity(AnswerLogEntity instance);
    partial void UpdateAnswerLogEntity(AnswerLogEntity instance);
    partial void DeleteAnswerLogEntity(AnswerLogEntity instance);
    partial void InsertTestResultAuditEntity(TestResultAuditEntity instance);
    partial void UpdateTestResultAuditEntity(TestResultAuditEntity instance);
    partial void DeleteTestResultAuditEntity(TestResultAuditEntity instance);
    #endregion
		public TestResultLogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestResultLogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestResultLogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestResultLogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TestResultSubScoreLogEntity> TestResultSubScoreLogEntities
		{
			get
			{
				return this.GetTable<TestResultSubScoreLogEntity>();
			}
		}
		
		public System.Data.Linq.Table<TestResultScoreLogEntity> TestResultScoreLogEntities
		{
			get
			{
				return this.GetTable<TestResultScoreLogEntity>();
			}
		}
		
		public System.Data.Linq.Table<TestResultProgramLogEntity> TestResultProgramLogEntities
		{
			get
			{
				return this.GetTable<TestResultProgramLogEntity>();
			}
		}
		
		public System.Data.Linq.Table<TestResultLogEntity> TestResultLogEntities
		{
			get
			{
				return this.GetTable<TestResultLogEntity>();
			}
		}
		
		public System.Data.Linq.Table<AnswerSubLogEntity> AnswerSubLogEntities
		{
			get
			{
				return this.GetTable<AnswerSubLogEntity>();
			}
		}
		
		public System.Data.Linq.Table<AnswerLogEntity> AnswerLogEntities
		{
			get
			{
				return this.GetTable<AnswerLogEntity>();
			}
		}
		
		public System.Data.Linq.Table<TestResultAuditEntity> TestResultAuditEntities
		{
			get
			{
				return this.GetTable<TestResultAuditEntity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestResultSubScoreLog")]
	public partial class TestResultSubScoreLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestResultSubScoreLogID;
		
		private int _TestResultSubScoreID;
		
		private int _TestResultScoreID;
		
		private string _Name;
		
		private System.Nullable<decimal> _ScorePercent;
		
		private System.Nullable<decimal> _ScorePercentage;
		
		private System.Nullable<decimal> _ScoreRaw;
		
		private System.Nullable<decimal> _ScoreScaled;
		
		private System.Nullable<decimal> _ScoreLexile;
		
		private bool _UsePercent;
		
		private bool _UsePercentage;
		
		private bool _UseRaw;
		
		private bool _UseScaled;
		
		private bool _UseLexile;
		
		private System.Nullable<int> _AchievementLevel;
		
		private System.Nullable<int> _PointsPossible;
		
		private bool _UseGradeLevelEquiv;
		
		private System.Nullable<decimal> _ScoreGradeLevelEquiv;
		
		private System.Nullable<bool> _MetStandard;
		
		private System.Nullable<decimal> _ScoreCustomN_1;
		
		private System.Nullable<decimal> _ScoreCustomN_2;
		
		private System.Nullable<decimal> _ScoreCustomN_3;
		
		private System.Nullable<decimal> _ScoreCustomN_4;
		
		private string _ScoreCustomA_1;
		
		private string _ScoreCustomA_2;
		
		private string _ScoreCustomA_3;
		
		private string _ScoreCustomA_4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestResultSubScoreLogIDChanging(int value);
    partial void OnTestResultSubScoreLogIDChanged();
    partial void OnTestResultSubScoreIDChanging(int value);
    partial void OnTestResultSubScoreIDChanged();
    partial void OnTestResultScoreIDChanging(int value);
    partial void OnTestResultScoreIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnScorePercentChanging(System.Nullable<decimal> value);
    partial void OnScorePercentChanged();
    partial void OnScorePercentageChanging(System.Nullable<decimal> value);
    partial void OnScorePercentageChanged();
    partial void OnScoreRawChanging(System.Nullable<decimal> value);
    partial void OnScoreRawChanged();
    partial void OnScoreScaledChanging(System.Nullable<decimal> value);
    partial void OnScoreScaledChanged();
    partial void OnScoreLexileChanging(System.Nullable<decimal> value);
    partial void OnScoreLexileChanged();
    partial void OnUsePercentChanging(bool value);
    partial void OnUsePercentChanged();
    partial void OnUsePercentageChanging(bool value);
    partial void OnUsePercentageChanged();
    partial void OnUseRawChanging(bool value);
    partial void OnUseRawChanged();
    partial void OnUseScaledChanging(bool value);
    partial void OnUseScaledChanged();
    partial void OnUseLexileChanging(bool value);
    partial void OnUseLexileChanged();
    partial void OnAchievementLevelChanging(System.Nullable<int> value);
    partial void OnAchievementLevelChanged();
    partial void OnPointsPossibleChanging(System.Nullable<int> value);
    partial void OnPointsPossibleChanged();
    partial void OnUseGradeLevelEquivChanging(bool value);
    partial void OnUseGradeLevelEquivChanged();
    partial void OnScoreGradeLevelEquivChanging(System.Nullable<decimal> value);
    partial void OnScoreGradeLevelEquivChanged();
    partial void OnMetStandardChanging(System.Nullable<bool> value);
    partial void OnMetStandardChanged();
    partial void OnScoreCustomN_1Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_1Changed();
    partial void OnScoreCustomN_2Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_2Changed();
    partial void OnScoreCustomN_3Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_3Changed();
    partial void OnScoreCustomN_4Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_4Changed();
    partial void OnScoreCustomA_1Changing(string value);
    partial void OnScoreCustomA_1Changed();
    partial void OnScoreCustomA_2Changing(string value);
    partial void OnScoreCustomA_2Changed();
    partial void OnScoreCustomA_3Changing(string value);
    partial void OnScoreCustomA_3Changed();
    partial void OnScoreCustomA_4Changing(string value);
    partial void OnScoreCustomA_4Changed();
    #endregion
		
		public TestResultSubScoreLogEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultSubScoreLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestResultSubScoreLogID
		{
			get
			{
				return this._TestResultSubScoreLogID;
			}
			set
			{
				if ((this._TestResultSubScoreLogID != value))
				{
					this.OnTestResultSubScoreLogIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultSubScoreLogID = value;
					this.SendPropertyChanged("TestResultSubScoreLogID");
					this.OnTestResultSubScoreLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultSubScoreID", DbType="Int NOT NULL")]
		public int TestResultSubScoreID
		{
			get
			{
				return this._TestResultSubScoreID;
			}
			set
			{
				if ((this._TestResultSubScoreID != value))
				{
					this.OnTestResultSubScoreIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultSubScoreID = value;
					this.SendPropertyChanged("TestResultSubScoreID");
					this.OnTestResultSubScoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultScoreID", DbType="Int NOT NULL")]
		public int TestResultScoreID
		{
			get
			{
				return this._TestResultScoreID;
			}
			set
			{
				if ((this._TestResultScoreID != value))
				{
					this.OnTestResultScoreIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultScoreID = value;
					this.SendPropertyChanged("TestResultScoreID");
					this.OnTestResultScoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScorePercent", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScorePercent
		{
			get
			{
				return this._ScorePercent;
			}
			set
			{
				if ((this._ScorePercent != value))
				{
					this.OnScorePercentChanging(value);
					this.SendPropertyChanging();
					this._ScorePercent = value;
					this.SendPropertyChanged("ScorePercent");
					this.OnScorePercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScorePercentage", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScorePercentage
		{
			get
			{
				return this._ScorePercentage;
			}
			set
			{
				if ((this._ScorePercentage != value))
				{
					this.OnScorePercentageChanging(value);
					this.SendPropertyChanging();
					this._ScorePercentage = value;
					this.SendPropertyChanged("ScorePercentage");
					this.OnScorePercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreRaw", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreRaw
		{
			get
			{
				return this._ScoreRaw;
			}
			set
			{
				if ((this._ScoreRaw != value))
				{
					this.OnScoreRawChanging(value);
					this.SendPropertyChanging();
					this._ScoreRaw = value;
					this.SendPropertyChanged("ScoreRaw");
					this.OnScoreRawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreScaled", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreScaled
		{
			get
			{
				return this._ScoreScaled;
			}
			set
			{
				if ((this._ScoreScaled != value))
				{
					this.OnScoreScaledChanging(value);
					this.SendPropertyChanging();
					this._ScoreScaled = value;
					this.SendPropertyChanged("ScoreScaled");
					this.OnScoreScaledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreLexile", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreLexile
		{
			get
			{
				return this._ScoreLexile;
			}
			set
			{
				if ((this._ScoreLexile != value))
				{
					this.OnScoreLexileChanging(value);
					this.SendPropertyChanging();
					this._ScoreLexile = value;
					this.SendPropertyChanged("ScoreLexile");
					this.OnScoreLexileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsePercent", DbType="Bit NOT NULL")]
		public bool UsePercent
		{
			get
			{
				return this._UsePercent;
			}
			set
			{
				if ((this._UsePercent != value))
				{
					this.OnUsePercentChanging(value);
					this.SendPropertyChanging();
					this._UsePercent = value;
					this.SendPropertyChanged("UsePercent");
					this.OnUsePercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsePercentage", DbType="Bit NOT NULL")]
		public bool UsePercentage
		{
			get
			{
				return this._UsePercentage;
			}
			set
			{
				if ((this._UsePercentage != value))
				{
					this.OnUsePercentageChanging(value);
					this.SendPropertyChanging();
					this._UsePercentage = value;
					this.SendPropertyChanged("UsePercentage");
					this.OnUsePercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseRaw", DbType="Bit NOT NULL")]
		public bool UseRaw
		{
			get
			{
				return this._UseRaw;
			}
			set
			{
				if ((this._UseRaw != value))
				{
					this.OnUseRawChanging(value);
					this.SendPropertyChanging();
					this._UseRaw = value;
					this.SendPropertyChanged("UseRaw");
					this.OnUseRawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseScaled", DbType="Bit NOT NULL")]
		public bool UseScaled
		{
			get
			{
				return this._UseScaled;
			}
			set
			{
				if ((this._UseScaled != value))
				{
					this.OnUseScaledChanging(value);
					this.SendPropertyChanging();
					this._UseScaled = value;
					this.SendPropertyChanged("UseScaled");
					this.OnUseScaledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseLexile", DbType="Bit NOT NULL")]
		public bool UseLexile
		{
			get
			{
				return this._UseLexile;
			}
			set
			{
				if ((this._UseLexile != value))
				{
					this.OnUseLexileChanging(value);
					this.SendPropertyChanging();
					this._UseLexile = value;
					this.SendPropertyChanged("UseLexile");
					this.OnUseLexileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AchievementLevel", DbType="Int")]
		public System.Nullable<int> AchievementLevel
		{
			get
			{
				return this._AchievementLevel;
			}
			set
			{
				if ((this._AchievementLevel != value))
				{
					this.OnAchievementLevelChanging(value);
					this.SendPropertyChanging();
					this._AchievementLevel = value;
					this.SendPropertyChanged("AchievementLevel");
					this.OnAchievementLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsPossible", DbType="Int")]
		public System.Nullable<int> PointsPossible
		{
			get
			{
				return this._PointsPossible;
			}
			set
			{
				if ((this._PointsPossible != value))
				{
					this.OnPointsPossibleChanging(value);
					this.SendPropertyChanging();
					this._PointsPossible = value;
					this.SendPropertyChanged("PointsPossible");
					this.OnPointsPossibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseGradeLevelEquiv", DbType="Bit NOT NULL")]
		public bool UseGradeLevelEquiv
		{
			get
			{
				return this._UseGradeLevelEquiv;
			}
			set
			{
				if ((this._UseGradeLevelEquiv != value))
				{
					this.OnUseGradeLevelEquivChanging(value);
					this.SendPropertyChanging();
					this._UseGradeLevelEquiv = value;
					this.SendPropertyChanged("UseGradeLevelEquiv");
					this.OnUseGradeLevelEquivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreGradeLevelEquiv", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreGradeLevelEquiv
		{
			get
			{
				return this._ScoreGradeLevelEquiv;
			}
			set
			{
				if ((this._ScoreGradeLevelEquiv != value))
				{
					this.OnScoreGradeLevelEquivChanging(value);
					this.SendPropertyChanging();
					this._ScoreGradeLevelEquiv = value;
					this.SendPropertyChanged("ScoreGradeLevelEquiv");
					this.OnScoreGradeLevelEquivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetStandard", DbType="Bit")]
		public System.Nullable<bool> MetStandard
		{
			get
			{
				return this._MetStandard;
			}
			set
			{
				if ((this._MetStandard != value))
				{
					this.OnMetStandardChanging(value);
					this.SendPropertyChanging();
					this._MetStandard = value;
					this.SendPropertyChanged("MetStandard");
					this.OnMetStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_1", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreCustomN_1
		{
			get
			{
				return this._ScoreCustomN_1;
			}
			set
			{
				if ((this._ScoreCustomN_1 != value))
				{
					this.OnScoreCustomN_1Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_1 = value;
					this.SendPropertyChanged("ScoreCustomN_1");
					this.OnScoreCustomN_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_2", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreCustomN_2
		{
			get
			{
				return this._ScoreCustomN_2;
			}
			set
			{
				if ((this._ScoreCustomN_2 != value))
				{
					this.OnScoreCustomN_2Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_2 = value;
					this.SendPropertyChanged("ScoreCustomN_2");
					this.OnScoreCustomN_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_3", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreCustomN_3
		{
			get
			{
				return this._ScoreCustomN_3;
			}
			set
			{
				if ((this._ScoreCustomN_3 != value))
				{
					this.OnScoreCustomN_3Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_3 = value;
					this.SendPropertyChanged("ScoreCustomN_3");
					this.OnScoreCustomN_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_4", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreCustomN_4
		{
			get
			{
				return this._ScoreCustomN_4;
			}
			set
			{
				if ((this._ScoreCustomN_4 != value))
				{
					this.OnScoreCustomN_4Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_4 = value;
					this.SendPropertyChanged("ScoreCustomN_4");
					this.OnScoreCustomN_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_1", DbType="VarChar(100)")]
		public string ScoreCustomA_1
		{
			get
			{
				return this._ScoreCustomA_1;
			}
			set
			{
				if ((this._ScoreCustomA_1 != value))
				{
					this.OnScoreCustomA_1Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_1 = value;
					this.SendPropertyChanged("ScoreCustomA_1");
					this.OnScoreCustomA_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_2", DbType="VarChar(100)")]
		public string ScoreCustomA_2
		{
			get
			{
				return this._ScoreCustomA_2;
			}
			set
			{
				if ((this._ScoreCustomA_2 != value))
				{
					this.OnScoreCustomA_2Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_2 = value;
					this.SendPropertyChanged("ScoreCustomA_2");
					this.OnScoreCustomA_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_3", DbType="VarChar(100)")]
		public string ScoreCustomA_3
		{
			get
			{
				return this._ScoreCustomA_3;
			}
			set
			{
				if ((this._ScoreCustomA_3 != value))
				{
					this.OnScoreCustomA_3Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_3 = value;
					this.SendPropertyChanged("ScoreCustomA_3");
					this.OnScoreCustomA_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_4", DbType="VarChar(100)")]
		public string ScoreCustomA_4
		{
			get
			{
				return this._ScoreCustomA_4;
			}
			set
			{
				if ((this._ScoreCustomA_4 != value))
				{
					this.OnScoreCustomA_4Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_4 = value;
					this.SendPropertyChanged("ScoreCustomA_4");
					this.OnScoreCustomA_4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestResultScoreLog")]
	public partial class TestResultScoreLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestResultScoreLogID;
		
		private int _TestResultScoreID;
		
		private int _TestResultID;
		
		private System.Nullable<bool> _TookTest;
		
		private System.Nullable<decimal> _ScorePercent;
		
		private System.Nullable<decimal> _ScorePercentage;
		
		private System.Nullable<decimal> _ScoreRaw;
		
		private System.Nullable<decimal> _ScoreScaled;
		
		private System.Nullable<decimal> _ScoreLexile;
		
		private System.Nullable<decimal> _ScoreIndex;
		
		private bool _UsePercent;
		
		private bool _UsePercentage;
		
		private bool _UseRaw;
		
		private bool _UseScaled;
		
		private System.Nullable<bool> _UseLexile;
		
		private System.Nullable<bool> _UseIndex;
		
		private System.Nullable<int> _AchievementLevel;
		
		private System.Nullable<int> _PointsPossible;
		
		private System.Nullable<bool> _UseGradeLevelEquiv;
		
		private System.Nullable<decimal> _ScoreGradeLevelEquiv;
		
		private string _Name;
		
		private System.Nullable<bool> _MetStandard;
		
		private string _AchieveLevelName;
		
		private System.Nullable<decimal> _ScoreCustomN_1;
		
		private System.Nullable<decimal> _ScoreCustomN_2;
		
		private System.Nullable<decimal> _ScoreCustomN_3;
		
		private System.Nullable<decimal> _ScoreCustomN_4;
		
		private string _ScoreCustomA_1;
		
		private string _ScoreCustomA_2;
		
		private string _ScoreCustomA_3;
		
		private string _ScoreCustomA_4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestResultScoreLogIDChanging(int value);
    partial void OnTestResultScoreLogIDChanged();
    partial void OnTestResultScoreIDChanging(int value);
    partial void OnTestResultScoreIDChanged();
    partial void OnTestResultIDChanging(int value);
    partial void OnTestResultIDChanged();
    partial void OnTookTestChanging(System.Nullable<bool> value);
    partial void OnTookTestChanged();
    partial void OnScorePercentChanging(System.Nullable<decimal> value);
    partial void OnScorePercentChanged();
    partial void OnScorePercentageChanging(System.Nullable<decimal> value);
    partial void OnScorePercentageChanged();
    partial void OnScoreRawChanging(System.Nullable<decimal> value);
    partial void OnScoreRawChanged();
    partial void OnScoreScaledChanging(System.Nullable<decimal> value);
    partial void OnScoreScaledChanged();
    partial void OnScoreLexileChanging(System.Nullable<decimal> value);
    partial void OnScoreLexileChanged();
    partial void OnScoreIndexChanging(System.Nullable<decimal> value);
    partial void OnScoreIndexChanged();
    partial void OnUsePercentChanging(bool value);
    partial void OnUsePercentChanged();
    partial void OnUsePercentageChanging(bool value);
    partial void OnUsePercentageChanged();
    partial void OnUseRawChanging(bool value);
    partial void OnUseRawChanged();
    partial void OnUseScaledChanging(bool value);
    partial void OnUseScaledChanged();
    partial void OnUseLexileChanging(System.Nullable<bool> value);
    partial void OnUseLexileChanged();
    partial void OnUseIndexChanging(System.Nullable<bool> value);
    partial void OnUseIndexChanged();
    partial void OnAchievementLevelChanging(System.Nullable<int> value);
    partial void OnAchievementLevelChanged();
    partial void OnPointsPossibleChanging(System.Nullable<int> value);
    partial void OnPointsPossibleChanged();
    partial void OnUseGradeLevelEquivChanging(System.Nullable<bool> value);
    partial void OnUseGradeLevelEquivChanged();
    partial void OnScoreGradeLevelEquivChanging(System.Nullable<decimal> value);
    partial void OnScoreGradeLevelEquivChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMetStandardChanging(System.Nullable<bool> value);
    partial void OnMetStandardChanged();
    partial void OnAchieveLevelNameChanging(string value);
    partial void OnAchieveLevelNameChanged();
    partial void OnScoreCustomN_1Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_1Changed();
    partial void OnScoreCustomN_2Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_2Changed();
    partial void OnScoreCustomN_3Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_3Changed();
    partial void OnScoreCustomN_4Changing(System.Nullable<decimal> value);
    partial void OnScoreCustomN_4Changed();
    partial void OnScoreCustomA_1Changing(string value);
    partial void OnScoreCustomA_1Changed();
    partial void OnScoreCustomA_2Changing(string value);
    partial void OnScoreCustomA_2Changed();
    partial void OnScoreCustomA_3Changing(string value);
    partial void OnScoreCustomA_3Changed();
    partial void OnScoreCustomA_4Changing(string value);
    partial void OnScoreCustomA_4Changed();
    #endregion
		
		public TestResultScoreLogEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultScoreLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestResultScoreLogID
		{
			get
			{
				return this._TestResultScoreLogID;
			}
			set
			{
				if ((this._TestResultScoreLogID != value))
				{
					this.OnTestResultScoreLogIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultScoreLogID = value;
					this.SendPropertyChanged("TestResultScoreLogID");
					this.OnTestResultScoreLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultScoreID", DbType="Int NOT NULL")]
		public int TestResultScoreID
		{
			get
			{
				return this._TestResultScoreID;
			}
			set
			{
				if ((this._TestResultScoreID != value))
				{
					this.OnTestResultScoreIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultScoreID = value;
					this.SendPropertyChanged("TestResultScoreID");
					this.OnTestResultScoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultID", DbType="Int NOT NULL")]
		public int TestResultID
		{
			get
			{
				return this._TestResultID;
			}
			set
			{
				if ((this._TestResultID != value))
				{
					this.OnTestResultIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultID = value;
					this.SendPropertyChanged("TestResultID");
					this.OnTestResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TookTest", DbType="Bit")]
		public System.Nullable<bool> TookTest
		{
			get
			{
				return this._TookTest;
			}
			set
			{
				if ((this._TookTest != value))
				{
					this.OnTookTestChanging(value);
					this.SendPropertyChanging();
					this._TookTest = value;
					this.SendPropertyChanged("TookTest");
					this.OnTookTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScorePercent", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScorePercent
		{
			get
			{
				return this._ScorePercent;
			}
			set
			{
				if ((this._ScorePercent != value))
				{
					this.OnScorePercentChanging(value);
					this.SendPropertyChanging();
					this._ScorePercent = value;
					this.SendPropertyChanged("ScorePercent");
					this.OnScorePercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScorePercentage", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScorePercentage
		{
			get
			{
				return this._ScorePercentage;
			}
			set
			{
				if ((this._ScorePercentage != value))
				{
					this.OnScorePercentageChanging(value);
					this.SendPropertyChanging();
					this._ScorePercentage = value;
					this.SendPropertyChanged("ScorePercentage");
					this.OnScorePercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreRaw", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreRaw
		{
			get
			{
				return this._ScoreRaw;
			}
			set
			{
				if ((this._ScoreRaw != value))
				{
					this.OnScoreRawChanging(value);
					this.SendPropertyChanging();
					this._ScoreRaw = value;
					this.SendPropertyChanged("ScoreRaw");
					this.OnScoreRawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreScaled", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreScaled
		{
			get
			{
				return this._ScoreScaled;
			}
			set
			{
				if ((this._ScoreScaled != value))
				{
					this.OnScoreScaledChanging(value);
					this.SendPropertyChanging();
					this._ScoreScaled = value;
					this.SendPropertyChanged("ScoreScaled");
					this.OnScoreScaledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreLexile", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreLexile
		{
			get
			{
				return this._ScoreLexile;
			}
			set
			{
				if ((this._ScoreLexile != value))
				{
					this.OnScoreLexileChanging(value);
					this.SendPropertyChanging();
					this._ScoreLexile = value;
					this.SendPropertyChanged("ScoreLexile");
					this.OnScoreLexileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreIndex", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreIndex
		{
			get
			{
				return this._ScoreIndex;
			}
			set
			{
				if ((this._ScoreIndex != value))
				{
					this.OnScoreIndexChanging(value);
					this.SendPropertyChanging();
					this._ScoreIndex = value;
					this.SendPropertyChanged("ScoreIndex");
					this.OnScoreIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsePercent", DbType="Bit NOT NULL")]
		public bool UsePercent
		{
			get
			{
				return this._UsePercent;
			}
			set
			{
				if ((this._UsePercent != value))
				{
					this.OnUsePercentChanging(value);
					this.SendPropertyChanging();
					this._UsePercent = value;
					this.SendPropertyChanged("UsePercent");
					this.OnUsePercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsePercentage", DbType="Bit NOT NULL")]
		public bool UsePercentage
		{
			get
			{
				return this._UsePercentage;
			}
			set
			{
				if ((this._UsePercentage != value))
				{
					this.OnUsePercentageChanging(value);
					this.SendPropertyChanging();
					this._UsePercentage = value;
					this.SendPropertyChanged("UsePercentage");
					this.OnUsePercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseRaw", DbType="Bit NOT NULL")]
		public bool UseRaw
		{
			get
			{
				return this._UseRaw;
			}
			set
			{
				if ((this._UseRaw != value))
				{
					this.OnUseRawChanging(value);
					this.SendPropertyChanging();
					this._UseRaw = value;
					this.SendPropertyChanged("UseRaw");
					this.OnUseRawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseScaled", DbType="Bit NOT NULL")]
		public bool UseScaled
		{
			get
			{
				return this._UseScaled;
			}
			set
			{
				if ((this._UseScaled != value))
				{
					this.OnUseScaledChanging(value);
					this.SendPropertyChanging();
					this._UseScaled = value;
					this.SendPropertyChanged("UseScaled");
					this.OnUseScaledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseLexile", DbType="Bit")]
		public System.Nullable<bool> UseLexile
		{
			get
			{
				return this._UseLexile;
			}
			set
			{
				if ((this._UseLexile != value))
				{
					this.OnUseLexileChanging(value);
					this.SendPropertyChanging();
					this._UseLexile = value;
					this.SendPropertyChanged("UseLexile");
					this.OnUseLexileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseIndex", DbType="Bit")]
		public System.Nullable<bool> UseIndex
		{
			get
			{
				return this._UseIndex;
			}
			set
			{
				if ((this._UseIndex != value))
				{
					this.OnUseIndexChanging(value);
					this.SendPropertyChanging();
					this._UseIndex = value;
					this.SendPropertyChanged("UseIndex");
					this.OnUseIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AchievementLevel", DbType="Int")]
		public System.Nullable<int> AchievementLevel
		{
			get
			{
				return this._AchievementLevel;
			}
			set
			{
				if ((this._AchievementLevel != value))
				{
					this.OnAchievementLevelChanging(value);
					this.SendPropertyChanging();
					this._AchievementLevel = value;
					this.SendPropertyChanged("AchievementLevel");
					this.OnAchievementLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsPossible", DbType="Int")]
		public System.Nullable<int> PointsPossible
		{
			get
			{
				return this._PointsPossible;
			}
			set
			{
				if ((this._PointsPossible != value))
				{
					this.OnPointsPossibleChanging(value);
					this.SendPropertyChanging();
					this._PointsPossible = value;
					this.SendPropertyChanged("PointsPossible");
					this.OnPointsPossibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseGradeLevelEquiv", DbType="Bit")]
		public System.Nullable<bool> UseGradeLevelEquiv
		{
			get
			{
				return this._UseGradeLevelEquiv;
			}
			set
			{
				if ((this._UseGradeLevelEquiv != value))
				{
					this.OnUseGradeLevelEquivChanging(value);
					this.SendPropertyChanging();
					this._UseGradeLevelEquiv = value;
					this.SendPropertyChanged("UseGradeLevelEquiv");
					this.OnUseGradeLevelEquivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreGradeLevelEquiv", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ScoreGradeLevelEquiv
		{
			get
			{
				return this._ScoreGradeLevelEquiv;
			}
			set
			{
				if ((this._ScoreGradeLevelEquiv != value))
				{
					this.OnScoreGradeLevelEquivChanging(value);
					this.SendPropertyChanging();
					this._ScoreGradeLevelEquiv = value;
					this.SendPropertyChanged("ScoreGradeLevelEquiv");
					this.OnScoreGradeLevelEquivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetStandard", DbType="Bit")]
		public System.Nullable<bool> MetStandard
		{
			get
			{
				return this._MetStandard;
			}
			set
			{
				if ((this._MetStandard != value))
				{
					this.OnMetStandardChanging(value);
					this.SendPropertyChanging();
					this._MetStandard = value;
					this.SendPropertyChanged("MetStandard");
					this.OnMetStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AchieveLevelName", DbType="VarChar(50)")]
		public string AchieveLevelName
		{
			get
			{
				return this._AchieveLevelName;
			}
			set
			{
				if ((this._AchieveLevelName != value))
				{
					this.OnAchieveLevelNameChanging(value);
					this.SendPropertyChanging();
					this._AchieveLevelName = value;
					this.SendPropertyChanged("AchieveLevelName");
					this.OnAchieveLevelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ScoreCustomN_1
		{
			get
			{
				return this._ScoreCustomN_1;
			}
			set
			{
				if ((this._ScoreCustomN_1 != value))
				{
					this.OnScoreCustomN_1Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_1 = value;
					this.SendPropertyChanged("ScoreCustomN_1");
					this.OnScoreCustomN_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ScoreCustomN_2
		{
			get
			{
				return this._ScoreCustomN_2;
			}
			set
			{
				if ((this._ScoreCustomN_2 != value))
				{
					this.OnScoreCustomN_2Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_2 = value;
					this.SendPropertyChanged("ScoreCustomN_2");
					this.OnScoreCustomN_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_3", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ScoreCustomN_3
		{
			get
			{
				return this._ScoreCustomN_3;
			}
			set
			{
				if ((this._ScoreCustomN_3 != value))
				{
					this.OnScoreCustomN_3Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_3 = value;
					this.SendPropertyChanged("ScoreCustomN_3");
					this.OnScoreCustomN_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomN_4", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ScoreCustomN_4
		{
			get
			{
				return this._ScoreCustomN_4;
			}
			set
			{
				if ((this._ScoreCustomN_4 != value))
				{
					this.OnScoreCustomN_4Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomN_4 = value;
					this.SendPropertyChanged("ScoreCustomN_4");
					this.OnScoreCustomN_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_1", DbType="VarChar(100)")]
		public string ScoreCustomA_1
		{
			get
			{
				return this._ScoreCustomA_1;
			}
			set
			{
				if ((this._ScoreCustomA_1 != value))
				{
					this.OnScoreCustomA_1Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_1 = value;
					this.SendPropertyChanged("ScoreCustomA_1");
					this.OnScoreCustomA_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_2", DbType="VarChar(100)")]
		public string ScoreCustomA_2
		{
			get
			{
				return this._ScoreCustomA_2;
			}
			set
			{
				if ((this._ScoreCustomA_2 != value))
				{
					this.OnScoreCustomA_2Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_2 = value;
					this.SendPropertyChanged("ScoreCustomA_2");
					this.OnScoreCustomA_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_3", DbType="VarChar(100)")]
		public string ScoreCustomA_3
		{
			get
			{
				return this._ScoreCustomA_3;
			}
			set
			{
				if ((this._ScoreCustomA_3 != value))
				{
					this.OnScoreCustomA_3Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_3 = value;
					this.SendPropertyChanged("ScoreCustomA_3");
					this.OnScoreCustomA_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreCustomA_4", DbType="VarChar(100)")]
		public string ScoreCustomA_4
		{
			get
			{
				return this._ScoreCustomA_4;
			}
			set
			{
				if ((this._ScoreCustomA_4 != value))
				{
					this.OnScoreCustomA_4Changing(value);
					this.SendPropertyChanging();
					this._ScoreCustomA_4 = value;
					this.SendPropertyChanged("ScoreCustomA_4");
					this.OnScoreCustomA_4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestResultProgramLog")]
	public partial class TestResultProgramLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestResultProgramLogID;
		
		private int _TestResultProgramID;
		
		private int _TestResultID;
		
		private int _ProgramID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestResultProgramLogIDChanging(int value);
    partial void OnTestResultProgramLogIDChanged();
    partial void OnTestResultProgramIDChanging(int value);
    partial void OnTestResultProgramIDChanged();
    partial void OnTestResultIDChanging(int value);
    partial void OnTestResultIDChanged();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    #endregion
		
		public TestResultProgramLogEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultProgramLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestResultProgramLogID
		{
			get
			{
				return this._TestResultProgramLogID;
			}
			set
			{
				if ((this._TestResultProgramLogID != value))
				{
					this.OnTestResultProgramLogIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultProgramLogID = value;
					this.SendPropertyChanged("TestResultProgramLogID");
					this.OnTestResultProgramLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultProgramID", DbType="Int NOT NULL")]
		public int TestResultProgramID
		{
			get
			{
				return this._TestResultProgramID;
			}
			set
			{
				if ((this._TestResultProgramID != value))
				{
					this.OnTestResultProgramIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultProgramID = value;
					this.SendPropertyChanged("TestResultProgramID");
					this.OnTestResultProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultID", DbType="Int NOT NULL")]
		public int TestResultID
		{
			get
			{
				return this._TestResultID;
			}
			set
			{
				if ((this._TestResultID != value))
				{
					this.OnTestResultIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultID = value;
					this.SendPropertyChanged("TestResultID");
					this.OnTestResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestResultLog")]
	public partial class TestResultLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestResultLogID;
		
		private int _TestResultID;
		
		private int _VirtualTestID;
		
		private int _StudentID;
		
		private System.Nullable<int> _TeacherID;
		
		private System.Nullable<int> _SchoolID;
		
		private System.DateTime _ResultDate;
		
		private System.DateTime _CreatedDate;
		
		private System.DateTime _UpdatedDate;
		
		private System.Nullable<int> _TermID;
		
		private System.Nullable<int> _ClassID;
		
		private int _GradedByID;
		
		private int _ScoreType;
		
		private System.Nullable<decimal> _ScoreValue;
		
		private string _TRData;
		
		private System.Nullable<int> _SubmitType;
		
		private System.Nullable<int> _DistrictTermID;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<int> _OriginalUserID;
		
		private string _UIN;
		
		private System.Nullable<int> _LegacyBatchID;
		
		private System.Nullable<int> _BubbleSheetID;
		
		private System.Nullable<int> _QTIOnlineTestSessionID;
		
		private int _DistrictID;
		
		private string _DistrictName;
		
		private string _DistrictTermName;
		
		private string _SchoolName;
		
		private string _UserName;
		
		private string _ClassName;
		
		private string _StudentFirst;
		
		private string _StudentLast;
		
		private string _TestName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestResultLogIDChanging(int value);
    partial void OnTestResultLogIDChanged();
    partial void OnTestResultIDChanging(int value);
    partial void OnTestResultIDChanged();
    partial void OnVirtualTestIDChanging(int value);
    partial void OnVirtualTestIDChanged();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnTeacherIDChanging(System.Nullable<int> value);
    partial void OnTeacherIDChanged();
    partial void OnSchoolIDChanging(System.Nullable<int> value);
    partial void OnSchoolIDChanged();
    partial void OnResultDateChanging(System.DateTime value);
    partial void OnResultDateChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnUpdatedDateChanging(System.DateTime value);
    partial void OnUpdatedDateChanged();
    partial void OnTermIDChanging(System.Nullable<int> value);
    partial void OnTermIDChanged();
    partial void OnClassIDChanging(System.Nullable<int> value);
    partial void OnClassIDChanged();
    partial void OnGradedByIDChanging(int value);
    partial void OnGradedByIDChanged();
    partial void OnScoreTypeChanging(int value);
    partial void OnScoreTypeChanged();
    partial void OnScoreValueChanging(System.Nullable<decimal> value);
    partial void OnScoreValueChanged();
    partial void OnTRDataChanging(string value);
    partial void OnTRDataChanged();
    partial void OnSubmitTypeChanging(System.Nullable<int> value);
    partial void OnSubmitTypeChanged();
    partial void OnDistrictTermIDChanging(System.Nullable<int> value);
    partial void OnDistrictTermIDChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnOriginalUserIDChanging(System.Nullable<int> value);
    partial void OnOriginalUserIDChanged();
    partial void OnUINChanging(string value);
    partial void OnUINChanged();
    partial void OnLegacyBatchIDChanging(System.Nullable<int> value);
    partial void OnLegacyBatchIDChanged();
    partial void OnBubbleSheetIDChanging(System.Nullable<int> value);
    partial void OnBubbleSheetIDChanged();
    partial void OnQTIOnlineTestSessionIDChanging(System.Nullable<int> value);
    partial void OnQTIOnlineTestSessionIDChanged();
    partial void OnDistrictIDChanging(int value);
    partial void OnDistrictIDChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    partial void OnDistrictTermNameChanging(string value);
    partial void OnDistrictTermNameChanged();
    partial void OnSchoolNameChanging(string value);
    partial void OnSchoolNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnStudentFirstChanging(string value);
    partial void OnStudentFirstChanged();
    partial void OnStudentLastChanging(string value);
    partial void OnStudentLastChanged();
    partial void OnTestNameChanging(string value);
    partial void OnTestNameChanged();
    #endregion
		
		public TestResultLogEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestResultLogID
		{
			get
			{
				return this._TestResultLogID;
			}
			set
			{
				if ((this._TestResultLogID != value))
				{
					this.OnTestResultLogIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultLogID = value;
					this.SendPropertyChanged("TestResultLogID");
					this.OnTestResultLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultID", DbType="Int NOT NULL")]
		public int TestResultID
		{
			get
			{
				return this._TestResultID;
			}
			set
			{
				if ((this._TestResultID != value))
				{
					this.OnTestResultIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultID = value;
					this.SendPropertyChanged("TestResultID");
					this.OnTestResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualTestID", DbType="Int NOT NULL")]
		public int VirtualTestID
		{
			get
			{
				return this._VirtualTestID;
			}
			set
			{
				if ((this._VirtualTestID != value))
				{
					this.OnVirtualTestIDChanging(value);
					this.SendPropertyChanging();
					this._VirtualTestID = value;
					this.SendPropertyChanged("VirtualTestID");
					this.OnVirtualTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int NOT NULL")]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", DbType="Int")]
		public System.Nullable<int> TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolID", DbType="Int")]
		public System.Nullable<int> SchoolID
		{
			get
			{
				return this._SchoolID;
			}
			set
			{
				if ((this._SchoolID != value))
				{
					this.OnSchoolIDChanging(value);
					this.SendPropertyChanging();
					this._SchoolID = value;
					this.SendPropertyChanged("SchoolID");
					this.OnSchoolIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultDate", DbType="DateTime NOT NULL")]
		public System.DateTime ResultDate
		{
			get
			{
				return this._ResultDate;
			}
			set
			{
				if ((this._ResultDate != value))
				{
					this.OnResultDateChanging(value);
					this.SendPropertyChanging();
					this._ResultDate = value;
					this.SendPropertyChanged("ResultDate");
					this.OnResultDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TermID", DbType="Int")]
		public System.Nullable<int> TermID
		{
			get
			{
				return this._TermID;
			}
			set
			{
				if ((this._TermID != value))
				{
					this.OnTermIDChanging(value);
					this.SendPropertyChanging();
					this._TermID = value;
					this.SendPropertyChanged("TermID");
					this.OnTermIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int")]
		public System.Nullable<int> ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradedByID", DbType="Int NOT NULL")]
		public int GradedByID
		{
			get
			{
				return this._GradedByID;
			}
			set
			{
				if ((this._GradedByID != value))
				{
					this.OnGradedByIDChanging(value);
					this.SendPropertyChanging();
					this._GradedByID = value;
					this.SendPropertyChanged("GradedByID");
					this.OnGradedByIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreType", DbType="Int NOT NULL")]
		public int ScoreType
		{
			get
			{
				return this._ScoreType;
			}
			set
			{
				if ((this._ScoreType != value))
				{
					this.OnScoreTypeChanging(value);
					this.SendPropertyChanging();
					this._ScoreType = value;
					this.SendPropertyChanged("ScoreType");
					this.OnScoreTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScoreValue", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ScoreValue
		{
			get
			{
				return this._ScoreValue;
			}
			set
			{
				if ((this._ScoreValue != value))
				{
					this.OnScoreValueChanging(value);
					this.SendPropertyChanging();
					this._ScoreValue = value;
					this.SendPropertyChanged("ScoreValue");
					this.OnScoreValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRData", DbType="VarChar(4000)")]
		public string TRData
		{
			get
			{
				return this._TRData;
			}
			set
			{
				if ((this._TRData != value))
				{
					this.OnTRDataChanging(value);
					this.SendPropertyChanging();
					this._TRData = value;
					this.SendPropertyChanged("TRData");
					this.OnTRDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitType", DbType="Int")]
		public System.Nullable<int> SubmitType
		{
			get
			{
				return this._SubmitType;
			}
			set
			{
				if ((this._SubmitType != value))
				{
					this.OnSubmitTypeChanging(value);
					this.SendPropertyChanging();
					this._SubmitType = value;
					this.SendPropertyChanged("SubmitType");
					this.OnSubmitTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictTermID", DbType="Int")]
		public System.Nullable<int> DistrictTermID
		{
			get
			{
				return this._DistrictTermID;
			}
			set
			{
				if ((this._DistrictTermID != value))
				{
					this.OnDistrictTermIDChanging(value);
					this.SendPropertyChanging();
					this._DistrictTermID = value;
					this.SendPropertyChanged("DistrictTermID");
					this.OnDistrictTermIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalUserID", DbType="Int")]
		public System.Nullable<int> OriginalUserID
		{
			get
			{
				return this._OriginalUserID;
			}
			set
			{
				if ((this._OriginalUserID != value))
				{
					this.OnOriginalUserIDChanging(value);
					this.SendPropertyChanging();
					this._OriginalUserID = value;
					this.SendPropertyChanged("OriginalUserID");
					this.OnOriginalUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIN", DbType="VarChar(50)")]
		public string UIN
		{
			get
			{
				return this._UIN;
			}
			set
			{
				if ((this._UIN != value))
				{
					this.OnUINChanging(value);
					this.SendPropertyChanging();
					this._UIN = value;
					this.SendPropertyChanged("UIN");
					this.OnUINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyBatchID", DbType="Int")]
		public System.Nullable<int> LegacyBatchID
		{
			get
			{
				return this._LegacyBatchID;
			}
			set
			{
				if ((this._LegacyBatchID != value))
				{
					this.OnLegacyBatchIDChanging(value);
					this.SendPropertyChanging();
					this._LegacyBatchID = value;
					this.SendPropertyChanged("LegacyBatchID");
					this.OnLegacyBatchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BubbleSheetID", DbType="Int")]
		public System.Nullable<int> BubbleSheetID
		{
			get
			{
				return this._BubbleSheetID;
			}
			set
			{
				if ((this._BubbleSheetID != value))
				{
					this.OnBubbleSheetIDChanging(value);
					this.SendPropertyChanging();
					this._BubbleSheetID = value;
					this.SendPropertyChanged("BubbleSheetID");
					this.OnBubbleSheetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTIOnlineTestSessionID", DbType="Int")]
		public System.Nullable<int> QTIOnlineTestSessionID
		{
			get
			{
				return this._QTIOnlineTestSessionID;
			}
			set
			{
				if ((this._QTIOnlineTestSessionID != value))
				{
					this.OnQTIOnlineTestSessionIDChanging(value);
					this.SendPropertyChanging();
					this._QTIOnlineTestSessionID = value;
					this.SendPropertyChanged("QTIOnlineTestSessionID");
					this.OnQTIOnlineTestSessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictID", DbType="Int NOT NULL")]
		public int DistrictID
		{
			get
			{
				return this._DistrictID;
			}
			set
			{
				if ((this._DistrictID != value))
				{
					this.OnDistrictIDChanging(value);
					this.SendPropertyChanging();
					this._DistrictID = value;
					this.SendPropertyChanged("DistrictID");
					this.OnDistrictIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictName", DbType="VarChar(100)")]
		public string DistrictName
		{
			get
			{
				return this._DistrictName;
			}
			set
			{
				if ((this._DistrictName != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictName = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictTermName", DbType="VarChar(100)")]
		public string DistrictTermName
		{
			get
			{
				return this._DistrictTermName;
			}
			set
			{
				if ((this._DistrictTermName != value))
				{
					this.OnDistrictTermNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictTermName = value;
					this.SendPropertyChanged("DistrictTermName");
					this.OnDistrictTermNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolName", DbType="VarChar(100)")]
		public string SchoolName
		{
			get
			{
				return this._SchoolName;
			}
			set
			{
				if ((this._SchoolName != value))
				{
					this.OnSchoolNameChanging(value);
					this.SendPropertyChanging();
					this._SchoolName = value;
					this.SendPropertyChanged("SchoolName");
					this.OnSchoolNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="VarChar(200)")]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentFirst", DbType="VarChar(100)")]
		public string StudentFirst
		{
			get
			{
				return this._StudentFirst;
			}
			set
			{
				if ((this._StudentFirst != value))
				{
					this.OnStudentFirstChanging(value);
					this.SendPropertyChanging();
					this._StudentFirst = value;
					this.SendPropertyChanged("StudentFirst");
					this.OnStudentFirstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentLast", DbType="VarChar(100)")]
		public string StudentLast
		{
			get
			{
				return this._StudentLast;
			}
			set
			{
				if ((this._StudentLast != value))
				{
					this.OnStudentLastChanging(value);
					this.SendPropertyChanging();
					this._StudentLast = value;
					this.SendPropertyChanged("StudentLast");
					this.OnStudentLastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestName", DbType="VarChar(150)")]
		public string TestName
		{
			get
			{
				return this._TestName;
			}
			set
			{
				if ((this._TestName != value))
				{
					this.OnTestNameChanging(value);
					this.SendPropertyChanging();
					this._TestName = value;
					this.SendPropertyChanged("TestName");
					this.OnTestNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnswerSubLog")]
	public partial class AnswerSubLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnswerSubLogID;
		
		private int _AnswerSubID;
		
		private int _AnswerID;
		
		private int _VirtualQuestionSubID;
		
		private int _PointsEarned;
		
		private int _PointsPossible;
		
		private string _AnswerLetter;
		
		private string _AnswerText;
		
		private string _ResponseIdentifier;
		
		private System.Nullable<bool> _Overridden;
		
		private System.Nullable<int> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnswerSubLogIDChanging(int value);
    partial void OnAnswerSubLogIDChanged();
    partial void OnAnswerSubIDChanging(int value);
    partial void OnAnswerSubIDChanged();
    partial void OnAnswerIDChanging(int value);
    partial void OnAnswerIDChanged();
    partial void OnVirtualQuestionSubIDChanging(int value);
    partial void OnVirtualQuestionSubIDChanged();
    partial void OnPointsEarnedChanging(int value);
    partial void OnPointsEarnedChanged();
    partial void OnPointsPossibleChanging(int value);
    partial void OnPointsPossibleChanged();
    partial void OnAnswerLetterChanging(string value);
    partial void OnAnswerLetterChanged();
    partial void OnAnswerTextChanging(string value);
    partial void OnAnswerTextChanged();
    partial void OnResponseIdentifierChanging(string value);
    partial void OnResponseIdentifierChanged();
    partial void OnOverriddenChanging(System.Nullable<bool> value);
    partial void OnOverriddenChanged();
    partial void OnUpdatedByChanging(System.Nullable<int> value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    #endregion
		
		public AnswerSubLogEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerSubLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AnswerSubLogID
		{
			get
			{
				return this._AnswerSubLogID;
			}
			set
			{
				if ((this._AnswerSubLogID != value))
				{
					this.OnAnswerSubLogIDChanging(value);
					this.SendPropertyChanging();
					this._AnswerSubLogID = value;
					this.SendPropertyChanged("AnswerSubLogID");
					this.OnAnswerSubLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerSubID", DbType="Int NOT NULL")]
		public int AnswerSubID
		{
			get
			{
				return this._AnswerSubID;
			}
			set
			{
				if ((this._AnswerSubID != value))
				{
					this.OnAnswerSubIDChanging(value);
					this.SendPropertyChanging();
					this._AnswerSubID = value;
					this.SendPropertyChanged("AnswerSubID");
					this.OnAnswerSubIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerID", DbType="Int NOT NULL")]
		public int AnswerID
		{
			get
			{
				return this._AnswerID;
			}
			set
			{
				if ((this._AnswerID != value))
				{
					this.OnAnswerIDChanging(value);
					this.SendPropertyChanging();
					this._AnswerID = value;
					this.SendPropertyChanged("AnswerID");
					this.OnAnswerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualQuestionSubID", DbType="Int NOT NULL")]
		public int VirtualQuestionSubID
		{
			get
			{
				return this._VirtualQuestionSubID;
			}
			set
			{
				if ((this._VirtualQuestionSubID != value))
				{
					this.OnVirtualQuestionSubIDChanging(value);
					this.SendPropertyChanging();
					this._VirtualQuestionSubID = value;
					this.SendPropertyChanged("VirtualQuestionSubID");
					this.OnVirtualQuestionSubIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsEarned", DbType="Int NOT NULL")]
		public int PointsEarned
		{
			get
			{
				return this._PointsEarned;
			}
			set
			{
				if ((this._PointsEarned != value))
				{
					this.OnPointsEarnedChanging(value);
					this.SendPropertyChanging();
					this._PointsEarned = value;
					this.SendPropertyChanged("PointsEarned");
					this.OnPointsEarnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsPossible", DbType="Int NOT NULL")]
		public int PointsPossible
		{
			get
			{
				return this._PointsPossible;
			}
			set
			{
				if ((this._PointsPossible != value))
				{
					this.OnPointsPossibleChanging(value);
					this.SendPropertyChanging();
					this._PointsPossible = value;
					this.SendPropertyChanged("PointsPossible");
					this.OnPointsPossibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerLetter", DbType="VarChar(200)")]
		public string AnswerLetter
		{
			get
			{
				return this._AnswerLetter;
			}
			set
			{
				if ((this._AnswerLetter != value))
				{
					this.OnAnswerLetterChanging(value);
					this.SendPropertyChanging();
					this._AnswerLetter = value;
					this.SendPropertyChanged("AnswerLetter");
					this.OnAnswerLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerText", DbType="NVarChar(MAX)")]
		public string AnswerText
		{
			get
			{
				return this._AnswerText;
			}
			set
			{
				if ((this._AnswerText != value))
				{
					this.OnAnswerTextChanging(value);
					this.SendPropertyChanging();
					this._AnswerText = value;
					this.SendPropertyChanged("AnswerText");
					this.OnAnswerTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseIdentifier", DbType="VarChar(50)")]
		public string ResponseIdentifier
		{
			get
			{
				return this._ResponseIdentifier;
			}
			set
			{
				if ((this._ResponseIdentifier != value))
				{
					this.OnResponseIdentifierChanging(value);
					this.SendPropertyChanging();
					this._ResponseIdentifier = value;
					this.SendPropertyChanged("ResponseIdentifier");
					this.OnResponseIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Overridden", DbType="Bit")]
		public System.Nullable<bool> Overridden
		{
			get
			{
				return this._Overridden;
			}
			set
			{
				if ((this._Overridden != value))
				{
					this.OnOverriddenChanging(value);
					this.SendPropertyChanging();
					this._Overridden = value;
					this.SendPropertyChanged("Overridden");
					this.OnOverriddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="Int")]
		public System.Nullable<int> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnswerLog")]
	public partial class AnswerLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnswerLogID;
		
		private int _AnswerID;
		
		private int _PointsEarned;
		
		private int _PointsPossible;
		
		private bool _WasAnswered;
		
		private int _TestResultID;
		
		private int _VirtualQuestionID;
		
		private string _AnswerLetter;
		
		private bool _Blocked;
		
		private string _AnswerText;
		
		private string _BubbleSheetErrorType;
		
		private string _ResponseIdentifier;
		
		private string _AnswerImage;
		
		private string _HighlightQuestion;
		
		private string _HighlightPassage;
		
		private System.Nullable<bool> _Overridden;
		
		private System.Nullable<int> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnswerLogIDChanging(int value);
    partial void OnAnswerLogIDChanged();
    partial void OnAnswerIDChanging(int value);
    partial void OnAnswerIDChanged();
    partial void OnPointsEarnedChanging(int value);
    partial void OnPointsEarnedChanged();
    partial void OnPointsPossibleChanging(int value);
    partial void OnPointsPossibleChanged();
    partial void OnWasAnsweredChanging(bool value);
    partial void OnWasAnsweredChanged();
    partial void OnTestResultIDChanging(int value);
    partial void OnTestResultIDChanged();
    partial void OnVirtualQuestionIDChanging(int value);
    partial void OnVirtualQuestionIDChanged();
    partial void OnAnswerLetterChanging(string value);
    partial void OnAnswerLetterChanged();
    partial void OnBlockedChanging(bool value);
    partial void OnBlockedChanged();
    partial void OnAnswerTextChanging(string value);
    partial void OnAnswerTextChanged();
    partial void OnBubbleSheetErrorTypeChanging(string value);
    partial void OnBubbleSheetErrorTypeChanged();
    partial void OnResponseIdentifierChanging(string value);
    partial void OnResponseIdentifierChanged();
    partial void OnAnswerImageChanging(string value);
    partial void OnAnswerImageChanged();
    partial void OnHighlightQuestionChanging(string value);
    partial void OnHighlightQuestionChanged();
    partial void OnHighlightPassageChanging(string value);
    partial void OnHighlightPassageChanged();
    partial void OnOverriddenChanging(System.Nullable<bool> value);
    partial void OnOverriddenChanged();
    partial void OnUpdatedByChanging(System.Nullable<int> value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    #endregion
		
		public AnswerLogEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AnswerLogID
		{
			get
			{
				return this._AnswerLogID;
			}
			set
			{
				if ((this._AnswerLogID != value))
				{
					this.OnAnswerLogIDChanging(value);
					this.SendPropertyChanging();
					this._AnswerLogID = value;
					this.SendPropertyChanged("AnswerLogID");
					this.OnAnswerLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerID", DbType="Int NOT NULL")]
		public int AnswerID
		{
			get
			{
				return this._AnswerID;
			}
			set
			{
				if ((this._AnswerID != value))
				{
					this.OnAnswerIDChanging(value);
					this.SendPropertyChanging();
					this._AnswerID = value;
					this.SendPropertyChanged("AnswerID");
					this.OnAnswerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsEarned", DbType="Int NOT NULL")]
		public int PointsEarned
		{
			get
			{
				return this._PointsEarned;
			}
			set
			{
				if ((this._PointsEarned != value))
				{
					this.OnPointsEarnedChanging(value);
					this.SendPropertyChanging();
					this._PointsEarned = value;
					this.SendPropertyChanged("PointsEarned");
					this.OnPointsEarnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsPossible", DbType="Int NOT NULL")]
		public int PointsPossible
		{
			get
			{
				return this._PointsPossible;
			}
			set
			{
				if ((this._PointsPossible != value))
				{
					this.OnPointsPossibleChanging(value);
					this.SendPropertyChanging();
					this._PointsPossible = value;
					this.SendPropertyChanged("PointsPossible");
					this.OnPointsPossibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasAnswered", DbType="Bit NOT NULL")]
		public bool WasAnswered
		{
			get
			{
				return this._WasAnswered;
			}
			set
			{
				if ((this._WasAnswered != value))
				{
					this.OnWasAnsweredChanging(value);
					this.SendPropertyChanging();
					this._WasAnswered = value;
					this.SendPropertyChanged("WasAnswered");
					this.OnWasAnsweredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultID", DbType="Int NOT NULL")]
		public int TestResultID
		{
			get
			{
				return this._TestResultID;
			}
			set
			{
				if ((this._TestResultID != value))
				{
					this.OnTestResultIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultID = value;
					this.SendPropertyChanged("TestResultID");
					this.OnTestResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualQuestionID", DbType="Int NOT NULL")]
		public int VirtualQuestionID
		{
			get
			{
				return this._VirtualQuestionID;
			}
			set
			{
				if ((this._VirtualQuestionID != value))
				{
					this.OnVirtualQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._VirtualQuestionID = value;
					this.SendPropertyChanged("VirtualQuestionID");
					this.OnVirtualQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerLetter", DbType="VarChar(200)")]
		public string AnswerLetter
		{
			get
			{
				return this._AnswerLetter;
			}
			set
			{
				if ((this._AnswerLetter != value))
				{
					this.OnAnswerLetterChanging(value);
					this.SendPropertyChanging();
					this._AnswerLetter = value;
					this.SendPropertyChanged("AnswerLetter");
					this.OnAnswerLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blocked", DbType="Bit NOT NULL")]
		public bool Blocked
		{
			get
			{
				return this._Blocked;
			}
			set
			{
				if ((this._Blocked != value))
				{
					this.OnBlockedChanging(value);
					this.SendPropertyChanging();
					this._Blocked = value;
					this.SendPropertyChanged("Blocked");
					this.OnBlockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerText", DbType="NVarChar(MAX)")]
		public string AnswerText
		{
			get
			{
				return this._AnswerText;
			}
			set
			{
				if ((this._AnswerText != value))
				{
					this.OnAnswerTextChanging(value);
					this.SendPropertyChanging();
					this._AnswerText = value;
					this.SendPropertyChanged("AnswerText");
					this.OnAnswerTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BubbleSheetErrorType", DbType="VarChar(10)")]
		public string BubbleSheetErrorType
		{
			get
			{
				return this._BubbleSheetErrorType;
			}
			set
			{
				if ((this._BubbleSheetErrorType != value))
				{
					this.OnBubbleSheetErrorTypeChanging(value);
					this.SendPropertyChanging();
					this._BubbleSheetErrorType = value;
					this.SendPropertyChanged("BubbleSheetErrorType");
					this.OnBubbleSheetErrorTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseIdentifier", DbType="VarChar(50)")]
		public string ResponseIdentifier
		{
			get
			{
				return this._ResponseIdentifier;
			}
			set
			{
				if ((this._ResponseIdentifier != value))
				{
					this.OnResponseIdentifierChanging(value);
					this.SendPropertyChanging();
					this._ResponseIdentifier = value;
					this.SendPropertyChanged("ResponseIdentifier");
					this.OnResponseIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerImage", DbType="NVarChar(MAX)")]
		public string AnswerImage
		{
			get
			{
				return this._AnswerImage;
			}
			set
			{
				if ((this._AnswerImage != value))
				{
					this.OnAnswerImageChanging(value);
					this.SendPropertyChanging();
					this._AnswerImage = value;
					this.SendPropertyChanged("AnswerImage");
					this.OnAnswerImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighlightQuestion", DbType="VarChar(MAX)")]
		public string HighlightQuestion
		{
			get
			{
				return this._HighlightQuestion;
			}
			set
			{
				if ((this._HighlightQuestion != value))
				{
					this.OnHighlightQuestionChanging(value);
					this.SendPropertyChanging();
					this._HighlightQuestion = value;
					this.SendPropertyChanged("HighlightQuestion");
					this.OnHighlightQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighlightPassage", DbType="VarChar(MAX)")]
		public string HighlightPassage
		{
			get
			{
				return this._HighlightPassage;
			}
			set
			{
				if ((this._HighlightPassage != value))
				{
					this.OnHighlightPassageChanging(value);
					this.SendPropertyChanging();
					this._HighlightPassage = value;
					this.SendPropertyChanged("HighlightPassage");
					this.OnHighlightPassageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Overridden", DbType="Bit")]
		public System.Nullable<bool> Overridden
		{
			get
			{
				return this._Overridden;
			}
			set
			{
				if ((this._Overridden != value))
				{
					this.OnOverriddenChanging(value);
					this.SendPropertyChanging();
					this._Overridden = value;
					this.SendPropertyChanged("Overridden");
					this.OnOverriddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="Int")]
		public System.Nullable<int> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestResultAudit")]
	public partial class TestResultAuditEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestResultAuditID;
		
		private int _TestResultID;
		
		private string _Type;
		
		private int _UserID;
		
		private System.DateTime _AuditDate;
		
		private string _IPAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestResultAuditIDChanging(int value);
    partial void OnTestResultAuditIDChanged();
    partial void OnTestResultIDChanging(int value);
    partial void OnTestResultIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnAuditDateChanging(System.DateTime value);
    partial void OnAuditDateChanged();
    partial void OnIPAddressChanging(string value);
    partial void OnIPAddressChanged();
    #endregion
		
		public TestResultAuditEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultAuditID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestResultAuditID
		{
			get
			{
				return this._TestResultAuditID;
			}
			set
			{
				if ((this._TestResultAuditID != value))
				{
					this.OnTestResultAuditIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultAuditID = value;
					this.SendPropertyChanged("TestResultAuditID");
					this.OnTestResultAuditIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestResultID", DbType="Int NOT NULL")]
		public int TestResultID
		{
			get
			{
				return this._TestResultID;
			}
			set
			{
				if ((this._TestResultID != value))
				{
					this.OnTestResultIDChanging(value);
					this.SendPropertyChanging();
					this._TestResultID = value;
					this.SendPropertyChanged("TestResultID");
					this.OnTestResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditDate", DbType="DateTime NOT NULL")]
		public System.DateTime AuditDate
		{
			get
			{
				return this._AuditDate;
			}
			set
			{
				if ((this._AuditDate != value))
				{
					this.OnAuditDateChanging(value);
					this.SendPropertyChanging();
					this._AuditDate = value;
					this.SendPropertyChanged("AuditDate");
					this.OnAuditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this.OnIPAddressChanging(value);
					this.SendPropertyChanging();
					this._IPAddress = value;
					this.SendPropertyChanged("IPAddress");
					this.OnIPAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TestResultRemoverLog")]
    public partial class TestResultRemoverLogEntity : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _TestResultRemoverLogID;
        private int _UserID;
        private string _ActionType;
        private System.DateTime _CreatedDate;
        private string _IPAddress;
        private string _TestResultIDs;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnTestResultRemoverLogIDChanging(int value);
        partial void OnTestResultRemoverLogIDChanged();
        partial void OnActionTypeTypeChanging(string value);
        partial void OnActionTypeTypeChanged();
        partial void OnUserIDChanging(int value);
        partial void OnUserIDChanged();
        partial void OnCreatedDateChanging(System.DateTime value);
        partial void OnCreatedDateChanged();
        partial void OnIPAddressChanging(string value);
        partial void OnIPAddressChanged();
        partial void OnTestResultIDsChanging(string value);
        partial void OnTestResultIDsChanged();
        #endregion

        public TestResultRemoverLogEntity()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TestResultRemoverLogID", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int TestResultRemoverLogID
        {
            get
            {
                return this._TestResultRemoverLogID;
            }
            set
            {
                if ((this._TestResultRemoverLogID != value))
                {
                    this.OnTestResultRemoverLogIDChanging(value);
                    this.SendPropertyChanging();
                    this._TestResultRemoverLogID = value;
                    this.SendPropertyChanged("TestResultRemoverLogID");
                    this.OnTestResultRemoverLogIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ActionType", DbType = "VarChar(100) NULL", CanBeNull = false)]
        public string ActionType
        {
            get
            {
                return this._ActionType;
            }
            set
            {
                if ((this._ActionType != value))
                {
                    this.OnActionTypeTypeChanging(value);
                    this.SendPropertyChanging();
                    this._ActionType = value;
                    this.SendPropertyChanged("ActionType");
                    this.OnIPAddressChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserID", DbType = "Int NULL")]
        public int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                if ((this._UserID != value))
                {
                    this.OnUserIDChanging(value);
                    this.SendPropertyChanging();
                    this._UserID = value;
                    this.SendPropertyChanged("UserID");
                    this.OnUserIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreatedDate", DbType = "DateTime NULL")]
        public System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                if ((this._CreatedDate != value))
                {
                    this.OnCreatedDateChanging(value);
                    this.SendPropertyChanging();
                    this._CreatedDate = value;
                    this.SendPropertyChanged("CreatedDate");
                    this.OnCreatedDateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IPAddress", DbType = "VarChar(200) NULL", CanBeNull = false)]
        public string IPAddress
        {
            get
            {
                return this._IPAddress;
            }
            set
            {
                if ((this._IPAddress != value))
                {
                    this.OnIPAddressChanging(value);
                    this.SendPropertyChanging();
                    this._IPAddress = value;
                    this.SendPropertyChanged("IPAddress");
                    this.OnIPAddressChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TestResultIDs", DbType = "VarChar(MAX) NULL", CanBeNull = false)]
        public string TestResultIDs
        {
            get
            {
                return this._TestResultIDs;
            }
            set
            {
                if ((this._TestResultIDs != value))
                {
                    this.OnTestResultIDsChanging(value);
                    this.SendPropertyChanging();
                    this._TestResultIDs = value;
                    this.SendPropertyChanged("TestResultIDs");
                    this.OnTestResultIDsChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
