<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingLog" Class="TestAuditDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.245.226.146;Initial Catalog=AdminReportingLog;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingLogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AnswerAudit" Member="AnswerAuditEntities" AccessModifier="Internal">
    <Type Name="AnswerAuditEntity" AccessModifier="Internal">
      <Column Name="AnswerAuditID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PreviousValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerSubAudit" Member="AnswerSubAuditEntities" AccessModifier="Internal">
    <Type Name="AnswerSubAuditEntity" AccessModifier="Internal">
      <Column Name="AnswerSubAuditID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PreviousValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QTIOnlineTestSessionAnswerAudit" Member="QTIOnlineTestSessionAnswerAuditEntities" AccessModifier="Internal">
    <Type Name="QTIOnlineTestSessionAnswerAuditEntity" AccessModifier="Internal">
      <Column Name="QTIOnlineTestSessionAnswerAuditID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionAnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PreviousValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QTIOnlineTestSessionAnswerSubAudit" Member="QTIOnlineTestSessionAnswerSubAuditEntities" AccessModifier="Internal">
    <Type Name="QTIOnlineTestSessionAnswerSubAuditEntity" AccessModifier="Internal">
      <Column Name="QTIOnlineTestSessionAnswerSubAuditID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionAnswerSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PreviousValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualQuestionSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>