<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingLog" Class="TestResultLogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.245.226.146;Initial Catalog=AdminReportingLog;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingLogConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TestResultSubScoreLog" Member="TestResultSubScoreLogEntities">
    <Type Name="TestResultSubScoreLogEntity">
      <Column Name="TestResultSubScoreLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultSubScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsePercentage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseGradeLevelEquiv" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ScoreGradeLevelEquiv" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="MetStandard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultScoreLog" Member="TestResultScoreLogEntities">
    <Type Name="TestResultScoreLogEntity">
      <Column Name="TestResultScoreLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultScoreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TookTest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScorePercent" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScorePercentage" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreRaw" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreScaled" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreLexile" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ScoreIndex" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="UsePercent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsePercentage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseRaw" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseScaled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseLexile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UseIndex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AchievementLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseGradeLevelEquiv" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScoreGradeLevelEquiv" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MetStandard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AchieveLevelName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ScoreCustomN_1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ScoreCustomN_2" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ScoreCustomN_3" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ScoreCustomN_4" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ScoreCustomA_1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ScoreCustomA_4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultProgramLog" Member="TestResultProgramLogEntities">
    <Type Name="TestResultProgramLogEntity">
      <Column Name="TestResultProgramLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultLog" Member="TestResultLogEntities">
    <Type Name="TestResultLogEntity">
      <Column Name="TestResultLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScoreValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TRData" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="SubmitType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginalUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LegacyBatchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BubbleSheetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="StudentFirst" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StudentLast" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerSubLog" Member="AnswerSubLogEntities">
    <Type Name="AnswerSubLogEntity">
      <Column Name="AnswerSubLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualQuestionSubID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerLetter" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Overridden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerLog" Member="AnswerLogEntities">
    <Type Name="AnswerLogEntity">
      <Column Name="AnswerLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsEarned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointsPossible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WasAnswered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerLetter" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Blocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BubbleSheetErrorType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ResponseIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AnswerImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HighlightQuestion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="HighlightPassage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Overridden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestResultAudit" Member="TestResultAuditEntities">
    <Type Name="TestResultAuditEntity">
      <Column Name="TestResultAuditID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuditDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>
