<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="TLDSContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
    <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;User ID=linkit_user;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString32" Provider="System.Data.SqlClient" /> 
  <Table Name="dbo.TLDSAdditionalInformation" Member="TLDSAdditionalInformationEntities" AccessModifier="Internal">
    <Type Name="TLDSAdditionalInformationEntity">
      <Column Name="AdditionalInformationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AreasOfNote" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="StrategiesForEnhancedSupport" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="TLDSProfileEntity_TLDSAdditionalInformationEntity" Member="TLDSProfileEntity" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSDevelopmentOutcome" Member="TLDSDevelopmentOutcomeEntities" AccessModifier="Internal">
    <Type Name="TLDSDevelopmentOutcomeEntity" AccessModifier="Internal">
      <Column Name="DevelopmentOutcomeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DevelopmentOutcomeTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSDevelopmentOutcomeProfile" Member="TLDSDevelopmentOutcomeProfileEntities" AccessModifier="Internal">
    <Type Name="TLDSDevelopmentOutcomeProfileEntity">
      <Column Name="DevelopmentOutcomeProfileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DevelopmentOutcomeTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DevelopmentOutcomeContent" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="StrategyContent" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="TLDSProfileEntity_TLDSDevelopmentOutcomeProfileEntity" Member="TLDSProfileEntity" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSOtherReportPlan" Member="TLDSOtherReportPlanEntities" AccessModifier="Internal">
    <Type Name="TLDSOtherReportPlanEntity">
      <Column Name="OtherReportPlanID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReportDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AttachmentURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AvailableOnRequest" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TLDSProfileEntity_TLDSOtherReportPlanEntity" Member="TLDSProfileEntity" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSParentGuardian" Member="TLDSParentGuardianEntities" AccessModifier="Internal">
    <Type Name="TLDSParentGuardianEntity">
      <Column Name="TLDSParentGuardianID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TLDSProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentGuardianName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ParentGuardianRelationship" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ParentGuardianPhone" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ParentGuardianEmail" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="TLDSProfileEntity_TLDSParentGuardianEntity" Member="TLDSProfileEntity" ThisKey="TLDSProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSProfessionalService" Member="TLDSProfessionalServiceEntities" AccessModifier="Internal">
    <Type Name="TLDSProfessionalServiceEntity">
      <Column Name="ProfessionalServiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WrittenReportAvailable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReportForwardedToSchoolDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Attached" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AvailableUponRequested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TLDSProfileEntity_TLDSProfessionalServiceEntity" Member="TLDSProfileEntity" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSEarlyABLESReport" Member="TLDSEarlyABLESReportEntities" AccessModifier="Internal">
    <Type Name="TLDSEarlyABLESReportEntity">
      <Column Name="EarlyABLESReportId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="LearningReadinessReportCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReportDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AvailableOnRequest" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TLDSProfileEntity_TLDSEarlyABLESReportEntity" Member="TLDSProfileEntity" ThisKey="ProfileId" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSUserMeta" Member="TLDSUserMetaEntities" AccessModifier="Internal">
    <Type Name="TLDSUserMetaEntity" AccessModifier="Internal">
      <Column Name="TLDSUserMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSLevelQualification" Member="TLDSLevelQualificationEntities" AccessModifier="Internal">
    <Type Name="TLDSLevelQualificationEntity" AccessModifier="Internal">
      <Column Name="TLDSLevelQualificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSUploadedDocument" Member="TLDSUploadedDocumentEntities" AccessModifier="Internal">
    <Type Name="TLDSUploadedDocumentEntity">
      <Column Name="UploadedDocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OriginalFileName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="S3FileName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UploadedUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TLDSProfileEntity_TLDSUploadedDocumentEntity" Member="TLDSProfileEntity" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSProfileMeta" Member="TLDSProfileMetaEntities">
    <Type Name="TLDSProfileMetaEntity">
      <Column Name="TLDSProfileMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TLDSProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MetaValue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSDownloadQueue" Member="TLDSDownloadQueueEntities" AccessModifier="Internal">
    <Type Name="TLDSDownloadQueueEntity" AccessModifier="Internal">
      <Column Name="TLDSDownloadQueueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfileIDs" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompletedFiles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Errors" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSProfileLink" Member="TLDSProfileLinkEntities" AccessModifier="Internal">
    <Type Name="TLDSProfileLinkEntity">
      <Column Name="TLDSProfileLinkID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LinkUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LoginFailed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TLDSProfileLinkEntity_TLDSFormSection2Entity" Member="TLDSFormSection2Entities" Storage="_TLDSFormSection2s" ThisKey="TLDSProfileLinkID" OtherKey="TLDSProfileLinkID" Type="TLDSFormSection2Entity" />
      <Association Name="TLDSProfileLinkEntity_TLDSFormSection3Entity" Member="TLDSFormSection3Entities" Storage="_TLDSFormSection3s" ThisKey="TLDSProfileLinkID" OtherKey="TLDSProfileLinkID" Type="TLDSFormSection3Entity" />
      <Association Name="TLDSProfileEntity_TLDSProfileLinkEntity" Member="TLDSProfileEntity" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSFormSection2" Member="TLDSFormSection2Entities" AccessModifier="Internal">
    <Type Name="TLDSFormSection2Entity">
      <Column Name="TLDSFormSection2ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TLDSProfileLinkID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="GuardianName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Relationship" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Favourite" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Strengths" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Weaknesses" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Interested" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Expected" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Drawing" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IsSubmitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TLDSProfileLinkEntity_TLDSFormSection2Entity" Member="TLDSProfileLinkEntity" Storage="_TLDSProfileLink" ThisKey="TLDSProfileLinkID" OtherKey="TLDSProfileLinkID" Type="TLDSProfileLinkEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSFormSection3" Member="TLDSFormSection3Entities" AccessModifier="Internal">
    <Type Name="TLDSFormSection3Entity">
      <Column Name="TLDSFormSection3ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TLDSProfileLinkID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="GuardianName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Relationship" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PreferredLanguage" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsAborigial" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HaveSiblingInSchool" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NameAndGradeOfSibling" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Wishes" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="InformationSchool" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="HelpInformation" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Interested" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ConditionImprovement" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="OtherInformation" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="IsSubmitted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TLDSProfileLinkEntity_TLDSFormSection3Entity" Member="TLDSProfileLinkEntity" Storage="_TLDSProfileLink" ThisKey="TLDSProfileLinkID" OtherKey="TLDSProfileLinkID" Type="TLDSProfileLinkEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSGroup" Member="TLDSGroupEntities">
    <Type Name="TLDSGroupEntity">
      <Column Name="TLDSGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TLDSUserMetaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSProfileTeacher" Member="TLDSProfileTeacherEntities">
    <Type Name="TLDSProfileTeacherEntity">
      <Column Name="TLDSProfileTeacherID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TLDSUserMetaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EducatorName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TLDSLevelQualificationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLDSProfile" Member="TLDSProfileEntities">
    <Type Name="TLDSProfileEntity">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PrimarySchool" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="OutsideSchoolHoursCareService" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PhotoURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ECSName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ECSAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ECSApprovalNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorPosition" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorQualification" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorQualificationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorEmail" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ECSCompledDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TLDSInformationHasBeenSaved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ContextOfEarlyYearsSetting" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpecificInformation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContextSpecificInforHasBeenSaved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DevelopmentOutcomeHasBeenSaved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SectionChildInputFileUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SectionFamilyFileUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SectionParentConsentFileUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Section102IsNotRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoKWName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NoKWPosition" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NoKWPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoKWEmail" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="EARReportCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EARReportDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EARAttachmentURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EARAvailableUponRequest" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Section102HasBeenSaved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UploadedChildFormFileName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UploadedFamilyFormFileName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UpcommingSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentConsentIsIncluded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SectionChildParentCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrintAllSectionsFamily" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WasAnEarlyABLESReportCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WillAttendASchoolInVictoria" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="HasParentSharedStatementWithSchool" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SchoolNotListed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Section2CheckedCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Section3CheckedCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Section4CheckedCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RejectedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RejectedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RejectedReason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsAboriginal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnrolmentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TLDSGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TLDSProfileEntity_TLDSAdditionalInformationEntity" Member="TLDSAdditionalInformationEntities" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSAdditionalInformationEntity" />
      <Association Name="TLDSProfileEntity_TLDSDevelopmentOutcomeProfileEntity" Member="TLDSDevelopmentOutcomeProfileEntities" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSDevelopmentOutcomeProfileEntity" />
      <Association Name="TLDSProfileEntity_TLDSOtherReportPlanEntity" Member="TLDSOtherReportPlanEntities" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSOtherReportPlanEntity" />
      <Association Name="TLDSProfileEntity_TLDSParentGuardianEntity" Member="TLDSParentGuardianEntities" ThisKey="ProfileID" OtherKey="TLDSProfileID" Type="TLDSParentGuardianEntity" />
      <Association Name="TLDSProfileEntity_TLDSProfessionalServiceEntity" Member="TLDSProfessionalServiceEntities" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfessionalServiceEntity" />
      <Association Name="TLDSProfileEntity_TLDSEarlyABLESReportEntity" Member="TLDSEarlyABLESReportEntities" ThisKey="ProfileID" OtherKey="ProfileId" Type="TLDSEarlyABLESReportEntity" />
      <Association Name="TLDSProfileEntity_TLDSUploadedDocumentEntity" Member="TLDSUploadedDocumentEntities" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSUploadedDocumentEntity" />
      <Association Name="TLDSProfileEntity_TLDSProfileLinkEntity" Member="TLDSProfileLinkEntities" ThisKey="ProfileID" OtherKey="ProfileID" Type="TLDSProfileLinkEntity" />
    </Type>
  </Table>
  <Function Name="dbo.TLDSDeleteProfile" Method="TLDSDeleteProfile">
    <Parameter Name="CurrentUserID" Parameter="currentUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TLDSProfileID" Parameter="tLDSProfileID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TLDSRejectProfile" Method="TLDSRejectProfile">
    <Parameter Name="CurrentUserID" Parameter="currentUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TLDSProfileID" Parameter="tLDSProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RejectedReason" Parameter="rejectedReason" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TLDSStudentGetGradesForFilter" Method="TLDSStudentGetGradesForFilter">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="TLDSStudentGetGradesForFilterResult">
      <Column Name="GradeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSStudentLookup" Method="TLDSStudentLookup">
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StateCode" Parameter="stateCode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GradeID" Parameter="gradeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RaceName" Parameter="raceName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="GenderID" Parameter="genderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TLDSProfileID" Parameter="tLDSProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="ShowAssociatedStudentOnly" Parameter="showAssociatedStudentOnly" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SSearch" Parameter="sSearch" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecords" Parameter="totalRecords" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SortColumns" Parameter="sortColumns" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="TLDSStudentLookupResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AltCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GradeName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RaceName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GenderCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckTLDSSectionSubmitted" Method="CheckTLDSSectionSubmitted">
    <Parameter Name="profileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="sectionType" Type="System.Int32" DbType="Int" />
    <ElementType Name="CheckTLDSSectionSubmittedResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTLDSInformationForSection23" Method="GetTLDSInformationForSection23">
    <Parameter Name="TLDSProfileLinkId" Parameter="tLDSProfileLinkId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetTLDSInformationForSection23Result">
      <Column Name="TLDSProfileLinkId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LinkUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSDigitalLogin" Method="TLDSDigitalLogin">
    <Parameter Name="TldsProfileLinkId" Parameter="tldsProfileLinkId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="DateOfBirth" Parameter="dateOfBirth" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NumOfProfile" Parameter="numOfProfile" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="TLDSDigitalLoginResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTLDSProfileByTLDSProfileLinkId" Method="GetTLDSProfileByTLDSProfileLinkId">
    <Parameter Name="TldsProfileLinkId" Parameter="tldsProfileLinkId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GetTLDSProfileByTLDSProfileLinkIdResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EnrolmentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrimarySchool" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OutsideSchoolHoursCareService" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhotoURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSGroup_GetAll" Method="TLDSGroup_GetAll">
    <Parameter Name="TLDSUserMetaID" Parameter="tLDSUserMetaID" Type="System.Int32" DbType="Int" />
    <ElementType Name="TLDSGroup_GetAllResult">
      <Column Name="TLDSGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfProfile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSGetProfiles" Method="TLDSGetProfiles">
    <Parameter Name="CurrentUserID" Parameter="currentUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedUserID" Parameter="createdUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubmittedSchoolID" Parameter="submittedSchoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TLDSProfileID" Parameter="tLDSProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EnrollmentYear" Parameter="enrollmentYear" Type="System.Int32" DbType="Int" />
    <Parameter Name="TldsGroupID" Parameter="tldsGroupID" Type="System.Int32" DbType="Int" />
    <ElementType Name="TLDSGetProfilesResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpcommingSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Viewable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Updateable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnrolmentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSProfileTeacher_GetAll" Method="TLDSProfileTeacher_GetAll">
    <Parameter Name="TLDSUserMetaID" Parameter="tLDSUserMetaID" Type="System.Int32" DbType="Int" />
    <ElementType Name="TLDSProfileTeacher_GetAllResult">
      <Column Name="TLDSProfileTeacherID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TLDSUserMetaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EducatorName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TLDSLevelQualificationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTLDSProfilesForSchoolAdmin" Method="GetTLDSProfilesForSchoolAdmin">
    <Parameter Name="CurrentUserID" Parameter="currentUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedUserID" Parameter="createdUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubmittedSchoolID" Parameter="submittedSchoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TLDSProfileID" Parameter="tLDSProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="showArchived" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EnrollmentYear" Parameter="enrollmentYear" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTLDSProfilesForSchoolAdminResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpcommingSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ECSName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Section102IsNotRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ECSCompledDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsUploadedStatement" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedStatementPdfFileName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="EnrolmentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TLDSGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StatusGroup" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSProfileLink_Delete" Method="TLDSProfileLink_Delete">
    <Parameter Name="TLDSProfileLinkId" Parameter="tLDSProfileLinkId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTLDSProfileLink" Method="GetTLDSProfileLink">
    <Parameter Name="CurrentUserID" Parameter="currentUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProfileId" Parameter="profileId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTLDSProfileLinkResult">
      <Column Name="TLDSProfileLinkId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GuadianName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SectionCompleted" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LinkUrl" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ProfileStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnrolmentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TLDSGetProfilesForAssociateToGroup" Method="TLDSGetProfilesForAssociateToGroup">
    <Parameter Name="CurrentUserID" Parameter="currentUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedUserID" Parameter="createdUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubmittedSchoolID" Parameter="submittedSchoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TLDSProfileID" Parameter="tLDSProfileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EnrollmentYear" Parameter="enrollmentYear" Type="System.Int32" DbType="Int" />
    <ElementType Name="TLDSGetProfilesForAssociateToGroupResult">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastStatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpcommingSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Viewable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Updateable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ECSCompletingFormEducatorName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EnrolmentYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>
