<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingStage" Class="UserDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.252.36.127;Initial Catalog=AdminReportingStage;User ID=DevblockDev;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingStageConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TeacherDistrictTermView" Member="TeacherDistrictTermEntities" AccessModifier="Internal">
    <Type Name="TeacherDistrictTermEntity" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictTermClassView" Member="DistrictTermClassViews" AccessModifier="Internal">
    <Type Name="DistrictTermClassView" AccessModifier="Internal">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolTeacherListView" Member="SchoolTeacherListViews" AccessModifier="Internal">
    <Type Name="SchoolTeacherListView" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolStudent" Member="SchoolStudentDataEntities" AccessModifier="Internal">
    <Type Name="SchoolStudentDataEntity" AccessModifier="Internal">
      <Column Name="SchoolStudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserBanks" Member="UserBankViews" AccessModifier="Internal">
    <Type Name="UserBankView" AccessModifier="Internal">
      <Column Name="BankID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserSchoolView" Member="UserSchoolViews" AccessModifier="Internal">
    <Type Name="UserSchoolView" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolTeacherView" Member="SchoolTeacherViews" AccessModifier="Internal">
    <Type Name="SchoolTeacherView" AccessModifier="Internal">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.APIAccount" Member="APIAccountEntities" AccessModifier="Internal">
    <Type Name="APIAccountEntity" AccessModifier="Internal">
      <Column Name="APIAccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientAccessKeyID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LinkitPublicKey" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="LinkitPrivateKey" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="APIAccountTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.APIFunction" Member="APIFunctionEntities" AccessModifier="Internal">
    <Type Name="APIFunctionEntity" AccessModifier="Internal">
      <Column Name="APIFunctionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="URI" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HttpAction" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="APIFunctionEntity_APIPermissionEntity" Member="APIPermissionEntities" ThisKey="APIFunctionID" OtherKey="APIFunctionID" Type="APIPermissionEntity" />
    </Type>
  </Table>
  <Table Name="dbo.APIPermission" Member="APIPermissionEntities" AccessModifier="Internal">
    <Type Name="APIPermissionEntity" AccessModifier="Internal">
      <Column Name="APIPermissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="APIFunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsAllow" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APIAccountTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="APIFunctionEntity_APIPermissionEntity" Member="APIFunctionEntity" ThisKey="APIFunctionID" OtherKey="APIFunctionID" Type="APIFunctionEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserManageView" Member="UserManageViews">
    <Type Name="UserManageView">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SchoolList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SchoolIDList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserByUserSchoolView" Member="UserByUserSchoolViews">
    <Type Name="UserByUserSchoolView">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hint" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Privileges]" Member="Privileges" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APIaccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GUIDcode" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SISID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HashedPassword" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HasTemporaryPassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordLastSetDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateConfirmedActive" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MessageNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserSchoolUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserSchoolSchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictSlide" Member="DistrictSlideEntities">
    <Type Name="DistrictSlideEntity">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SlideOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LinkTo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NewTabOpen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictSlideID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NetworkAdminView" Member="NetworkAdminViews" AccessModifier="Internal">
    <Type Name="NetworkAdminView" AccessModifier="Internal">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneOffsetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ImpersonateLog" Member="ImpersonateLogEntities" AccessModifier="Internal">
    <Type Name="ImpersonateLogEntity" AccessModifier="Internal">
      <Column Name="ImpersonateLogID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SessionCookieGUID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ActionType" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ActionTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OriginalUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImpersonatedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherDistrictTermView" Member="TeacherDistrictTermViews" AccessModifier="Internal">
    <Type Name="TeacherDistrictTermView" AccessModifier="Internal">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PasswordResetQuestion" Member="PasswordResetQuestionEntities" AccessModifier="Internal">
    <Type Name="PasswordResetQuestionEntity" AccessModifier="Internal">
      <Column Name="PasswordQuestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ASPsession" Member="ASPsessionEntities">
    <Type Name="ASPsessionEntity">
      <Column Name="ASPSessionTokenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SessionToken" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="expires" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LoginID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CKSession" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherTestDistrictTermView" Member="TeacherTestDistrictTermViews">
    <Type Name="TeacherTestDistrictTermView">
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSubTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FileLinks" Member="FileLinksEntities">
    <Type Name="FileLinksEntity">
      <Column Name="DownloadID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StudentTestDistrictTermView" Member="StudentTestDistrictTermViews">
    <Type Name="StudentTestDistrictTermView">
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VirtualTestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VirtualTestSubTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TakenTestClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TakenTestDistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TakenTestSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TakenTestTeacherID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.District" Member="DistrictEntities">
    <Type Name="DistrictEntity">
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneOffsetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="DistrictEntity_SchoolEntity" Member="SchoolEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="SchoolEntity" />
      <Association Name="DistrictEntity_UserEntity" Member="UserEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="UserEntity" />
      <Association Name="DistrictEntity_TeacherEntity" Member="TeacherEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="TeacherEntity" />
      <Association Name="DistrictEntity_DistrictDecodeEntity" Member="DistrictDecodeEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictDecodeEntity" />
      <Association Name="DistrictEntity_DSPDistrictEntity" Member="DSPDistricts" ThisKey="DistrictID" OtherKey="MemberDistrictID" Type="DSPDistrictEntity" />
      <Association Name="DistrictEntity_DSPDistrictEntity1" Member="DSPDistrictEntities" ThisKey="DistrictID" OtherKey="OrganizationDistrictID" Type="DSPDistrictEntity" />
      <Association Name="DistrictEntity_LocalizeResourceEntity" Member="LocalizeResourceEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="LocalizeResourceEntity" />
      <Association Name="DistrictEntity_SSOUserMappingEntity" Member="SSOUserMappingEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="SSOUserMappingEntity" />
      <Association Name="DistrictEntity_SSODistrictGroupEntity" Member="SSODistrictGroupEntities" ThisKey="DistrictID" OtherKey="DistrictID" Type="SSODistrictGroupEntity" />
      <Association Name="StateEntity_DistrictEntity" Member="StateEntity" ThisKey="StateID" OtherKey="StateID" Type="StateEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.School" Member="SchoolEntities">
    <Type Name="SchoolEntity">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TempName" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SISID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="SchoolEntity_UserSchoolEntity" Member="UserSchoolEntities" ThisKey="SchoolID" OtherKey="SchoolID" Type="UserSchoolEntity" />
      <Association Name="SchoolEntity_CEESchoolEntity" Member="CEESchoolEntities" ThisKey="SchoolID" OtherKey="SchoolID" Type="CEESchoolEntity" />
      <Association Name="DistrictEntity_SchoolEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
      <Association Name="StateEntity_SchoolEntity" Member="StateEntity" ThisKey="StateID" OtherKey="StateID" Type="StateEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="UserEntities">
    <Type Name="UserEntity">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hint" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Privileges]" Member="Privileges" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APIaccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GUIDcode" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SISID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HashedPassword" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HasTemporaryPassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime2(7) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordLastSetDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateConfirmedActive" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MessageNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TermOfUseAccepted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UserEntity_SSOUserMappingEntity" Member="SSOUserMappingEntities" ThisKey="UserID" OtherKey="UserID" Type="SSOUserMappingEntity" />
      <Association Name="UserEntity_XLIGroupUser" Member="XLIGroupUsers" ThisKey="UserID" OtherKey="UserID" Type="XLIGroupUser" />
      <Association Name="UserEntity_UserMetaEntity" Member="UserMetaEntities" ThisKey="UserID" OtherKey="UserID" Type="UserMetaEntity" />
      <Association Name="UserEntity_SharingGroupUserEntity" Member="SharingGroupUserEntities" ThisKey="UserID" OtherKey="UserID" Type="SharingGroupUserEntity" />
      <Association Name="UserEntity_SharingReportEntity" Member="SharingReportEntities" ThisKey="UserID" OtherKey="UserID" Type="SharingReportEntity" />
      <Association Name="UserEntity_SharingReportPropertyEntity" Member="SharingReportPropertyEntities" ThisKey="UserID" OtherKey="UserID" Type="SharingReportPropertyEntity" />
      <Association Name="DistrictEntity_UserEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
      <Association Name="TeacherEntity_UserEntity" Member="TeacherEntity" ThisKey="TeacherID" OtherKey="TeacherID" Type="TeacherEntity" IsForeignKey="true" />
      <Association Name="StateEntity_UserEntity" Member="StateEntity" ThisKey="StateID" OtherKey="StateID" Type="StateEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="TeacherEntities">
    <Type Name="TeacherEntity">
      <Column Name="TeacherID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Hint" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TeacherEntity_UserEntity" Member="UserEntities" ThisKey="TeacherID" OtherKey="TeacherID" Type="UserEntity" />
      <Association Name="TeacherEntity_TermEntity" Member="TermEntities" ThisKey="TeacherID" OtherKey="TeacherID" Type="TermEntity" />
      <Association Name="DistrictEntity_TeacherEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictDecode" Member="DistrictDecodeEntities">
    <Type Name="DistrictDecodeEntity">
      <Column Name="DistrictDeCodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="DistrictDecodeEntity_DistrictDecodeEntity" Member="DistrictDecodeEntity1" ThisKey="DistrictDeCodeID" OtherKey="DistrictDeCodeID" Type="DistrictDecodeEntity" Cardinality="One" />
      <Association Name="DistrictEntity_DistrictDecodeEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
      <Association Name="DistrictDecodeEntity_DistrictDecodeEntity" Member="DistrictDecode1" ThisKey="DistrictDeCodeID" OtherKey="DistrictDeCodeID" Type="DistrictDecodeEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DSPDistrict" Member="DSPDistrictEntities">
    <Type Name="DSPDistrictEntity">
      <Column Name="DSPDistrictID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrganizationDistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MemberDistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DistrictEntity_DSPDistrictEntity" Member="DistrictEntity" ThisKey="MemberDistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
      <Association Name="DistrictEntity_DSPDistrictEntity1" Member="DistrictEntity1" ThisKey="OrganizationDistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserSchool" Member="UserSchoolEntities">
    <Type Name="UserSchoolEntity">
      <Column Name="UserSchoolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateInactive" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateActive" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SchoolEntity_UserSchoolEntity" Member="SchoolEntity" ThisKey="SchoolID" OtherKey="SchoolID" Type="SchoolEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CEESchool" Member="CEESchoolEntities">
    <Type Name="CEESchoolEntity">
      <Column Name="CEESchoolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="SchoolEntity_CEESchoolEntity" Member="SchoolEntity" ThisKey="SchoolID" OtherKey="SchoolID" Type="SchoolEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Term" Member="TermEntities">
    <Type Name="TermEntity">
      <Column Name="TermID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TeacherEntity_TermEntity" Member="TeacherEntity" ThisKey="TeacherID" OtherKey="TeacherID" Type="TeacherEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DisplayUserGroupAndRoleView" Member="DisplayUserGroupAndRoleViews" AccessModifier="Internal">
    <Type Name="DisplayUserGroupAndRoleView" AccessModifier="Internal">
      <Column Name="GroupName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="XLIGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleDisplay" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LocalizeResource" Member="LocalizeResourceEntities">
    <Type Name="LocalizeResourceEntity">
      <Column Name="LocalizeResourceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="DistrictEntity_LocalizeResourceEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TeacherListView" Member="TeacherListViews">
    <Type Name="TeacherListView">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIGroup" Member="XLIGroupEntities">
    <Type Name="XLIGroupEntity">
      <Column Name="XLIGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InheritRoleFunctionality" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="XLIGroupEntity_XLIAreaGroup" Member="XLIAreaGroups" ThisKey="XLIGroupID" OtherKey="XLIGroupID" Type="XLIAreaGroup" />
      <Association Name="XLIGroupEntity_XLIGroupUser" Member="XLIGroupUsers" ThisKey="XLIGroupID" OtherKey="XLIGroupID" Type="XLIGroupUser" />
    </Type>
  </Table>
  <Table Name="dbo.DSPDistrictView" Member="DSPDistrictViews">
    <Type Name="DSPDistrictView">
      <Column Name="OrganizationDistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LICode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneOffsetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NotificationMessage" Member="NotificationMessageEntities">
    <Type Name="NotificationMessageEntity">
      <Column Name="NotificationMessageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublishedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HtmlContent" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AccessedDistrict" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ReceivingUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotificationType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SSOInformation" Member="SSOInformationEntities">
    <Type Name="SSOInformationEntity">
      <Column Name="SSOInformationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Auth0ClientId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Auth0ClientSecret" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultConnection" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UrlLandingPage" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="UrlLogoutPage" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="SSOInformationEntity_SSODistrictGroupEntity" Member="SSODistrictGroupEntities" ThisKey="SSOInformationID" OtherKey="SSOInformationID" Type="SSODistrictGroupEntity" />
    </Type>
  </Table>
  <Table Name="dbo.SSOUserMapping" Member="SSOUserMappingEntities">
    <Type Name="SSOUserMappingEntity">
      <Column Name="SSOUserMappingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADUsername" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="DistrictEntity_SSOUserMappingEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
      <Association Name="UserEntity_SSOUserMappingEntity" Member="UserEntity" ThisKey="UserID" OtherKey="UserID" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SSODistrictGroup" Member="SSODistrictGroupEntities">
    <Type Name="SSODistrictGroupEntity">
      <Column Name="SSODistrictGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SSOInformationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DistrictEntity_SSODistrictGroupEntity" Member="DistrictEntity" ThisKey="DistrictID" OtherKey="DistrictID" Type="DistrictEntity" IsForeignKey="true" />
      <Association Name="SSOInformationEntity_SSODistrictGroupEntity" Member="SSOInformationEntity" ThisKey="SSOInformationID" OtherKey="SSOInformationID" Type="SSOInformationEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="StateEntities">
    <Type Name="StateEntity">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultTimeZoneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipRange" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="International" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TimeZoneID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="StateEntity_DistrictEntity" Member="DistrictEntities" ThisKey="StateID" OtherKey="StateID" Type="DistrictEntity" />
      <Association Name="StateEntity_SchoolEntity" Member="SchoolEntities" ThisKey="StateID" OtherKey="StateID" Type="SchoolEntity" />
      <Association Name="StateEntity_UserEntity" Member="UserEntities" ThisKey="StateID" OtherKey="StateID" Type="UserEntity" />
    </Type>
  </Table>
  <Table Name="dbo.XLIAreaGroup" Member="XLIAreaGroups">
    <Type Name="XLIAreaGroup">
      <Column Name="XLIAreaGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="XLIAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XLIGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Expires" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="XLIAreaGroup_XLIAreaGroupModule" Member="XLIAreaGroupModules" ThisKey="XLIAreaGroupID" OtherKey="XLIAreaGroupID" Type="XLIAreaGroupModule" />
      <Association Name="XLIGroupEntity_XLIAreaGroup" Member="XLIGroupEntity" ThisKey="XLIGroupID" OtherKey="XLIGroupID" Type="XLIGroupEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIAreaGroupModule" Member="XLIAreaGroupModules">
    <Type Name="XLIAreaGroupModule">
      <Column Name="XLIAreaGroupModuleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="XLIAreaGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XLIModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllRoles" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="XLIAreaGroupModule_XLIAreaGMRole" Member="XLIAreaGMRoles" ThisKey="XLIAreaGroupModuleID" OtherKey="XLIAreaGroupModuleID" Type="XLIAreaGMRole" />
      <Association Name="XLIAreaGroup_XLIAreaGroupModule" Member="XLIAreaGroup" ThisKey="XLIAreaGroupID" OtherKey="XLIAreaGroupID" Type="XLIAreaGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIAreaGMRole" Member="XLIAreaGMRoles">
    <Type Name="XLIAreaGMRole">
      <Column Name="XLIAreaGMRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XLIAreaGroupModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="XLIAreaGroupModule_XLIAreaGMRole" Member="XLIAreaGroupModule" ThisKey="XLIAreaGroupModuleID" OtherKey="XLIAreaGroupModuleID" Type="XLIAreaGroupModule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XLIGroupUser" Member="XLIGroupUsers">
    <Type Name="XLIGroupUser">
      <Column Name="XLIGroupUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="XLIGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="XLIGroupEntity_XLIGroupUser" Member="XLIGroupEntity" ThisKey="XLIGroupID" OtherKey="XLIGroupID" Type="XLIGroupEntity" IsForeignKey="true" />
      <Association Name="UserEntity_XLIGroupUser" Member="UserEntity" ThisKey="UserID" OtherKey="UserID" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolManagementView" Member="UserContext_SchoolManagementViews">
    <Type Name="UserContext_SchoolManagementView">
      <Column Name="UserSchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DistrictMeta" Member="DistrictMetaEntities">
    <Type Name="DistrictMetaEntity">
      <Column Name="DistrictMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserMeta" Member="UserMetaEntities">
    <Type Name="UserMetaEntity">
      <Column Name="UserMetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaValue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaLabel" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="UserEntity_UserMetaEntity" Member="UserEntity" ThisKey="UserID" OtherKey="UserID" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AutoFocusGroupConfig" Member="AutoFocusGroupConfigEntities">
    <Type Name="AutoFocusGroupConfigEntity">
      <Column Name="AutoFocusGroupConfigID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AutoGroupType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JSONConfig" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ScheduledTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="LastRunDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Run" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserStudentView" Member="UserStudentViews">
    <Type Name="UserStudentView">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SharingGroup" Member="SharingGroupEntities">
    <Type Name="SharingGroupEntity">
      <Column Name="SharingGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPublished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PublishTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublisherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SharingGroupEntity_SharingGroupUserEntity" Member="SharingGroupUserEntities" ThisKey="SharingGroupID" OtherKey="SharingGroupID" Type="SharingGroupUserEntity" />
      <Association Name="SharingGroupEntity_SharingReportEntity" Member="SharingReportEntities" ThisKey="SharingGroupID" OtherKey="SharingGroupID" Type="SharingReportEntity" />
    </Type>
  </Table>
  <Table Name="dbo.SharingGroupUser" Member="SharingGroupUserEntities">
    <Type Name="SharingGroupUserEntity">
      <Column Name="SharingGroupUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SharingGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SharingGroupEntity_SharingGroupUserEntity" Member="SharingGroupEntity" ThisKey="SharingGroupID" OtherKey="SharingGroupID" Type="SharingGroupEntity" IsForeignKey="true" />
      <Association Name="UserEntity_SharingGroupUserEntity" Member="UserEntity" ThisKey="UserID" OtherKey="UserID" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SharingReport" Member="SharingReportEntities">
    <Type Name="SharingReportEntity">
      <Column Name="SharingReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SharingGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SavedReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImDashboardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArDashboardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SharingGroupEntity_SharingReportEntity" Member="SharingGroupEntity" ThisKey="SharingGroupID" OtherKey="SharingGroupID" Type="SharingGroupEntity" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="UserEntity_SharingReportEntity" Member="UserEntity" ThisKey="UserID" OtherKey="UserID" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SharingReportProperty" Member="SharingReportPropertyEntities">
    <Type Name="SharingReportPropertyEntity">
      <Column Name="SharingReportPropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Favorite" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Visibility" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SavedReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImDashboardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArDashboardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UserEntity_SharingReportPropertyEntity" Member="UserEntity" ThisKey="UserID" OtherKey="UserID" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetStateByDistrictNetWorkAdminID" Method="GetStateByDistrictNetWorkAdminID">
    <Parameter Name="DistrictOrganizationID" Parameter="districtOrganizationID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStateByDistrictNetWorkAdminIDResult">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultTimeZoneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipRange" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTeacherBySchoolIDAndDistricttermID" Method="GetTeacherBySchoolIDAndDistricttermID">
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistricttermID" Parameter="districttermID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTeacherBySchoolIDAndDistricttermIDResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(102)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserLoginFailedCount" Method="GetUserLoginFailedCount">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetUserLoginFailedCountResult">
      <Column Name="LoginFailedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteUserFailedCount" Method="DeleteUserFailedCount">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncreaseUserLoginFailedCount" Method="IncreaseUserLoginFailedCount">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllUserStartWithCodeByDistrictID" Method="GetAllUserStartWithCodeByDistrictID">
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalCode" Parameter="localCode" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetAllUserStartWithCodeByDistrictIDResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hint" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Privileges]" Member="Privileges" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DistrictGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APIaccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GUIDcode" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AltCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SISID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HashedPassword" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HasTemporaryPassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PasswordLastSetDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateConfirmedActive" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MessageNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TermOfUseAccepted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.fnGetStateForUser" Method="fnGetStateForUser" IsComposable="true">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UseStateOfDistrictSchool" Parameter="useStateOfDistrictSchool" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UseStateSchool" Parameter="useStateSchool" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="fnGetStateForUserResult">
      <Column Name="StateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DefaultTimeZoneID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZipRange" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="International" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddUsersToGroup" Method="AddUsersToGroup">
    <Parameter Name="UserIDs" Parameter="userIDs" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RemoveUserFromGroup" Method="RemoveUserFromGroup">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetUserAvailableForAddGroup" Method="GetUserAvailableForAddGroup">
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsShowInactiveUser" Parameter="isShowInactiveUser" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortColumn" Parameter="sortColumn" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StartRow" Parameter="startRow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GetUserAvailableForAddGroupResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SchoolList" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserManageByRoleInGroup" Method="GetUserManageByRoleInGroup">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsShowInactiveUser" Parameter="isShowInactiveUser" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="SortColumn" Parameter="sortColumn" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StartRow" Parameter="startRow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GetUserManageByRoleInGroupResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolList" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRolesForManageUserGroup" Method="GetRolesForManageUserGroup">
    <Parameter Name="UserRoleID" Parameter="userRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRolesForManageUserGroupResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserManageByRole" Method="GetUserManageByRole">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StaffName" Parameter="staffName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Inactive" Parameter="inactive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="OtherUserId" Parameter="otherUserId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetUserManageByRoleResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolIDList" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolList" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolList1" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTeacherForAddClass" Method="GetTeacherForAddClass">
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTeacherForAddClassResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTeacherSchoolByTerm" Method="GetTeacherSchoolByTerm">
    <Parameter Name="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="termOnly" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="validUserSchoolRoleId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="isIncludeDistrictAdmin" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetTeacherSchoolByTermResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllTeacherBySchoolIDAndDistrictTermID" Method="GetAllTeacherBySchoolIDAndDistrictTermID">
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistricttermID" Parameter="districttermID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllTeacherBySchoolIDAndDistrictTermIDResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(102)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudentTestDistrictTerm" Method="GetStudentTestDistrictTerm">
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TeacherId" Parameter="teacherId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictTermId" Parameter="districtTermId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClassId" Parameter="classId" Type="System.Int32" DbType="Int" />
    <Parameter Name="VirtualTestIds" Parameter="virtualTestIds" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="VirtualTestSubTypeIds" Parameter="virtualTestSubTypeIds" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ResultDateFrom" Parameter="resultDateFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ResultDateTo" Parameter="resultDateTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetStudentTestDistrictTermResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DistrictTermID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictTermName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XLICreateGroup" Method="XLICreateGroup">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InheritRoleFunctionality" Parameter="inheritRoleFunctionality" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="XLICreateGroupResult">
      <Column Name="XLIGroupID" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XLIDeleteGroup" Method="XLIDeleteGroup">
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XLIUpdateGroup" Method="XLIUpdateGroup">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="InheritRoleFunctionality" Parameter="inheritRoleFunctionality" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="XLIGroupID" Parameter="xLIGroupID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAvailableClassesBySchoolAndStudentId" Method="GetAvailableClassesBySchoolAndStudentId">
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="OffSetRowCount" Parameter="offSetRowCount" Type="System.Int32" DbType="Int" />
    <Parameter Name="FetchRowCount" Parameter="fetchRowCount" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchStr" Parameter="searchStr" Type="System.String" DbType="NVarChar(450)" />
    <Parameter Name="SortBy" Parameter="sortBy" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="GetAvailableClassesBySchoolAndStudentIdResult">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TermName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeacherName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TotalCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SharingGroup_GetUserAvailableAddSharingGroup" Method="SP_SharingGroup_GetUserAvailableAddSharingGroup">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SharingGroupID" Parameter="sharingGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SelectedRoleIds" Parameter="selectedRoleIds" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="SelectedSchoolIds" Parameter="selectedSchoolIds" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="IsShowInactiveUser" Parameter="isShowInactiveUser" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="SortColumn" Parameter="sortColumn" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StartRow" Parameter="startRow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_SharingGroup_GetUserAvailableAddSharingGroupResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatusName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SharingGroupName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SharingGroup_GetUserInSharingGroup" Method="SP_SharingGroup_GetUserInSharingGroup">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SharingGroupID" Parameter="sharingGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsShowInactiveUser" Parameter="isShowInactiveUser" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="SortColumn" Parameter="sortColumn" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StartRow" Parameter="startRow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_SharingGroup_GetUserInSharingGroupResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameFirst" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NameLast" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatusName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SharingGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolList" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SharingGroupName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SharingGroup_CloneSharingGroup" Method="SP_SharingGroup_CloneSharingGroup">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SharingGroupID" Parameter="sharingGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SharingGroup_PublishSharingGroup" Method="SP_SharingGroup_PublishSharingGroup">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SharingGroupID" Parameter="sharingGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsPublished" Parameter="isPublished" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SharingGroup_AssignUsersIntoSharingGroup" Method="SP_SharingGroup_AssignUsersIntoSharingGroup">
    <Parameter Name="SharingGroupID" Parameter="sharingGroupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserIds" Parameter="userIds" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SharingGroup_DeleteSharingGroup" Method="SP_SharingGroup_DeleteSharingGroup">
    <Parameter Name="SharingGroupID" Parameter="sharingGroupID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SharingGroup_GetSharingGroups" Method="SP_SharingGroup_GetSharingGroups">
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GeneralSearch" Parameter="generalSearch" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="ShowInactiveSharingGroup" Parameter="showInactiveSharingGroup" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ShowCreatedByOtherSharingGroup" Parameter="showCreatedByOtherSharingGroup" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SortColumn" Parameter="sortColumn" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SortDirection" Parameter="sortDirection" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="StartRow" Parameter="startRow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalRecord" Parameter="totalRecord" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_SharingGroup_GetSharingGroupsResult">
      <Column Name="SharingGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsPublished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StrUserGroupName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddNewUser" Method="AddNewUser">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="DistrictID" Parameter="districtID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StateID" Parameter="stateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NameFirst" Parameter="nameFirst" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NameLast" Parameter="nameLast" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="HashedPassword" Parameter="hashedPassword" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="LastLoginDate" Parameter="lastLoginDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordLastSetDate" Parameter="passwordLastSetDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SISID" Parameter="sISID" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>