//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkIt.BubbleSheetPortal.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LinkIt Error Reporting")]
        public string DefaultSubject {
            get {
                return ((string)(this["DefaultSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LinkIt")]
        public string XMailer {
            get {
                return ((string)(this["XMailer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LinkIt Error Report - {0}")]
        public string Subject {
            get {
                return ((string)(this["Subject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("From: {0}<br />{1}")]
        public string Body {
            get {
                return ((string)(this["Body"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string SmtpServer {
            get {
                return ((string)(this["SmtpServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notification@linkit.com")]
        public string FromEmail {
            get {
                return ((string)(this["FromEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notification@linkit.com")]
        public string SmtpUsername {
            get {
                return ((string)(this["SmtpUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eniweetok")]
        public string SmtpPassword {
            get {
                return ((string)(this["SmtpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpPort {
            get {
                return ((int)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tungtran@vinasource.com")]
        public string ToEmail {
            get {
                return ((string)(this["ToEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCredential {
            get {
                return ((bool)(this["UseCredential"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n                   " +
            " <license version=\"1.1\">\r\n                    <Customer>\r\n                    <n" +
            "ame>advancedintellect-4060\r\n                    Calvin Fabre   (Fabre, Calvin)\r\n" +
            "                    18211 E. Petroleum Drive\r\n                    Baton Rouge, L" +
            "A   70809\r\n                    US United States\r\n                    225 910 825" +
            "0\r\n                    num:1</name>\r\n                    </Customer>\r\n          " +
            "          <products>\r\n                    <Product>\r\n                    <name>a" +
            "spNetEmail</name>\r\n                    <version>3</version>\r\n                   " +
            " <licensetype>developer</licensetype>\r\n                    <expires>-1</expires>" +
            "\r\n                    </Product>\r\n                    </products>\r\n             " +
            "       <LicenseInformation>\r\n                    <Version>1.1</Version>\r\n       " +
            "             <H1>0</H1>\r\n                    <H2>3pUVH3T9QrMAi/0t9Bke7w==</H2>\r\n" +
            "                    </LicenseInformation>\r\n                    <Signature xmlns=" +
            "\"http://www.w3.org/2000/09/xmldsig#\">\r\n                    <SignedInfo>\r\n       " +
            "             <CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xm" +
            "l-c14n-20010315\" />\r\n                    <SignatureMethod Algorithm=\"http://www." +
            "w3.org/2000/09/xmldsig#rsa-sha1\" />\r\n                    <Reference URI=\"\">\r\n   " +
            "                 <Transforms>\r\n                    <Transform Algorithm=\"http://" +
            "www.w3.org/2000/09/xmldsig#enveloped-signature\" />\r\n                    </Transf" +
            "orms>\r\n                    <DigestMethod Algorithm=\"http://www.w3.org/2000/09/xm" +
            "ldsig#sha1\" />\r\n                    <DigestValue>cpdfioXSugQ2aLbPNBEdwdodN5s=</D" +
            "igestValue>\r\n                    </Reference>\r\n                    </SignedInfo>" +
            "\r\n                    <SignatureValue>F/ryTZk6uO6OIouHRL4qHQkb4gVgFBZaswliiFsgcr" +
            "+fZPwsn1LWzXXVDn4nsgkhcKwbS6v5eGLL13EUbopOBBUMtqzjjs36yUyCTvO3u+M+YX5UnC/+i0Uadu" +
            "RwYzBqzM7M/5IQM3lOKQ7PeeVxK0vEXkKKkRWRBSlvkn9fu6s=</SignatureValue>\r\n           " +
            "         </Signature>\r\n                    </license>\r\n                ")]
        public string AspNetEmailLicence {
            get {
                return ((string)(this["AspNetEmailLicence"]));
            }
        }
    }
}
