<?xml version="1.0" encoding="utf-8"?><Database Name="AdminReportingVNS" Class="RubricDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.217.231.40;Initial Catalog=AdminReportingVNS;Persist Security Info=True;User ID=linkit_user" SettingsObjectName="LinkIt.BubbleSheetPortal.Data.Properties.Settings" SettingsPropertyName="AdminReportingVNSConnectionString30" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RubricTestResultScore" Member="RubricTestResultScoreEntities">
    <Type Name="RubricTestResultScoreEntity">
      <Column Name="RubricTestResultScoreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RubricQuestionCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QTIOnlineTestSessionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="RubricQuestionCategoryEntity_RubricTestResultScoreEntity" Member="RubricQuestionCategoryEntity" ThisKey="RubricQuestionCategoryID" OtherKey="RubricQuestionCategoryID" Type="RubricQuestionCategoryEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RubricQuestionCategory" Member="RubricQuestionCategoryEntities">
    <Type Name="RubricQuestionCategoryEntity">
      <Column Name="RubricQuestionCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryCode" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsPossible" Type="System.Decimal" CanBeNull="true" />
      <Association Name="RubricQuestionCategoryEntity_RubricTestResultScoreEntity" Member="RubricTestResultScoreEntities" ThisKey="RubricQuestionCategoryID" OtherKey="RubricQuestionCategoryID" Type="RubricTestResultScoreEntity" />
      <Association Name="RubricQuestionCategoryEntity_RubricCategoryTierEntity" Member="RubricCategoryTierEntities" ThisKey="RubricQuestionCategoryID" OtherKey="RubricQuestionCategoryID" Type="RubricCategoryTierEntity" />
      <Association Name="RubricQuestionCategoryEntity_RubricCategoryTagEntity" Member="RubricCategoryTagEntities" ThisKey="RubricQuestionCategoryID" OtherKey="RubricQuestionCategoryID" Type="RubricCategoryTagEntity" />
    </Type>
  </Table>
  <Table Name="dbo.RubricCategoryTier" Member="RubricCategoryTierEntities">
    <Type Name="RubricCategoryTierEntity">
      <Column Name="RubricCategoryTierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RubricQuestionCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RubricQuestionCategoryEntity_RubricCategoryTierEntity" Member="RubricQuestionCategoryEntity" ThisKey="RubricQuestionCategoryID" OtherKey="RubricQuestionCategoryID" Type="RubricQuestionCategoryEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RubricCategoryTag" Member="RubricCategoryTagEntities">
    <Type Name="RubricCategoryTagEntity">
      <Column Name="RubricCategoryTagID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RubricQuestionCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TagDescription" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TagCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TagCategoryName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Member="VirtualQuestionID" Type="System.Int32" CanBeNull="true" />
      <Association Name="RubricQuestionCategoryEntity_RubricCategoryTagEntity" Member="RubricQuestionCategoryEntity" ThisKey="RubricQuestionCategoryID" OtherKey="RubricQuestionCategoryID" Type="RubricQuestionCategoryEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetRubricTagByCategoryIdAndIds" Method="GetRubricTagByCategoryIdAndIds">
    <Parameter Name="TagIDs" Parameter="tagIDs" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="CategoryIDs" Parameter="categoryIDs" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="TagType" Parameter="tagType" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetRubricTagByCategoryIdAndIdsResult">
      <Column Name="RubricCategoryTagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RubricQuestionCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TagDescription" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TagCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagCategoryName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllTagsByVirtualQuestion" Method="GetAllTagsByVirtualQuestion">
    <Parameter Name="VirtualQuestionIds" Parameter="virtualQuestionIds" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="GetAllTagsByVirtualQuestionResult">
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="TagCategoryName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TagCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagType" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="VirtualQuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>